// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ModuleSettingRecord {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub module_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub key: ::prost::alloc::string::String,
    /// Always empty for a `secret` setting: its value never leaves db-proxy in
    /// this record. See GetModuleSecretValues.
    #[prost(string, tag="4")]
    pub value: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub value_type: ::prost::alloc::string::String,
    /// Whether a value is stored — the only way to tell for a secret.
    #[prost(bool, tag="6")]
    pub is_set: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListModuleSettingsRequest {
    #[prost(string, tag="1")]
    pub module_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListModuleSettingsResponse {
    #[prost(message, repeated, tag="1")]
    pub settings: ::prost::alloc::vec::Vec<ModuleSettingRecord>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SetModuleSettingRequest {
    #[prost(string, tag="1")]
    pub module_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub value: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub value_type: ::prost::alloc::string::String,
}
/// Writes `value` only while the setting still holds `expected_value`, in one
/// statement: the safe way for a module's functions to change a setting that
/// other runs, or the streamer, may be changing at the same moment. Refused for
/// a `secret` setting, whose stored value is sealed and never compared.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CompareAndSetModuleSettingRequest {
    #[prost(string, tag="1")]
    pub module_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub expected_value: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub value: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CompareAndSetModuleSettingResponse {
    #[prost(bool, tag="1")]
    pub swapped: bool,
    /// The setting as stored after the call: the written row when swapped, else
    /// what it holds now, which is what the caller retries from. Absent when no
    /// such setting exists.
    #[prost(message, optional, tag="2")]
    pub current: ::core::option::Option<ModuleSettingRecord>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ManifestSettingInput {
    #[prost(string, tag="1")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub value: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub value_type: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterModuleSettingsRequest {
    #[prost(string, tag="1")]
    pub module_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="2")]
    pub settings: ::prost::alloc::vec::Vec<ManifestSettingInput>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RegisterModuleSettingsResponse {
    #[prost(int32, tag="1")]
    pub registered: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetModuleSecretValuesRequest {
    #[prost(string, tag="1")]
    pub module_id: ::prost::alloc::string::String,
}
/// Decrypted `secret` settings by key. Only barkloader calls this, to build
/// `ctx.module.settings` for the owning module's functions.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetModuleSecretValuesResponse {
    #[prost(map="string, string", tag="1")]
    pub values: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
include!("module_setting.serde.rs");
include!("module_setting.tonic.rs");
// @@protoc_insertion_point(module)