// Code generated by protoc-gen-twirp v8.1.2, DO NOT EDIT.
// source: module_setting.proto

package v1

import context "context"
import fmt "fmt"
import http "net/http"
import ioutil "io/ioutil"
import json "encoding/json"
import strconv "strconv"
import strings "strings"

import protojson "google.golang.org/protobuf/encoding/protojson"
import proto "google.golang.org/protobuf/proto"
import twirp "github.com/twitchtv/twirp"
import ctxsetters "github.com/twitchtv/twirp/ctxsetters"

// Version compatibility assertion.
// If the constant is not defined in the package, that likely means
// the package needs to be updated to work with this generated code.
// See https://twitchtv.github.io/twirp/docs/version_matrix.html
const _ = twirp.TwirpPackageMinVersion_8_1_0

// ==============================
// ModuleSettingService Interface
// ==============================

type ModuleSettingService interface {
	ListModuleSettings(context.Context, *ListModuleSettingsRequest) (*ListModuleSettingsResponse, error)

	SetModuleSetting(context.Context, *SetModuleSettingRequest) (*ModuleSettingRecord, error)

	RegisterModuleSettings(context.Context, *RegisterModuleSettingsRequest) (*RegisterModuleSettingsResponse, error)

	GetModuleSecretValues(context.Context, *GetModuleSecretValuesRequest) (*GetModuleSecretValuesResponse, error)
}

// ====================================
// ModuleSettingService Protobuf Client
// ====================================

type moduleSettingServiceProtobufClient struct {
	client      HTTPClient
	urls        [4]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewModuleSettingServiceProtobufClient creates a Protobuf client that implements the ModuleSettingService interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewModuleSettingServiceProtobufClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) ModuleSettingService {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwads compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "module_setting", "ModuleSettingService")
	urls := [4]string{
		serviceURL + "ListModuleSettings",
		serviceURL + "SetModuleSetting",
		serviceURL + "RegisterModuleSettings",
		serviceURL + "GetModuleSecretValues",
	}

	return &moduleSettingServiceProtobufClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *moduleSettingServiceProtobufClient) ListModuleSettings(ctx context.Context, in *ListModuleSettingsRequest) (*ListModuleSettingsResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "module_setting")
	ctx = ctxsetters.WithServiceName(ctx, "ModuleSettingService")
	ctx = ctxsetters.WithMethodName(ctx, "ListModuleSettings")
	caller := c.callListModuleSettings
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *ListModuleSettingsRequest) (*ListModuleSettingsResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListModuleSettingsRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListModuleSettingsRequest) when calling interceptor")
					}
					return c.callListModuleSettings(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ListModuleSettingsResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ListModuleSettingsResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *moduleSettingServiceProtobufClient) callListModuleSettings(ctx context.Context, in *ListModuleSettingsRequest) (*ListModuleSettingsResponse, error) {
	out := new(ListModuleSettingsResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *moduleSettingServiceProtobufClient) SetModuleSetting(ctx context.Context, in *SetModuleSettingRequest) (*ModuleSettingRecord, error) {
	ctx = ctxsetters.WithPackageName(ctx, "module_setting")
	ctx = ctxsetters.WithServiceName(ctx, "ModuleSettingService")
	ctx = ctxsetters.WithMethodName(ctx, "SetModuleSetting")
	caller := c.callSetModuleSetting
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *SetModuleSettingRequest) (*ModuleSettingRecord, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*SetModuleSettingRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*SetModuleSettingRequest) when calling interceptor")
					}
					return c.callSetModuleSetting(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ModuleSettingRecord)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ModuleSettingRecord) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *moduleSettingServiceProtobufClient) callSetModuleSetting(ctx context.Context, in *SetModuleSettingRequest) (*ModuleSettingRecord, error) {
	out := new(ModuleSettingRecord)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *moduleSettingServiceProtobufClient) RegisterModuleSettings(ctx context.Context, in *RegisterModuleSettingsRequest) (*RegisterModuleSettingsResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "module_setting")
	ctx = ctxsetters.WithServiceName(ctx, "ModuleSettingService")
	ctx = ctxsetters.WithMethodName(ctx, "RegisterModuleSettings")
	caller := c.callRegisterModuleSettings
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *RegisterModuleSettingsRequest) (*RegisterModuleSettingsResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*RegisterModuleSettingsRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*RegisterModuleSettingsRequest) when calling interceptor")
					}
					return c.callRegisterModuleSettings(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*RegisterModuleSettingsResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*RegisterModuleSettingsResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *moduleSettingServiceProtobufClient) callRegisterModuleSettings(ctx context.Context, in *RegisterModuleSettingsRequest) (*RegisterModuleSettingsResponse, error) {
	out := new(RegisterModuleSettingsResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[2], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *moduleSettingServiceProtobufClient) GetModuleSecretValues(ctx context.Context, in *GetModuleSecretValuesRequest) (*GetModuleSecretValuesResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "module_setting")
	ctx = ctxsetters.WithServiceName(ctx, "ModuleSettingService")
	ctx = ctxsetters.WithMethodName(ctx, "GetModuleSecretValues")
	caller := c.callGetModuleSecretValues
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *GetModuleSecretValuesRequest) (*GetModuleSecretValuesResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetModuleSecretValuesRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetModuleSecretValuesRequest) when calling interceptor")
					}
					return c.callGetModuleSecretValues(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetModuleSecretValuesResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetModuleSecretValuesResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *moduleSettingServiceProtobufClient) callGetModuleSecretValues(ctx context.Context, in *GetModuleSecretValuesRequest) (*GetModuleSecretValuesResponse, error) {
	out := new(GetModuleSecretValuesResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[3], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ================================
// ModuleSettingService JSON Client
// ================================

type moduleSettingServiceJSONClient struct {
	client      HTTPClient
	urls        [4]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewModuleSettingServiceJSONClient creates a JSON client that implements the ModuleSettingService interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewModuleSettingServiceJSONClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) ModuleSettingService {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwads compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "module_setting", "ModuleSettingService")
	urls := [4]string{
		serviceURL + "ListModuleSettings",
		serviceURL + "SetModuleSetting",
		serviceURL + "RegisterModuleSettings",
		serviceURL + "GetModuleSecretValues",
	}

	return &moduleSettingServiceJSONClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *moduleSettingServiceJSONClient) ListModuleSettings(ctx context.Context, in *ListModuleSettingsRequest) (*ListModuleSettingsResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "module_setting")
	ctx = ctxsetters.WithServiceName(ctx, "ModuleSettingService")
	ctx = ctxsetters.WithMethodName(ctx, "ListModuleSettings")
	caller := c.callListModuleSettings
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *ListModuleSettingsRequest) (*ListModuleSettingsResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListModuleSettingsRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListModuleSettingsRequest) when calling interceptor")
					}
					return c.callListModuleSettings(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ListModuleSettingsResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ListModuleSettingsResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *moduleSettingServiceJSONClient) callListModuleSettings(ctx context.Context, in *ListModuleSettingsRequest) (*ListModuleSettingsResponse, error) {
	out := new(ListModuleSettingsResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *moduleSettingServiceJSONClient) SetModuleSetting(ctx context.Context, in *SetModuleSettingRequest) (*ModuleSettingRecord, error) {
	ctx = ctxsetters.WithPackageName(ctx, "module_setting")
	ctx = ctxsetters.WithServiceName(ctx, "ModuleSettingService")
	ctx = ctxsetters.WithMethodName(ctx, "SetModuleSetting")
	caller := c.callSetModuleSetting
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *SetModuleSettingRequest) (*ModuleSettingRecord, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*SetModuleSettingRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*SetModuleSettingRequest) when calling interceptor")
					}
					return c.callSetModuleSetting(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ModuleSettingRecord)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ModuleSettingRecord) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *moduleSettingServiceJSONClient) callSetModuleSetting(ctx context.Context, in *SetModuleSettingRequest) (*ModuleSettingRecord, error) {
	out := new(ModuleSettingRecord)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *moduleSettingServiceJSONClient) RegisterModuleSettings(ctx context.Context, in *RegisterModuleSettingsRequest) (*RegisterModuleSettingsResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "module_setting")
	ctx = ctxsetters.WithServiceName(ctx, "ModuleSettingService")
	ctx = ctxsetters.WithMethodName(ctx, "RegisterModuleSettings")
	caller := c.callRegisterModuleSettings
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *RegisterModuleSettingsRequest) (*RegisterModuleSettingsResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*RegisterModuleSettingsRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*RegisterModuleSettingsRequest) when calling interceptor")
					}
					return c.callRegisterModuleSettings(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*RegisterModuleSettingsResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*RegisterModuleSettingsResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *moduleSettingServiceJSONClient) callRegisterModuleSettings(ctx context.Context, in *RegisterModuleSettingsRequest) (*RegisterModuleSettingsResponse, error) {
	out := new(RegisterModuleSettingsResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[2], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *moduleSettingServiceJSONClient) GetModuleSecretValues(ctx context.Context, in *GetModuleSecretValuesRequest) (*GetModuleSecretValuesResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "module_setting")
	ctx = ctxsetters.WithServiceName(ctx, "ModuleSettingService")
	ctx = ctxsetters.WithMethodName(ctx, "GetModuleSecretValues")
	caller := c.callGetModuleSecretValues
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *GetModuleSecretValuesRequest) (*GetModuleSecretValuesResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetModuleSecretValuesRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetModuleSecretValuesRequest) when calling interceptor")
					}
					return c.callGetModuleSecretValues(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetModuleSecretValuesResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetModuleSecretValuesResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *moduleSettingServiceJSONClient) callGetModuleSecretValues(ctx context.Context, in *GetModuleSecretValuesRequest) (*GetModuleSecretValuesResponse, error) {
	out := new(GetModuleSecretValuesResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[3], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ===================================
// ModuleSettingService Server Handler
// ===================================

type moduleSettingServiceServer struct {
	ModuleSettingService
	interceptor      twirp.Interceptor
	hooks            *twirp.ServerHooks
	pathPrefix       string // prefix for routing
	jsonSkipDefaults bool   // do not include unpopulated fields (default values) in the response
	jsonCamelCase    bool   // JSON fields are serialized as lowerCamelCase rather than keeping the original proto names
}

// NewModuleSettingServiceServer builds a TwirpServer that can be used as an http.Handler to handle
// HTTP requests that are routed to the right method in the provided svc implementation.
// The opts are twirp.ServerOption modifiers, for example twirp.WithServerHooks(hooks).
func NewModuleSettingServiceServer(svc ModuleSettingService, opts ...interface{}) TwirpServer {
	serverOpts := newServerOpts(opts)

	// Using ReadOpt allows backwards and forwads compatibility with new options in the future
	jsonSkipDefaults := false
	_ = serverOpts.ReadOpt("jsonSkipDefaults", &jsonSkipDefaults)
	jsonCamelCase := false
	_ = serverOpts.ReadOpt("jsonCamelCase", &jsonCamelCase)
	var pathPrefix string
	if ok := serverOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	return &moduleSettingServiceServer{
		ModuleSettingService: svc,
		hooks:                serverOpts.Hooks,
		interceptor:          twirp.ChainInterceptors(serverOpts.Interceptors...),
		pathPrefix:           pathPrefix,
		jsonSkipDefaults:     jsonSkipDefaults,
		jsonCamelCase:        jsonCamelCase,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *moduleSettingServiceServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// handleRequestBodyError is used to handle error when the twirp server cannot read request
func (s *moduleSettingServiceServer) handleRequestBodyError(ctx context.Context, resp http.ResponseWriter, msg string, err error) {
	if context.Canceled == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.Canceled, "failed to read request: context canceled"))
		return
	}
	if context.DeadlineExceeded == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.DeadlineExceeded, "failed to read request: deadline exceeded"))
		return
	}
	s.writeError(ctx, resp, twirp.WrapError(malformedRequestError(msg), err))
}

// ModuleSettingServicePathPrefix is a convenience constant that may identify URL paths.
// Should be used with caution, it only matches routes generated by Twirp Go clients,
// with the default "/twirp" prefix and default CamelCase service and method names.
// More info: https://twitchtv.github.io/twirp/docs/routing.html
const ModuleSettingServicePathPrefix = "/twirp/module_setting.ModuleSettingService/"

func (s *moduleSettingServiceServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "module_setting")
	ctx = ctxsetters.WithServiceName(ctx, "ModuleSettingService")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	// Verify path format: [<prefix>]/<package>.<Service>/<Method>
	prefix, pkgService, method := parseTwirpPath(req.URL.Path)
	if pkgService != "module_setting.ModuleSettingService" {
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
	if prefix != s.pathPrefix {
		msg := fmt.Sprintf("invalid path prefix %q, expected %q, on path %q", prefix, s.pathPrefix, req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	switch method {
	case "ListModuleSettings":
		s.serveListModuleSettings(ctx, resp, req)
		return
	case "SetModuleSetting":
		s.serveSetModuleSetting(ctx, resp, req)
		return
	case "RegisterModuleSettings":
		s.serveRegisterModuleSettings(ctx, resp, req)
		return
	case "GetModuleSecretValues":
		s.serveGetModuleSecretValues(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
}

func (s *moduleSettingServiceServer) serveListModuleSettings(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveListModuleSettingsJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveListModuleSettingsProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *moduleSettingServiceServer) serveListModuleSettingsJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ListModuleSettings")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(ListModuleSettingsRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.ModuleSettingService.ListModuleSettings
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *ListModuleSettingsRequest) (*ListModuleSettingsResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListModuleSettingsRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListModuleSettingsRequest) when calling interceptor")
					}
					return s.ModuleSettingService.ListModuleSettings(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ListModuleSettingsResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ListModuleSettingsResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *ListModuleSettingsResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ListModuleSettingsResponse and nil error while calling ListModuleSettings. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *moduleSettingServiceServer) serveListModuleSettingsProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ListModuleSettings")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(ListModuleSettingsRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.ModuleSettingService.ListModuleSettings
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *ListModuleSettingsRequest) (*ListModuleSettingsResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListModuleSettingsRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListModuleSettingsRequest) when calling interceptor")
					}
					return s.ModuleSettingService.ListModuleSettings(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ListModuleSettingsResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ListModuleSettingsResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *ListModuleSettingsResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ListModuleSettingsResponse and nil error while calling ListModuleSettings. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *moduleSettingServiceServer) serveSetModuleSetting(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveSetModuleSettingJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveSetModuleSettingProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *moduleSettingServiceServer) serveSetModuleSettingJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "SetModuleSetting")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(SetModuleSettingRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.ModuleSettingService.SetModuleSetting
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *SetModuleSettingRequest) (*ModuleSettingRecord, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*SetModuleSettingRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*SetModuleSettingRequest) when calling interceptor")
					}
					return s.ModuleSettingService.SetModuleSetting(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ModuleSettingRecord)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ModuleSettingRecord) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *ModuleSettingRecord
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ModuleSettingRecord and nil error while calling SetModuleSetting. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *moduleSettingServiceServer) serveSetModuleSettingProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "SetModuleSetting")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(SetModuleSettingRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.ModuleSettingService.SetModuleSetting
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *SetModuleSettingRequest) (*ModuleSettingRecord, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*SetModuleSettingRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*SetModuleSettingRequest) when calling interceptor")
					}
					return s.ModuleSettingService.SetModuleSetting(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ModuleSettingRecord)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ModuleSettingRecord) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *ModuleSettingRecord
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ModuleSettingRecord and nil error while calling SetModuleSetting. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *moduleSettingServiceServer) serveRegisterModuleSettings(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveRegisterModuleSettingsJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveRegisterModuleSettingsProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *moduleSettingServiceServer) serveRegisterModuleSettingsJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "RegisterModuleSettings")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(RegisterModuleSettingsRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.ModuleSettingService.RegisterModuleSettings
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *RegisterModuleSettingsRequest) (*RegisterModuleSettingsResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*RegisterModuleSettingsRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*RegisterModuleSettingsRequest) when calling interceptor")
					}
					return s.ModuleSettingService.RegisterModuleSettings(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*RegisterModuleSettingsResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*RegisterModuleSettingsResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *RegisterModuleSettingsResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *RegisterModuleSettingsResponse and nil error while calling RegisterModuleSettings. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *moduleSettingServiceServer) serveRegisterModuleSettingsProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "RegisterModuleSettings")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(RegisterModuleSettingsRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.ModuleSettingService.RegisterModuleSettings
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *RegisterModuleSettingsRequest) (*RegisterModuleSettingsResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*RegisterModuleSettingsRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*RegisterModuleSettingsRequest) when calling interceptor")
					}
					return s.ModuleSettingService.RegisterModuleSettings(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*RegisterModuleSettingsResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*RegisterModuleSettingsResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *RegisterModuleSettingsResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *RegisterModuleSettingsResponse and nil error while calling RegisterModuleSettings. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *moduleSettingServiceServer) serveGetModuleSecretValues(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveGetModuleSecretValuesJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveGetModuleSecretValuesProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *moduleSettingServiceServer) serveGetModuleSecretValuesJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetModuleSecretValues")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(GetModuleSecretValuesRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.ModuleSettingService.GetModuleSecretValues
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *GetModuleSecretValuesRequest) (*GetModuleSecretValuesResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetModuleSecretValuesRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetModuleSecretValuesRequest) when calling interceptor")
					}
					return s.ModuleSettingService.GetModuleSecretValues(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetModuleSecretValuesResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetModuleSecretValuesResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *GetModuleSecretValuesResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *GetModuleSecretValuesResponse and nil error while calling GetModuleSecretValues. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *moduleSettingServiceServer) serveGetModuleSecretValuesProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetModuleSecretValues")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(GetModuleSecretValuesRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.ModuleSettingService.GetModuleSecretValues
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *GetModuleSecretValuesRequest) (*GetModuleSecretValuesResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetModuleSecretValuesRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetModuleSecretValuesRequest) when calling interceptor")
					}
					return s.ModuleSettingService.GetModuleSecretValues(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetModuleSecretValuesResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetModuleSecretValuesResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *GetModuleSecretValuesResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *GetModuleSecretValuesResponse and nil error while calling GetModuleSecretValues. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *moduleSettingServiceServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor6, 0
}

func (s *moduleSettingServiceServer) ProtocGenTwirpVersion() string {
	return "v8.1.2"
}

// PathPrefix returns the base service path, in the form: "/<prefix>/<package>.<Service>/"
// that is everything in a Twirp route except for the <Method>. This can be used for routing,
// for example to identify the requests that are targeted to this service in a mux.
func (s *moduleSettingServiceServer) PathPrefix() string {
	return baseServicePath(s.pathPrefix, "module_setting", "ModuleSettingService")
}

var twirpFileDescriptor6 = []byte{
	// 514 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0x65, 0xbb, 0x89, 0x92, 0xa9, 0x54, 0x55, 0x4b, 0x0a, 0x26, 0x90, 0x2a, 0x32, 0x48,
	0x4d, 0x11, 0xb5, 0x45, 0x7b, 0x69, 0xe1, 0x40, 0x85, 0x84, 0x50, 0x25, 0x7a, 0xc0, 0x41, 0x1c,
	0x90, 0xaa, 0x92, 0xc4, 0x93, 0xb0, 0x6a, 0xe2, 0x35, 0xde, 0x75, 0x82, 0x0f, 0xf0, 0x2c, 0xbc,
	0x00, 0x6f, 0xc3, 0x03, 0xa1, 0xac, 0x37, 0x10, 0x6f, 0xed, 0xd6, 0xbd, 0x79, 0xff, 0xec, 0xcc,
	0xfc, 0xfb, 0xcd, 0x4c, 0xa0, 0x35, 0x63, 0x41, 0x32, 0xc5, 0x4b, 0x8e, 0x42, 0xd0, 0x70, 0xe2,
	0x46, 0x31, 0x13, 0x8c, 0x6c, 0xe5, 0x55, 0xe7, 0x97, 0x01, 0xf7, 0xce, 0xa5, 0xd4, 0xcf, 0x14,
	0x1f, 0x47, 0x2c, 0x0e, 0xc8, 0x16, 0x98, 0x34, 0xb0, 0x8d, 0xae, 0xd1, 0x6b, 0xfa, 0x26, 0x0d,
	0xc8, 0x23, 0x68, 0xaa, 0x48, 0x1a, 0xd8, 0xa6, 0x94, 0x1b, 0x99, 0x70, 0x16, 0x90, 0x6d, 0xb0,
	0xae, 0x30, 0xb5, 0x2d, 0x29, 0x2f, 0x3f, 0x49, 0x0b, 0x6a, 0xf3, 0xc1, 0x34, 0x41, 0x7b, 0x43,
	0x6a, 0xd9, 0x81, 0x74, 0x00, 0xe4, 0xc7, 0xa5, 0x48, 0x23, 0xb4, 0x6b, 0xf2, 0xa7, 0xa6, 0x54,
	0x3e, 0xa6, 0x11, 0x92, 0x1d, 0xa8, 0x53, 0xbe, 0x74, 0x66, 0xd7, 0xbb, 0x46, 0xaf, 0xe1, 0xd7,
	0x28, 0xef, 0xa3, 0x70, 0x8e, 0xe1, 0xe1, 0x7b, 0xca, 0x45, 0xce, 0x25, 0xf7, 0xf1, 0x5b, 0x82,
	0x5c, 0xe4, 0x7d, 0x19, 0x79, 0x5f, 0xce, 0x05, 0xb4, 0x8b, 0x22, 0x79, 0xc4, 0x42, 0x8e, 0xe4,
	0x35, 0x34, 0x14, 0x05, 0x6e, 0x1b, 0x5d, 0xab, 0xb7, 0x79, 0xf8, 0xc4, 0xd5, 0x98, 0x15, 0x90,
	0xf1, 0xff, 0x05, 0x39, 0x3f, 0xe0, 0x41, 0x1f, 0x85, 0x76, 0xe7, 0x76, 0x5b, 0x2b, 0x5c, 0x66,
	0x01, 0x2e, 0xab, 0x1c, 0xd7, 0x86, 0x86, 0xcb, 0xb9, 0x80, 0xd6, 0xf9, 0x20, 0xa4, 0x63, 0xe4,
	0x42, 0x55, 0x3f, 0x0b, 0xa3, 0x44, 0xac, 0xd2, 0x1b, 0x05, 0xe9, 0xcd, 0xf2, 0xf4, 0x96, 0x9e,
	0xfe, 0x27, 0x74, 0x7c, 0x9c, 0x50, 0x2e, 0x30, 0xbe, 0x3b, 0x7a, 0x72, 0xba, 0x06, 0xd7, 0x94,
	0x70, 0x9f, 0x5e, 0x83, 0x5b, 0x60, 0x7e, 0x8d, 0xee, 0x29, 0xec, 0x96, 0xd5, 0x57, 0x0d, 0xdc,
	0x05, 0x88, 0xd5, 0x0d, 0xcc, 0x1c, 0xd4, 0xfc, 0x35, 0xc5, 0x79, 0x05, 0x8f, 0xdf, 0xfd, 0xef,
	0xcf, 0x28, 0x46, 0xf1, 0x69, 0xf9, 0xba, 0x6a, 0xb3, 0xf3, 0xdb, 0x80, 0x4e, 0x49, 0xb4, 0x2a,
	0xff, 0x01, 0xea, 0x92, 0xd6, 0x6a, 0x7a, 0x4e, 0xf4, 0x07, 0xde, 0x18, 0xee, 0x66, 0xc7, 0xb7,
	0xa1, 0x88, 0x53, 0x5f, 0x25, 0x6a, 0x9f, 0xc0, 0xe6, 0x9a, 0x5c, 0xb5, 0x93, 0x2f, 0xcd, 0x63,
	0xe3, 0xf0, 0x8f, 0x05, 0xad, 0x1c, 0xa7, 0x3e, 0xc6, 0x73, 0x3a, 0x42, 0x72, 0x05, 0xe4, 0xfa,
	0x12, 0x90, 0x7d, 0xdd, 0x6c, 0xe9, 0x8a, 0xb5, 0x9f, 0x55, 0xb9, 0xaa, 0x98, 0x7c, 0x81, 0x6d,
	0x7d, 0x25, 0xc8, 0x9e, 0x1e, 0x5f, 0xb2, 0x34, 0xed, 0x2a, 0xeb, 0x47, 0x16, 0x70, 0xbf, 0x78,
	0x2c, 0xc8, 0x81, 0x1e, 0x7e, 0xe3, 0xf8, 0xb6, 0xdd, 0xaa, 0xd7, 0xd5, 0xd3, 0x04, 0xec, 0x14,
	0x36, 0x94, 0x3c, 0xaf, 0xd8, 0xf7, 0xac, 0xec, 0xc1, 0x9d, 0xa6, 0xe4, 0xcd, 0xfe, 0xe7, 0xbd,
	0x09, 0x15, 0x5f, 0x93, 0xa1, 0x3b, 0x62, 0x33, 0x6f, 0xc1, 0xa6, 0xe3, 0x74, 0x36, 0x58, 0xba,
	0xf4, 0x16, 0x8c, 0x8d, 0xbf, 0x1f, 0x79, 0xc1, 0xd0, 0x9b, 0x60, 0xe8, 0xcd, 0x5f, 0x0c, 0xeb,
	0xf2, 0x1f, 0xfe, 0xe8, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x83, 0x97, 0xe0, 0xee, 0xf9, 0x05,
	0x00, 0x00,
}
