// Regenerates google-fonts.generated.ts from the Google Fonts catalog:
//
//   bun run generate:google-fonts
//
// Only each family's name and category are kept, most popular first, so the
// list stays a few tens of KB however many families the catalog grows to. The
// font files themselves are fetched by the scene manager on first use.

import { join } from "node:path";
import { GOOGLE_FONT_CATEGORIES, type GoogleFontCategory, isGoogleFontFamilyName } from "../google-fonts";

const METADATA_URL = "https://fonts.google.com/metadata/fonts";
const OUTPUT = join(import.meta.dir, "..", "google-fonts.generated.ts");

/** The catalog's category labels, by the token the list stores. */
const CATALOG_CATEGORIES: Record<string, GoogleFontCategory> = {
  "Sans Serif": "sans-serif",
  Serif: "serif",
  Display: "display",
  Handwriting: "handwriting",
  Monospace: "monospace",
};

interface CatalogFamily {
  family: string;
  category: string;
  popularity: number;
}

const response = await fetch(METADATA_URL);
if (!response.ok) {
  throw new Error(`google fonts metadata: ${METADATA_URL} answered ${response.status}`);
}
const catalog = (await response.json()) as { familyMetadataList?: CatalogFamily[] };
const families = catalog.familyMetadataList;
if (!Array.isArray(families) || families.length === 0) {
  throw new Error("google fonts metadata: no familyMetadataList");
}

const rows = [...families]
  .sort((a, b) => a.popularity - b.popularity || a.family.localeCompare(b.family))
  .map((entry) => {
    const category = CATALOG_CATEGORIES[entry.category];
    if (category === undefined) {
      throw new Error(`google fonts metadata: ${entry.family} has an unknown category ${entry.category}`);
    }
    // The name becomes part of a URL the scene manager requests, so a family
    // outside the accepted shape is a reason to stop, not to skip silently.
    if (!isGoogleFontFamilyName(entry.family)) {
      throw new Error(`google fonts metadata: ${JSON.stringify(entry.family)} is not an accepted family name`);
    }
    return `[${JSON.stringify(entry.family)},${GOOGLE_FONT_CATEGORIES.indexOf(category)}]`;
  });

const source = `// Generated by scripts/generate-google-fonts.ts from ${METADATA_URL}. Do not edit.
//
// Every Google Fonts family, most popular first, as [family, category], the
// category being an index into GOOGLE_FONT_CATEGORIES.

export const GOOGLE_FONT_ROWS: readonly (readonly [string, number])[] = [
${rows.join(",\n")}
];
`;

await Bun.write(OUTPUT, source);
console.log(`wrote ${rows.length} families to ${OUTPUT}`);
