version: "0.5"

environment:
  - "FORCE_COLOR=1"

processes:
  api:
    command: bun run dev
    description: woofx3 API
    working_dir: api

  barkloader:
    command: cargo run .
    description: Plugin Module System
    working_dir: barkloader-rust

  cloudflare:
    command: cloudflared tunnel --url http://localhost:9001

  db:
    command: go run .
    description: proxy for accessing databases
    working_dir: db

  messagebus:
    command: GO_ENV=development go run .
    description: communication message bus
    working_dir: services/nats

  # streamlabs:
  #   command: PORT=5175 bun run dev
  #   description: slobs
  #   working_dir: streamlabs
  #   depends_on:
  #     woofwoofwoof:
  #       condition: process_started

  twitch:
    command: bun run src/api.ts
    description: Twitch API + Eventbus
    working_dir: twitch

  workflow:
    command: go run .
    description: Workflow Management
    working_dir: workflow

  woofwoofwoof:
    command: bun run src/woofwoofwoof.ts
    description: Twitch Chatbot
    working_dir: woofwoofwoof
