version: "0.5"

environment:
  - "FORCE_COLOR=1"

processes:
  auth:
    command: go run src/main.go
    description: supertokens auth
    working_dir: auth

  barkloader:
    command: bun run start
    description: Plugin Module System
    working_dir: barkloader
    depends_on:
      wooflow:
        condition: process_started

  barkloader-rust:
    command: cargo run .
    description: Plugin Module System
    working_dir: barkloader-rust
    depends_on:
      wooflow:
        condition: process_started

  # caddy:
  #   command: "caddy run"
  #   description: "start caddy proxy"
  #   is_elevated: true
  #   shutdown:
  #     command: "caddy stop"
  #     signal: 15

  db:
    command: go run .
    description: proxy for accessing databases
    working_dir: db/cmd/server
    ready_log_line: "Starting server"

  permissions:
    command: go run . 
    description: viewer permissions
    working_dir: permissions/src
    depends_on:
      db:
        condition: process_log_ready


  # extension-be:
  #   command: bun run dev
  #   description: Twitch Data Center Extension Development
  #   working_dir: extension

  # extension-fe:
  #   command: bun run dev
  #   description: Twitch Data Center Extension Development
  #   working_dir: extension/client

  # reward:
  #   command: bun run src/index.ts
  #   description: Twitch Viewer Rewards
  #   working_dir: reward

  streamlabs:
    command: PORT=5175 bun run dev
    description: slobs
    working_dir: streamlabs
    depends_on:
      woofwoofwoof:
        condition: process_started

  # streamerui:
  #   command: bun run dev
  #   description: Off-Twitch UI for managing things
  #   working_dir: streamerui
  #   depends_on:
  #     caddy:
  #       condition: process_started

  temporal-server:
    command: temporal server start-dev
    description: Temporal Server

  twitch:
    command: bun run src/api.ts
    description: Twitch API + Eventbus
    working_dir: twitch
    depends_on:
      db:
        condition: process_log_ready
      barkloader-rust:
        condition: process_started
      wooflow:
        condition: process_started

  # voice:
  #   command: go run ./src --url https://www.twitch.tv/wolfymaster
  #   description: Voice control stream
  #   working_dir: stream        

  wooflow:
    command: go run .
    description: Workflow Management
    working_dir: wooflow
    depends_on:
      temporal-server:
        condition: process_started

  woofwoofwoof:
    command: bun run woofwoofwoof/src/woofwoofwoof.ts
    description: Twitch Chatbot
    depends_on:
      db:
        condition: process_log_ready
      twitch:
        condition: process_started

  messagebus-gateway:
    command: go run .
    description: Message Bus Gateway (WebSocket to NATS bridge)
    working_dir: services/messagebus-gateway
    ready_log_line: "Server starting"
