version: "0.5"

environment:
  - "FORCE_COLOR=1"

processes:
  barkloader:
    command: bun run start
    description: Plugin Module System
    working_dir: barkloader
    depends_on:
      wooflow:
        condition: process_started

  barkloader-rust:
    command: cargo run .
    description: Plugin Module System
    working_dir: barkloader-rust
    depends_on:
      wooflow:
        condition: process_started

  db:
    command: go run .
    description: proxy for accessing databases
    working_dir: db/cmd/server
    ready_log_line: "Starting server"

  messagebus:
    command: go run .
    description: communication message bus
    working_dir: services/messagebus-gateway

  streamlabs:
    command: PORT=5175 bun run dev
    description: slobs
    working_dir: streamlabs
    depends_on:
      woofwoofwoof:
        condition: process_started

  temporal-server:
    command: temporal server start-dev
    description: Temporal Server

  twitch:
    command: bun run src/api.ts
    description: Twitch API + Eventbus
    working_dir: twitch
    depends_on:
      db:
        condition: process_log_ready
      messagebus:
        condition: process_started
      # barkloader-rust:
        # condition: process_started
      # wooflow:
        # condition: process_started

  wooflow:
    command: go run .
    description: Workflow Management
    working_dir: wooflow
    depends_on:
      temporal-server:
        condition: process_started

  woofwoofwoof:
    command: bun run woofwoofwoof/src/woofwoofwoof.ts
    description: Twitch Chatbot
    depends_on:
      db:
        condition: process_log_ready
      twitch:
        condition: process_started
