version: "0.5"

processes:
  auth:
    command: go run src/main.go
    description: supertokens auth
    working_dir: auth

  barkloader:
    command: bun run start
    description: Plugin Module System
    working_dir: barkloader

  caddy:
    command: "caddy run"
    description: "start caddy proxy"
    is_elevated: true
    shutdown:
      command: "caddy stop"
      signal: 15

  db:
    command: go run .
    description: proxy for accessing databases
    working_dir: db
    ready_log_line: "Connected to the database!"

  extension-be:
    command: bun run dev
    description: Twitch Data Center Extension Development
    working_dir: extension

  extension-fe:
    command: bun run dev
    description: Twitch Data Center Extension Development
    working_dir: extension/client

  reward:
    command: bun run src/index.ts
    description: Twitch Viewer Rewards
    working_dir: reward

  streamlabs:
    command: PORT=5175 bun run dev
    description: slobs
    working_dir: streamlabs

  streamerui:
    command: bun run dev
    description: Off-Twitch UI for managing things
    working_dir: streamerui
    depends_on:
      caddy:
        condition: process_started

  temporal-server:
    command: temporal server start-dev
    description: Temporal Server

  twitch:
    command: bun run src/api.ts
    description: Twitch API + Eventbus
    working_dir: twitch
    depends_on:
      db:
        condition: process_log_ready

  voice:
    command: go run ./src --url https://www.twitch.tv/wolfymaster
    description: Voice control stream
    working_dir: stream        

  woofwoofwoof:
    command: bun run woofwoofwoof/src/woofwoofwoof.ts
    description: Twitch Chatbot
    depends_on:
      db:
        condition: process_log_ready