package barkloader

import (
	"encoding/json"
	"testing"
)

// The frame barkloader actually sends when a sandbox function throws:
// `data` is a bare JSON string. Declaring it as a map made this fail to
// unmarshal, so the frame was dropped and the caller waited out the full
// 30-second invoke timeout instead of being told what happened.
func TestAnErrorFrameWithStringDataDeserializes(t *testing.T) {
	raw := []byte(`{"type":"error","id":"r1","data":"Runtime execution error: Exception generated by QuickJS"}`)

	var response InvokeResponse
	if err := json.Unmarshal(raw, &response); err != nil {
		t.Fatalf("error frame must deserialize, got: %v", err)
	}
	if response.Type != "error" || response.Id != "r1" {
		t.Fatalf("type=%q id=%q", response.Type, response.Id)
	}
	if got := response.ErrorMessage(); got != "Runtime execution error: Exception generated by QuickJS" {
		t.Errorf("ErrorMessage() = %q", got)
	}
}

// The shape the client was originally written against. Both must work, so a
// sender on either contract is understood.
func TestAnErrorFrameWithObjectDataDeserializes(t *testing.T) {
	raw := []byte(`{"type":"error","id":"r1","data":{"error":"boom"}}`)

	var response InvokeResponse
	if err := json.Unmarshal(raw, &response); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}
	if got := response.ErrorMessage(); got != "boom" {
		t.Errorf("ErrorMessage() = %q, want boom", got)
	}
}

func TestErrorMessageFallsBackToDataAndMessageKeys(t *testing.T) {
	for _, body := range []string{`{"data":"via-data"}`, `{"message":"via-message"}`} {
		var response InvokeResponse
		if err := json.Unmarshal([]byte(`{"type":"error","data":`+body+`}`), &response); err != nil {
			t.Fatalf("unmarshal %s: %v", body, err)
		}
		if got := response.ErrorMessage(); got == "" || got == "unknown error" {
			t.Errorf("ErrorMessage() for %s = %q", body, got)
		}
	}
}

func TestErrorMessageNeverReturnsEmpty(t *testing.T) {
	var response InvokeResponse
	if err := json.Unmarshal([]byte(`{"type":"error","data":null}`), &response); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}
	if got := response.ErrorMessage(); got == "" {
		t.Error("ErrorMessage() must always say something")
	}
}

func TestAResultFrameStillDecodesAsAnObject(t *testing.T) {
	raw := []byte(`{"type":"result","id":"r1","data":{"result":{"next":5}}}`)

	var response InvokeResponse
	if err := json.Unmarshal(raw, &response); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}
	data := response.DataObject()
	result, ok := data["result"].(map[string]interface{})
	if !ok {
		t.Fatalf("result missing, data=%v", data)
	}
	if result["next"] != float64(5) {
		t.Errorf("next = %v, want 5", result["next"])
	}
}

// A result frame whose data is not an object must read as "no result"
// rather than panicking on a nil map.
func TestANonObjectResultFrameYieldsNoData(t *testing.T) {
	var response InvokeResponse
	if err := json.Unmarshal([]byte(`{"type":"result","data":"scalar"}`), &response); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}
	if data := response.DataObject(); data != nil {
		t.Errorf("DataObject() = %v, want nil", data)
	}
	if _, ok := response.DataObject()["result"]; ok {
		t.Error("reading a missing key from a nil map must be safe and absent")
	}
}
