[package]
name = "lib_module"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
async-trait = "0.1"
lib_repository = { path = "../lib_repository" }
lib_sandbox = { path = "../lib_sandbox" }
log = "0.4"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9.34"
sha2 = "0.10"
tokio = { version = "1", features = ["sync", "rt", "macros"] }
woofx3 = { path = "../../shared/clients/rust/db" }
woofx3-twirp = { path = "../../shared/clients/rust/twirp" }

[dev-dependencies]
tempfile = "3"
