// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OverlayToken {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    /// Plaintext credential, format "ovl_" + base58(32 random bytes).
    /// Generated db-proxy-side; never accepted from callers.
    #[prost(string, tag="2")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub scene_id: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub application_id: ::prost::alloc::string::String,
    /// Operator bookkeeping (e.g. "OBS main PC"). Free-form.
    #[prost(string, tag="5")]
    pub label: ::prost::alloc::string::String,
    /// "active" | "revoked".
    #[prost(string, tag="6")]
    pub status: ::prost::alloc::string::String,
    #[prost(message, optional, tag="7")]
    pub created_at: ::core::option::Option<::pbjson_types::Timestamp>,
    #[prost(message, optional, tag="8")]
    pub revoked_at: ::core::option::Option<::pbjson_types::Timestamp>,
    #[prost(message, optional, tag="9")]
    pub last_used_at: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MintOverlayTokenRequest {
    #[prost(string, tag="1")]
    pub scene_id: ::prost::alloc::string::String,
    /// Empty resolves to the default application (same convention as
    /// CreateSceneRequest). The scene must belong to this application.
    #[prost(string, tag="2")]
    pub application_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub label: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevokeOverlayTokenRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RotateOverlayTokenRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OverlayTokenResponse {
    #[prost(message, optional, tag="1")]
    pub status: ::core::option::Option<super::common::ResponseStatus>,
    #[prost(message, optional, tag="2")]
    pub overlay_token: ::core::option::Option<OverlayToken>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListOverlayTokensRequest {
    #[prost(string, tag="1")]
    pub scene_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub application_id: ::prost::alloc::string::String,
    /// Revoked tombstones are excluded unless explicitly requested.
    #[prost(bool, tag="3")]
    pub include_revoked: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListOverlayTokensResponse {
    #[prost(message, optional, tag="1")]
    pub status: ::core::option::Option<super::common::ResponseStatus>,
    #[prost(message, repeated, tag="2")]
    pub overlay_tokens: ::prost::alloc::vec::Vec<OverlayToken>,
    #[prost(int32, tag="3")]
    pub total_count: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResolveOverlayTokenRequest {
    #[prost(string, tag="1")]
    pub token: ::prost::alloc::string::String,
}
/// Engine-internal resolution result. Active tokens return OK with the
/// bound scene/application; revoked and unknown tokens return byte-for-
/// byte identical NOT_FOUND responses.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResolveOverlayTokenResponse {
    #[prost(message, optional, tag="1")]
    pub status: ::core::option::Option<super::common::ResponseStatus>,
    #[prost(string, tag="2")]
    pub scene_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub application_id: ::prost::alloc::string::String,
}
include!("overlay_token.serde.rs");
include!("overlay_token.tonic.rs");
// @@protoc_insertion_point(module)