// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: module_resource_instance.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ModuleResourceInstance is a runtime-created instance of a kind that an
// installed barkloader module declares it provides. This is the K8s
// custom-resource analog: the engine learns identity (module + kind +
// instance_id) and owns referential integrity, but never learns what the
// kind *means*. All semantics (value storage, mutation operations,
// validation) live in the owning module.
//
// Identity:
//
//	`module_id`     FK to modules.id (the owning module / "controller")
//	`kind`          manifest-declared kind string (e.g. "counter")
//	`instance_id`   instance-local id (e.g. "death_count")
//	canonical id    `{module_name}:{kind}:{instance_id}` — derived
//
// `module_name` is the bare manifest id segment (e.g. "counter"), copied
// to the wire so consumers don't need a second lookup to render the
// canonical id.
//
// `display_name` is the user-facing label. It can drift across the
// instance's lifetime without affecting identity.
type ModuleResourceInstance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ModuleId      string                 `protobuf:"bytes,2,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	ModuleName    string                 `protobuf:"bytes,3,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"`
	Kind          string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	InstanceId    string                 `protobuf:"bytes,5,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,6,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	CanonicalId   string                 `protobuf:"bytes,7,opt,name=canonical_id,json=canonicalId,proto3" json:"canonical_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleResourceInstance) Reset() {
	*x = ModuleResourceInstance{}
	mi := &file_module_resource_instance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleResourceInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleResourceInstance) ProtoMessage() {}

func (x *ModuleResourceInstance) ProtoReflect() protoreflect.Message {
	mi := &file_module_resource_instance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleResourceInstance.ProtoReflect.Descriptor instead.
func (*ModuleResourceInstance) Descriptor() ([]byte, []int) {
	return file_module_resource_instance_proto_rawDescGZIP(), []int{0}
}

func (x *ModuleResourceInstance) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ModuleResourceInstance) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *ModuleResourceInstance) GetModuleName() string {
	if x != nil {
		return x.ModuleName
	}
	return ""
}

func (x *ModuleResourceInstance) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ModuleResourceInstance) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ModuleResourceInstance) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ModuleResourceInstance) GetCanonicalId() string {
	if x != nil {
		return x.CanonicalId
	}
	return ""
}

func (x *ModuleResourceInstance) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ModuleResourceInstance) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateResourceInstanceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Owning module UUID. Optional when `module_name` is set; the server
	// resolves the UUID from the name in that case (single Postgres lookup
	// backed by the unique index on `modules.name`).
	ModuleId       string          `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	Kind           string          `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	InstanceId     string          `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	DisplayName    string          `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	RequestContext *RequestContext `protobuf:"bytes,5,opt,name=request_context,json=requestContext,proto3" json:"request_context,omitempty"`
	// Owning module's manifest id (== `modules.name`). Sandbox callers
	// (`ctx.resources.create`) typically know the manifest id but not the
	// UUID — passing this avoids a separate `GetModuleByName` round-trip.
	// When both are set, `module_id` wins.
	ModuleName    string `protobuf:"bytes,6,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResourceInstanceRequest) Reset() {
	*x = CreateResourceInstanceRequest{}
	mi := &file_module_resource_instance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResourceInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResourceInstanceRequest) ProtoMessage() {}

func (x *CreateResourceInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_module_resource_instance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResourceInstanceRequest.ProtoReflect.Descriptor instead.
func (*CreateResourceInstanceRequest) Descriptor() ([]byte, []int) {
	return file_module_resource_instance_proto_rawDescGZIP(), []int{1}
}

func (x *CreateResourceInstanceRequest) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *CreateResourceInstanceRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *CreateResourceInstanceRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *CreateResourceInstanceRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreateResourceInstanceRequest) GetRequestContext() *RequestContext {
	if x != nil {
		return x.RequestContext
	}
	return nil
}

func (x *CreateResourceInstanceRequest) GetModuleName() string {
	if x != nil {
		return x.ModuleName
	}
	return ""
}

type ResourceInstanceResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Status        *ResponseStatus         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Instance      *ModuleResourceInstance `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceInstanceResponse) Reset() {
	*x = ResourceInstanceResponse{}
	mi := &file_module_resource_instance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceInstanceResponse) ProtoMessage() {}

func (x *ResourceInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_module_resource_instance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceInstanceResponse.ProtoReflect.Descriptor instead.
func (*ResourceInstanceResponse) Descriptor() ([]byte, []int) {
	return file_module_resource_instance_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceInstanceResponse) GetStatus() *ResponseStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ResourceInstanceResponse) GetInstance() *ModuleResourceInstance {
	if x != nil {
		return x.Instance
	}
	return nil
}

type DeleteResourceInstanceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CanonicalId    string                 `protobuf:"bytes,1,opt,name=canonical_id,json=canonicalId,proto3" json:"canonical_id,omitempty"`
	RequestContext *RequestContext        `protobuf:"bytes,2,opt,name=request_context,json=requestContext,proto3" json:"request_context,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteResourceInstanceRequest) Reset() {
	*x = DeleteResourceInstanceRequest{}
	mi := &file_module_resource_instance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResourceInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceInstanceRequest) ProtoMessage() {}

func (x *DeleteResourceInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_module_resource_instance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceInstanceRequest.ProtoReflect.Descriptor instead.
func (*DeleteResourceInstanceRequest) Descriptor() ([]byte, []int) {
	return file_module_resource_instance_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteResourceInstanceRequest) GetCanonicalId() string {
	if x != nil {
		return x.CanonicalId
	}
	return ""
}

func (x *DeleteResourceInstanceRequest) GetRequestContext() *RequestContext {
	if x != nil {
		return x.RequestContext
	}
	return nil
}

type GetResourceInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CanonicalId   string                 `protobuf:"bytes,1,opt,name=canonical_id,json=canonicalId,proto3" json:"canonical_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceInstanceRequest) Reset() {
	*x = GetResourceInstanceRequest{}
	mi := &file_module_resource_instance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceInstanceRequest) ProtoMessage() {}

func (x *GetResourceInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_module_resource_instance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceInstanceRequest.ProtoReflect.Descriptor instead.
func (*GetResourceInstanceRequest) Descriptor() ([]byte, []int) {
	return file_module_resource_instance_proto_rawDescGZIP(), []int{4}
}

func (x *GetResourceInstanceRequest) GetCanonicalId() string {
	if x != nil {
		return x.CanonicalId
	}
	return ""
}

type ListResourceInstancesByKindRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourceInstancesByKindRequest) Reset() {
	*x = ListResourceInstancesByKindRequest{}
	mi := &file_module_resource_instance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourceInstancesByKindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourceInstancesByKindRequest) ProtoMessage() {}

func (x *ListResourceInstancesByKindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_module_resource_instance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourceInstancesByKindRequest.ProtoReflect.Descriptor instead.
func (*ListResourceInstancesByKindRequest) Descriptor() ([]byte, []int) {
	return file_module_resource_instance_proto_rawDescGZIP(), []int{5}
}

func (x *ListResourceInstancesByKindRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type ListResourceInstancesByModuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModuleId      string                 `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourceInstancesByModuleRequest) Reset() {
	*x = ListResourceInstancesByModuleRequest{}
	mi := &file_module_resource_instance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourceInstancesByModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourceInstancesByModuleRequest) ProtoMessage() {}

func (x *ListResourceInstancesByModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_module_resource_instance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourceInstancesByModuleRequest.ProtoReflect.Descriptor instead.
func (*ListResourceInstancesByModuleRequest) Descriptor() ([]byte, []int) {
	return file_module_resource_instance_proto_rawDescGZIP(), []int{6}
}

func (x *ListResourceInstancesByModuleRequest) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

type ListResourceInstancesResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Status        *ResponseStatus           `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Instances     []*ModuleResourceInstance `protobuf:"bytes,2,rep,name=instances,proto3" json:"instances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourceInstancesResponse) Reset() {
	*x = ListResourceInstancesResponse{}
	mi := &file_module_resource_instance_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourceInstancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourceInstancesResponse) ProtoMessage() {}

func (x *ListResourceInstancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_module_resource_instance_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourceInstancesResponse.ProtoReflect.Descriptor instead.
func (*ListResourceInstancesResponse) Descriptor() ([]byte, []int) {
	return file_module_resource_instance_proto_rawDescGZIP(), []int{7}
}

func (x *ListResourceInstancesResponse) GetStatus() *ResponseStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ListResourceInstancesResponse) GetInstances() []*ModuleResourceInstance {
	if x != nil {
		return x.Instances
	}
	return nil
}

var File_module_resource_instance_proto protoreflect.FileDescriptor

const file_module_resource_instance_proto_rawDesc = "" +
	"\n" +
	"\x1emodule_resource_instance.proto\x12\x06module\x1a\fcommon.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd7\x02\n" +
	"\x16ModuleResourceInstance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tmodule_id\x18\x02 \x01(\tR\bmoduleId\x12\x1f\n" +
	"\vmodule_name\x18\x03 \x01(\tR\n" +
	"moduleName\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12\x1f\n" +
	"\vinstance_id\x18\x05 \x01(\tR\n" +
	"instanceId\x12!\n" +
	"\fdisplay_name\x18\x06 \x01(\tR\vdisplayName\x12!\n" +
	"\fcanonical_id\x18\a \x01(\tR\vcanonicalId\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xf6\x01\n" +
	"\x1dCreateResourceInstanceRequest\x12\x1b\n" +
	"\tmodule_id\x18\x01 \x01(\tR\bmoduleId\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12?\n" +
	"\x0frequest_context\x18\x05 \x01(\v2\x16.common.RequestContextR\x0erequestContext\x12\x1f\n" +
	"\vmodule_name\x18\x06 \x01(\tR\n" +
	"moduleName\"\x86\x01\n" +
	"\x18ResourceInstanceResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\v2\x16.common.ResponseStatusR\x06status\x12:\n" +
	"\binstance\x18\x02 \x01(\v2\x1e.module.ModuleResourceInstanceR\binstance\"\x83\x01\n" +
	"\x1dDeleteResourceInstanceRequest\x12!\n" +
	"\fcanonical_id\x18\x01 \x01(\tR\vcanonicalId\x12?\n" +
	"\x0frequest_context\x18\x02 \x01(\v2\x16.common.RequestContextR\x0erequestContext\"?\n" +
	"\x1aGetResourceInstanceRequest\x12!\n" +
	"\fcanonical_id\x18\x01 \x01(\tR\vcanonicalId\"8\n" +
	"\"ListResourceInstancesByKindRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\"C\n" +
	"$ListResourceInstancesByModuleRequest\x12\x1b\n" +
	"\tmodule_id\x18\x01 \x01(\tR\bmoduleId\"\x8d\x01\n" +
	"\x1dListResourceInstancesResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\v2\x16.common.ResponseStatusR\x06status\x12<\n" +
	"\tinstances\x18\x02 \x03(\v2\x1e.module.ModuleResourceInstanceR\tinstancesB)Z'github.com/wolfymaster/woofx3/db/gen/v1b\x06proto3"

var (
	file_module_resource_instance_proto_rawDescOnce sync.Once
	file_module_resource_instance_proto_rawDescData []byte
)

func file_module_resource_instance_proto_rawDescGZIP() []byte {
	file_module_resource_instance_proto_rawDescOnce.Do(func() {
		file_module_resource_instance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_module_resource_instance_proto_rawDesc), len(file_module_resource_instance_proto_rawDesc)))
	})
	return file_module_resource_instance_proto_rawDescData
}

var file_module_resource_instance_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_module_resource_instance_proto_goTypes = []any{
	(*ModuleResourceInstance)(nil),               // 0: module.ModuleResourceInstance
	(*CreateResourceInstanceRequest)(nil),        // 1: module.CreateResourceInstanceRequest
	(*ResourceInstanceResponse)(nil),             // 2: module.ResourceInstanceResponse
	(*DeleteResourceInstanceRequest)(nil),        // 3: module.DeleteResourceInstanceRequest
	(*GetResourceInstanceRequest)(nil),           // 4: module.GetResourceInstanceRequest
	(*ListResourceInstancesByKindRequest)(nil),   // 5: module.ListResourceInstancesByKindRequest
	(*ListResourceInstancesByModuleRequest)(nil), // 6: module.ListResourceInstancesByModuleRequest
	(*ListResourceInstancesResponse)(nil),        // 7: module.ListResourceInstancesResponse
	(*timestamppb.Timestamp)(nil),                // 8: google.protobuf.Timestamp
	(*RequestContext)(nil),                       // 9: common.RequestContext
	(*ResponseStatus)(nil),                       // 10: common.ResponseStatus
}
var file_module_resource_instance_proto_depIdxs = []int32{
	8,  // 0: module.ModuleResourceInstance.created_at:type_name -> google.protobuf.Timestamp
	8,  // 1: module.ModuleResourceInstance.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 2: module.CreateResourceInstanceRequest.request_context:type_name -> common.RequestContext
	10, // 3: module.ResourceInstanceResponse.status:type_name -> common.ResponseStatus
	0,  // 4: module.ResourceInstanceResponse.instance:type_name -> module.ModuleResourceInstance
	9,  // 5: module.DeleteResourceInstanceRequest.request_context:type_name -> common.RequestContext
	10, // 6: module.ListResourceInstancesResponse.status:type_name -> common.ResponseStatus
	0,  // 7: module.ListResourceInstancesResponse.instances:type_name -> module.ModuleResourceInstance
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_module_resource_instance_proto_init() }
func file_module_resource_instance_proto_init() {
	if File_module_resource_instance_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_module_resource_instance_proto_rawDesc), len(file_module_resource_instance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_module_resource_instance_proto_goTypes,
		DependencyIndexes: file_module_resource_instance_proto_depIdxs,
		MessageInfos:      file_module_resource_instance_proto_msgTypes,
	}.Build()
	File_module_resource_instance_proto = out.File
	file_module_resource_instance_proto_goTypes = nil
	file_module_resource_instance_proto_depIdxs = nil
}
