// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: scene.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Scene struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ApplicationId string                 `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// JSON array of placed widget instances. Shape:
	// `[{ id, widgetCanonicalId, position, settings }, ...]`.
	// Persisted verbatim in `scenes.widgets_json` (JSONB).
	WidgetsJson string `protobuf:"bytes,5,opt,name=widgets_json,json=widgetsJson,proto3" json:"widgets_json,omitempty"`
	// JSON object describing canvas-level layout (dimensions, grid,
	// theme). Optional; most scenes will store `{}`. Persisted
	// verbatim in `scenes.layout_json` (JSONB).
	LayoutJson string `protobuf:"bytes,6,opt,name=layout_json,json=layoutJson,proto3" json:"layout_json,omitempty"`
	// Origin metadata. `created_by_type` is "USER" for UI-authored
	// scenes and "MODULE" if a future manifest surface ships preset
	// scenes. `created_by_ref` is the composite moduleKey for MODULE
	// rows, empty for USER rows.
	CreatedByType string                 `protobuf:"bytes,7,opt,name=created_by_type,json=createdByType,proto3" json:"created_by_type,omitempty"`
	CreatedByRef  string                 `protobuf:"bytes,8,opt,name=created_by_ref,json=createdByRef,proto3" json:"created_by_ref,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scene) Reset() {
	*x = Scene{}
	mi := &file_scene_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scene) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scene) ProtoMessage() {}

func (x *Scene) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scene.ProtoReflect.Descriptor instead.
func (*Scene) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{0}
}

func (x *Scene) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Scene) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *Scene) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Scene) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Scene) GetWidgetsJson() string {
	if x != nil {
		return x.WidgetsJson
	}
	return ""
}

func (x *Scene) GetLayoutJson() string {
	if x != nil {
		return x.LayoutJson
	}
	return ""
}

func (x *Scene) GetCreatedByType() string {
	if x != nil {
		return x.CreatedByType
	}
	return ""
}

func (x *Scene) GetCreatedByRef() string {
	if x != nil {
		return x.CreatedByRef
	}
	return ""
}

func (x *Scene) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Scene) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateSceneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// JSON-encoded widget-instances array. Persisted verbatim into
	// `scenes.widgets_json`.
	WidgetsJson string `protobuf:"bytes,4,opt,name=widgets_json,json=widgetsJson,proto3" json:"widgets_json,omitempty"`
	// JSON-encoded layout object. Persisted verbatim into
	// `scenes.layout_json`.
	LayoutJson    string `protobuf:"bytes,5,opt,name=layout_json,json=layoutJson,proto3" json:"layout_json,omitempty"`
	CreatedByType string `protobuf:"bytes,6,opt,name=created_by_type,json=createdByType,proto3" json:"created_by_type,omitempty"`
	CreatedByRef  string `protobuf:"bytes,7,opt,name=created_by_ref,json=createdByRef,proto3" json:"created_by_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSceneRequest) Reset() {
	*x = CreateSceneRequest{}
	mi := &file_scene_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSceneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSceneRequest) ProtoMessage() {}

func (x *CreateSceneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSceneRequest.ProtoReflect.Descriptor instead.
func (*CreateSceneRequest) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSceneRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *CreateSceneRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSceneRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateSceneRequest) GetWidgetsJson() string {
	if x != nil {
		return x.WidgetsJson
	}
	return ""
}

func (x *CreateSceneRequest) GetLayoutJson() string {
	if x != nil {
		return x.LayoutJson
	}
	return ""
}

func (x *CreateSceneRequest) GetCreatedByType() string {
	if x != nil {
		return x.CreatedByType
	}
	return ""
}

func (x *CreateSceneRequest) GetCreatedByRef() string {
	if x != nil {
		return x.CreatedByRef
	}
	return ""
}

type GetSceneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSceneRequest) Reset() {
	*x = GetSceneRequest{}
	mi := &file_scene_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSceneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSceneRequest) ProtoMessage() {}

func (x *GetSceneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSceneRequest.ProtoReflect.Descriptor instead.
func (*GetSceneRequest) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{2}
}

func (x *GetSceneRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SceneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *ResponseStatus        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Scene         *Scene                 `protobuf:"bytes,2,opt,name=scene,proto3" json:"scene,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SceneResponse) Reset() {
	*x = SceneResponse{}
	mi := &file_scene_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneResponse) ProtoMessage() {}

func (x *SceneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneResponse.ProtoReflect.Descriptor instead.
func (*SceneResponse) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{3}
}

func (x *SceneResponse) GetStatus() *ResponseStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *SceneResponse) GetScene() *Scene {
	if x != nil {
		return x.Scene
	}
	return nil
}

// Patch semantics — every scalar field is "leave unchanged unless
// caller set it." Mirrors `UpdateWorkflowRequest`. Empty string is
// the sentinel for "not provided" today; revisit when migrating to
// `optional` scalars.
type UpdateSceneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	WidgetsJson   string                 `protobuf:"bytes,4,opt,name=widgets_json,json=widgetsJson,proto3" json:"widgets_json,omitempty"`
	LayoutJson    string                 `protobuf:"bytes,5,opt,name=layout_json,json=layoutJson,proto3" json:"layout_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSceneRequest) Reset() {
	*x = UpdateSceneRequest{}
	mi := &file_scene_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSceneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSceneRequest) ProtoMessage() {}

func (x *UpdateSceneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSceneRequest.ProtoReflect.Descriptor instead.
func (*UpdateSceneRequest) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateSceneRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSceneRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSceneRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateSceneRequest) GetWidgetsJson() string {
	if x != nil {
		return x.WidgetsJson
	}
	return ""
}

func (x *UpdateSceneRequest) GetLayoutJson() string {
	if x != nil {
		return x.LayoutJson
	}
	return ""
}

type DeleteSceneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSceneRequest) Reset() {
	*x = DeleteSceneRequest{}
	mi := &file_scene_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSceneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSceneRequest) ProtoMessage() {}

func (x *DeleteSceneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSceneRequest.ProtoReflect.Descriptor instead.
func (*DeleteSceneRequest) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteSceneRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListScenesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SortBy        string                 `protobuf:"bytes,4,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"` // e.g. "name", "created_at", "updated_at"
	SortDesc      bool                   `protobuf:"varint,5,opt,name=sort_desc,json=sortDesc,proto3" json:"sort_desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScenesRequest) Reset() {
	*x = ListScenesRequest{}
	mi := &file_scene_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScenesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScenesRequest) ProtoMessage() {}

func (x *ListScenesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScenesRequest.ProtoReflect.Descriptor instead.
func (*ListScenesRequest) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{6}
}

func (x *ListScenesRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *ListScenesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListScenesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListScenesRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListScenesRequest) GetSortDesc() bool {
	if x != nil {
		return x.SortDesc
	}
	return false
}

type ListScenesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *ResponseStatus        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Scenes        []*Scene               `protobuf:"bytes,2,rep,name=scenes,proto3" json:"scenes,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScenesResponse) Reset() {
	*x = ListScenesResponse{}
	mi := &file_scene_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScenesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScenesResponse) ProtoMessage() {}

func (x *ListScenesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScenesResponse.ProtoReflect.Descriptor instead.
func (*ListScenesResponse) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{7}
}

func (x *ListScenesResponse) GetStatus() *ResponseStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ListScenesResponse) GetScenes() []*Scene {
	if x != nil {
		return x.Scenes
	}
	return nil
}

func (x *ListScenesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListScenesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListScenesResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_scene_proto protoreflect.FileDescriptor

const file_scene_proto_rawDesc = "" +
	"\n" +
	"\vscene.proto\x12\x05scene\x1a\fcommon.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfc\x02\n" +
	"\x05Scene\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eapplication_id\x18\x02 \x01(\tR\rapplicationId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12!\n" +
	"\fwidgets_json\x18\x05 \x01(\tR\vwidgetsJson\x12\x1f\n" +
	"\vlayout_json\x18\x06 \x01(\tR\n" +
	"layoutJson\x12&\n" +
	"\x0fcreated_by_type\x18\a \x01(\tR\rcreatedByType\x12$\n" +
	"\x0ecreated_by_ref\x18\b \x01(\tR\fcreatedByRef\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x83\x02\n" +
	"\x12CreateSceneRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12!\n" +
	"\fwidgets_json\x18\x04 \x01(\tR\vwidgetsJson\x12\x1f\n" +
	"\vlayout_json\x18\x05 \x01(\tR\n" +
	"layoutJson\x12&\n" +
	"\x0fcreated_by_type\x18\x06 \x01(\tR\rcreatedByType\x12$\n" +
	"\x0ecreated_by_ref\x18\a \x01(\tR\fcreatedByRef\"!\n" +
	"\x0fGetSceneRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"c\n" +
	"\rSceneResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\v2\x16.common.ResponseStatusR\x06status\x12\"\n" +
	"\x05scene\x18\x02 \x01(\v2\f.scene.SceneR\x05scene\"\x9e\x01\n" +
	"\x12UpdateSceneRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12!\n" +
	"\fwidgets_json\x18\x04 \x01(\tR\vwidgetsJson\x12\x1f\n" +
	"\vlayout_json\x18\x05 \x01(\tR\n" +
	"layoutJson\"$\n" +
	"\x12DeleteSceneRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa1\x01\n" +
	"\x11ListScenesRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x17\n" +
	"\asort_by\x18\x04 \x01(\tR\x06sortBy\x12\x1b\n" +
	"\tsort_desc\x18\x05 \x01(\bR\bsortDesc\"\xbc\x01\n" +
	"\x12ListScenesResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\v2\x16.common.ResponseStatusR\x06status\x12$\n" +
	"\x06scenes\x18\x02 \x03(\v2\f.scene.SceneR\x06scenes\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize2\xcd\x02\n" +
	"\fSceneService\x12>\n" +
	"\vCreateScene\x12\x19.scene.CreateSceneRequest\x1a\x14.scene.SceneResponse\x128\n" +
	"\bGetScene\x12\x16.scene.GetSceneRequest\x1a\x14.scene.SceneResponse\x12>\n" +
	"\vUpdateScene\x12\x19.scene.UpdateSceneRequest\x1a\x14.scene.SceneResponse\x12@\n" +
	"\vDeleteScene\x12\x19.scene.DeleteSceneRequest\x1a\x16.common.ResponseStatus\x12A\n" +
	"\n" +
	"ListScenes\x12\x18.scene.ListScenesRequest\x1a\x19.scene.ListScenesResponseB)Z'github.com/wolfymaster/woofx3/db/gen/v1b\x06proto3"

var (
	file_scene_proto_rawDescOnce sync.Once
	file_scene_proto_rawDescData []byte
)

func file_scene_proto_rawDescGZIP() []byte {
	file_scene_proto_rawDescOnce.Do(func() {
		file_scene_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scene_proto_rawDesc), len(file_scene_proto_rawDesc)))
	})
	return file_scene_proto_rawDescData
}

var file_scene_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_scene_proto_goTypes = []any{
	(*Scene)(nil),                 // 0: scene.Scene
	(*CreateSceneRequest)(nil),    // 1: scene.CreateSceneRequest
	(*GetSceneRequest)(nil),       // 2: scene.GetSceneRequest
	(*SceneResponse)(nil),         // 3: scene.SceneResponse
	(*UpdateSceneRequest)(nil),    // 4: scene.UpdateSceneRequest
	(*DeleteSceneRequest)(nil),    // 5: scene.DeleteSceneRequest
	(*ListScenesRequest)(nil),     // 6: scene.ListScenesRequest
	(*ListScenesResponse)(nil),    // 7: scene.ListScenesResponse
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
	(*ResponseStatus)(nil),        // 9: common.ResponseStatus
}
var file_scene_proto_depIdxs = []int32{
	8,  // 0: scene.Scene.created_at:type_name -> google.protobuf.Timestamp
	8,  // 1: scene.Scene.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 2: scene.SceneResponse.status:type_name -> common.ResponseStatus
	0,  // 3: scene.SceneResponse.scene:type_name -> scene.Scene
	9,  // 4: scene.ListScenesResponse.status:type_name -> common.ResponseStatus
	0,  // 5: scene.ListScenesResponse.scenes:type_name -> scene.Scene
	1,  // 6: scene.SceneService.CreateScene:input_type -> scene.CreateSceneRequest
	2,  // 7: scene.SceneService.GetScene:input_type -> scene.GetSceneRequest
	4,  // 8: scene.SceneService.UpdateScene:input_type -> scene.UpdateSceneRequest
	5,  // 9: scene.SceneService.DeleteScene:input_type -> scene.DeleteSceneRequest
	6,  // 10: scene.SceneService.ListScenes:input_type -> scene.ListScenesRequest
	3,  // 11: scene.SceneService.CreateScene:output_type -> scene.SceneResponse
	3,  // 12: scene.SceneService.GetScene:output_type -> scene.SceneResponse
	3,  // 13: scene.SceneService.UpdateScene:output_type -> scene.SceneResponse
	9,  // 14: scene.SceneService.DeleteScene:output_type -> common.ResponseStatus
	7,  // 15: scene.SceneService.ListScenes:output_type -> scene.ListScenesResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_scene_proto_init() }
func file_scene_proto_init() {
	if File_scene_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scene_proto_rawDesc), len(file_scene_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scene_proto_goTypes,
		DependencyIndexes: file_scene_proto_depIdxs,
		MessageInfos:      file_scene_proto_msgTypes,
	}.Build()
	File_scene_proto = out.File
	file_scene_proto_goTypes = nil
	file_scene_proto_depIdxs = nil
}
