// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// Source: module_resource.proto
/* eslint-disable */

import type { ByteSource, PartialDeep } from "protoscript";
import * as protoscript from "protoscript";

import * as common from "./common.pb";

//========================================//
//                 Types                  //
//========================================//

export interface ModuleResource {
  id: string;
  moduleId: string;
  resourceType: string;
  resourceId: string;
  manifestId: string;
  resourceName: string;
  originalVersion: string;
  currentVersion: string;
  installedAt: protoscript.Timestamp;
  updatedAt: protoscript.Timestamp;
}

export interface CreateModuleResourceRequest {
  moduleId: string;
  resourceType: string;
  resourceId: string;
  manifestId: string;
  resourceName: string;
  version: string;
}

export interface ListModuleResourcesRequest {
  moduleId: string;
  resourceType: string;
}

export interface ListModuleResourcesResponse {
  status: common.ResponseStatus;
  resources: ModuleResource[];
}

export interface ModuleResourceResponse {
  status: common.ResponseStatus;
  resource: ModuleResource;
}

export interface DeleteModuleResourcesRequest {
  moduleId: string;
}

export interface UpdateModuleResourceVersionRequest {
  id: string;
  version: string;
}

//========================================//
//        Protobuf Encode / Decode        //
//========================================//

export const ModuleResource = {
  /**
   * Serializes ModuleResource to protobuf.
   */
  encode: function (msg: PartialDeep<ModuleResource>): Uint8Array {
    return ModuleResource._writeMessage(
      msg,
      new protoscript.BinaryWriter(),
    ).getResultBuffer();
  },

  /**
   * Deserializes ModuleResource from protobuf.
   */
  decode: function (bytes: ByteSource): ModuleResource {
    return ModuleResource._readMessage(
      ModuleResource.initialize(),
      new protoscript.BinaryReader(bytes),
    );
  },

  /**
   * Initializes ModuleResource with all fields set to their default value.
   */
  initialize: function (msg?: Partial<ModuleResource>): ModuleResource {
    return {
      id: "",
      moduleId: "",
      resourceType: "",
      resourceId: "",
      manifestId: "",
      resourceName: "",
      originalVersion: "",
      currentVersion: "",
      installedAt: protoscript.Timestamp.initialize(),
      updatedAt: protoscript.Timestamp.initialize(),
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<ModuleResource>,
    writer: protoscript.BinaryWriter,
  ): protoscript.BinaryWriter {
    if (msg.id) {
      writer.writeString(1, msg.id);
    }
    if (msg.moduleId) {
      writer.writeString(2, msg.moduleId);
    }
    if (msg.resourceType) {
      writer.writeString(3, msg.resourceType);
    }
    if (msg.resourceId) {
      writer.writeString(4, msg.resourceId);
    }
    if (msg.manifestId) {
      writer.writeString(5, msg.manifestId);
    }
    if (msg.resourceName) {
      writer.writeString(6, msg.resourceName);
    }
    if (msg.originalVersion) {
      writer.writeString(7, msg.originalVersion);
    }
    if (msg.currentVersion) {
      writer.writeString(8, msg.currentVersion);
    }
    if (msg.installedAt) {
      writer.writeMessage(
        9,
        msg.installedAt,
        protoscript.Timestamp._writeMessage,
      );
    }
    if (msg.updatedAt) {
      writer.writeMessage(
        10,
        msg.updatedAt,
        protoscript.Timestamp._writeMessage,
      );
    }
    return writer;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: ModuleResource,
    reader: protoscript.BinaryReader,
  ): ModuleResource {
    while (reader.nextField()) {
      const field = reader.getFieldNumber();
      switch (field) {
        case 1: {
          msg.id = reader.readString();
          break;
        }
        case 2: {
          msg.moduleId = reader.readString();
          break;
        }
        case 3: {
          msg.resourceType = reader.readString();
          break;
        }
        case 4: {
          msg.resourceId = reader.readString();
          break;
        }
        case 5: {
          msg.manifestId = reader.readString();
          break;
        }
        case 6: {
          msg.resourceName = reader.readString();
          break;
        }
        case 7: {
          msg.originalVersion = reader.readString();
          break;
        }
        case 8: {
          msg.currentVersion = reader.readString();
          break;
        }
        case 9: {
          reader.readMessage(
            msg.installedAt,
            protoscript.Timestamp._readMessage,
          );
          break;
        }
        case 10: {
          reader.readMessage(msg.updatedAt, protoscript.Timestamp._readMessage);
          break;
        }
        default: {
          reader.skipField();
          break;
        }
      }
    }
    return msg;
  },
};

export const CreateModuleResourceRequest = {
  /**
   * Serializes CreateModuleResourceRequest to protobuf.
   */
  encode: function (msg: PartialDeep<CreateModuleResourceRequest>): Uint8Array {
    return CreateModuleResourceRequest._writeMessage(
      msg,
      new protoscript.BinaryWriter(),
    ).getResultBuffer();
  },

  /**
   * Deserializes CreateModuleResourceRequest from protobuf.
   */
  decode: function (bytes: ByteSource): CreateModuleResourceRequest {
    return CreateModuleResourceRequest._readMessage(
      CreateModuleResourceRequest.initialize(),
      new protoscript.BinaryReader(bytes),
    );
  },

  /**
   * Initializes CreateModuleResourceRequest with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<CreateModuleResourceRequest>,
  ): CreateModuleResourceRequest {
    return {
      moduleId: "",
      resourceType: "",
      resourceId: "",
      manifestId: "",
      resourceName: "",
      version: "",
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<CreateModuleResourceRequest>,
    writer: protoscript.BinaryWriter,
  ): protoscript.BinaryWriter {
    if (msg.moduleId) {
      writer.writeString(1, msg.moduleId);
    }
    if (msg.resourceType) {
      writer.writeString(2, msg.resourceType);
    }
    if (msg.resourceId) {
      writer.writeString(3, msg.resourceId);
    }
    if (msg.manifestId) {
      writer.writeString(4, msg.manifestId);
    }
    if (msg.resourceName) {
      writer.writeString(5, msg.resourceName);
    }
    if (msg.version) {
      writer.writeString(6, msg.version);
    }
    return writer;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: CreateModuleResourceRequest,
    reader: protoscript.BinaryReader,
  ): CreateModuleResourceRequest {
    while (reader.nextField()) {
      const field = reader.getFieldNumber();
      switch (field) {
        case 1: {
          msg.moduleId = reader.readString();
          break;
        }
        case 2: {
          msg.resourceType = reader.readString();
          break;
        }
        case 3: {
          msg.resourceId = reader.readString();
          break;
        }
        case 4: {
          msg.manifestId = reader.readString();
          break;
        }
        case 5: {
          msg.resourceName = reader.readString();
          break;
        }
        case 6: {
          msg.version = reader.readString();
          break;
        }
        default: {
          reader.skipField();
          break;
        }
      }
    }
    return msg;
  },
};

export const ListModuleResourcesRequest = {
  /**
   * Serializes ListModuleResourcesRequest to protobuf.
   */
  encode: function (msg: PartialDeep<ListModuleResourcesRequest>): Uint8Array {
    return ListModuleResourcesRequest._writeMessage(
      msg,
      new protoscript.BinaryWriter(),
    ).getResultBuffer();
  },

  /**
   * Deserializes ListModuleResourcesRequest from protobuf.
   */
  decode: function (bytes: ByteSource): ListModuleResourcesRequest {
    return ListModuleResourcesRequest._readMessage(
      ListModuleResourcesRequest.initialize(),
      new protoscript.BinaryReader(bytes),
    );
  },

  /**
   * Initializes ListModuleResourcesRequest with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<ListModuleResourcesRequest>,
  ): ListModuleResourcesRequest {
    return {
      moduleId: "",
      resourceType: "",
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<ListModuleResourcesRequest>,
    writer: protoscript.BinaryWriter,
  ): protoscript.BinaryWriter {
    if (msg.moduleId) {
      writer.writeString(1, msg.moduleId);
    }
    if (msg.resourceType) {
      writer.writeString(2, msg.resourceType);
    }
    return writer;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: ListModuleResourcesRequest,
    reader: protoscript.BinaryReader,
  ): ListModuleResourcesRequest {
    while (reader.nextField()) {
      const field = reader.getFieldNumber();
      switch (field) {
        case 1: {
          msg.moduleId = reader.readString();
          break;
        }
        case 2: {
          msg.resourceType = reader.readString();
          break;
        }
        default: {
          reader.skipField();
          break;
        }
      }
    }
    return msg;
  },
};

export const ListModuleResourcesResponse = {
  /**
   * Serializes ListModuleResourcesResponse to protobuf.
   */
  encode: function (msg: PartialDeep<ListModuleResourcesResponse>): Uint8Array {
    return ListModuleResourcesResponse._writeMessage(
      msg,
      new protoscript.BinaryWriter(),
    ).getResultBuffer();
  },

  /**
   * Deserializes ListModuleResourcesResponse from protobuf.
   */
  decode: function (bytes: ByteSource): ListModuleResourcesResponse {
    return ListModuleResourcesResponse._readMessage(
      ListModuleResourcesResponse.initialize(),
      new protoscript.BinaryReader(bytes),
    );
  },

  /**
   * Initializes ListModuleResourcesResponse with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<ListModuleResourcesResponse>,
  ): ListModuleResourcesResponse {
    return {
      status: common.ResponseStatus.initialize(),
      resources: [],
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<ListModuleResourcesResponse>,
    writer: protoscript.BinaryWriter,
  ): protoscript.BinaryWriter {
    if (msg.status) {
      writer.writeMessage(1, msg.status, common.ResponseStatus._writeMessage);
    }
    if (msg.resources?.length) {
      writer.writeRepeatedMessage(
        2,
        msg.resources as any,
        ModuleResource._writeMessage,
      );
    }
    return writer;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: ListModuleResourcesResponse,
    reader: protoscript.BinaryReader,
  ): ListModuleResourcesResponse {
    while (reader.nextField()) {
      const field = reader.getFieldNumber();
      switch (field) {
        case 1: {
          reader.readMessage(msg.status, common.ResponseStatus._readMessage);
          break;
        }
        case 2: {
          const m = ModuleResource.initialize();
          reader.readMessage(m, ModuleResource._readMessage);
          msg.resources.push(m);
          break;
        }
        default: {
          reader.skipField();
          break;
        }
      }
    }
    return msg;
  },
};

export const ModuleResourceResponse = {
  /**
   * Serializes ModuleResourceResponse to protobuf.
   */
  encode: function (msg: PartialDeep<ModuleResourceResponse>): Uint8Array {
    return ModuleResourceResponse._writeMessage(
      msg,
      new protoscript.BinaryWriter(),
    ).getResultBuffer();
  },

  /**
   * Deserializes ModuleResourceResponse from protobuf.
   */
  decode: function (bytes: ByteSource): ModuleResourceResponse {
    return ModuleResourceResponse._readMessage(
      ModuleResourceResponse.initialize(),
      new protoscript.BinaryReader(bytes),
    );
  },

  /**
   * Initializes ModuleResourceResponse with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<ModuleResourceResponse>,
  ): ModuleResourceResponse {
    return {
      status: common.ResponseStatus.initialize(),
      resource: ModuleResource.initialize(),
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<ModuleResourceResponse>,
    writer: protoscript.BinaryWriter,
  ): protoscript.BinaryWriter {
    if (msg.status) {
      writer.writeMessage(1, msg.status, common.ResponseStatus._writeMessage);
    }
    if (msg.resource) {
      writer.writeMessage(2, msg.resource, ModuleResource._writeMessage);
    }
    return writer;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: ModuleResourceResponse,
    reader: protoscript.BinaryReader,
  ): ModuleResourceResponse {
    while (reader.nextField()) {
      const field = reader.getFieldNumber();
      switch (field) {
        case 1: {
          reader.readMessage(msg.status, common.ResponseStatus._readMessage);
          break;
        }
        case 2: {
          reader.readMessage(msg.resource, ModuleResource._readMessage);
          break;
        }
        default: {
          reader.skipField();
          break;
        }
      }
    }
    return msg;
  },
};

export const DeleteModuleResourcesRequest = {
  /**
   * Serializes DeleteModuleResourcesRequest to protobuf.
   */
  encode: function (
    msg: PartialDeep<DeleteModuleResourcesRequest>,
  ): Uint8Array {
    return DeleteModuleResourcesRequest._writeMessage(
      msg,
      new protoscript.BinaryWriter(),
    ).getResultBuffer();
  },

  /**
   * Deserializes DeleteModuleResourcesRequest from protobuf.
   */
  decode: function (bytes: ByteSource): DeleteModuleResourcesRequest {
    return DeleteModuleResourcesRequest._readMessage(
      DeleteModuleResourcesRequest.initialize(),
      new protoscript.BinaryReader(bytes),
    );
  },

  /**
   * Initializes DeleteModuleResourcesRequest with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<DeleteModuleResourcesRequest>,
  ): DeleteModuleResourcesRequest {
    return {
      moduleId: "",
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<DeleteModuleResourcesRequest>,
    writer: protoscript.BinaryWriter,
  ): protoscript.BinaryWriter {
    if (msg.moduleId) {
      writer.writeString(1, msg.moduleId);
    }
    return writer;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: DeleteModuleResourcesRequest,
    reader: protoscript.BinaryReader,
  ): DeleteModuleResourcesRequest {
    while (reader.nextField()) {
      const field = reader.getFieldNumber();
      switch (field) {
        case 1: {
          msg.moduleId = reader.readString();
          break;
        }
        default: {
          reader.skipField();
          break;
        }
      }
    }
    return msg;
  },
};

export const UpdateModuleResourceVersionRequest = {
  /**
   * Serializes UpdateModuleResourceVersionRequest to protobuf.
   */
  encode: function (
    msg: PartialDeep<UpdateModuleResourceVersionRequest>,
  ): Uint8Array {
    return UpdateModuleResourceVersionRequest._writeMessage(
      msg,
      new protoscript.BinaryWriter(),
    ).getResultBuffer();
  },

  /**
   * Deserializes UpdateModuleResourceVersionRequest from protobuf.
   */
  decode: function (bytes: ByteSource): UpdateModuleResourceVersionRequest {
    return UpdateModuleResourceVersionRequest._readMessage(
      UpdateModuleResourceVersionRequest.initialize(),
      new protoscript.BinaryReader(bytes),
    );
  },

  /**
   * Initializes UpdateModuleResourceVersionRequest with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<UpdateModuleResourceVersionRequest>,
  ): UpdateModuleResourceVersionRequest {
    return {
      id: "",
      version: "",
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<UpdateModuleResourceVersionRequest>,
    writer: protoscript.BinaryWriter,
  ): protoscript.BinaryWriter {
    if (msg.id) {
      writer.writeString(1, msg.id);
    }
    if (msg.version) {
      writer.writeString(2, msg.version);
    }
    return writer;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: UpdateModuleResourceVersionRequest,
    reader: protoscript.BinaryReader,
  ): UpdateModuleResourceVersionRequest {
    while (reader.nextField()) {
      const field = reader.getFieldNumber();
      switch (field) {
        case 1: {
          msg.id = reader.readString();
          break;
        }
        case 2: {
          msg.version = reader.readString();
          break;
        }
        default: {
          reader.skipField();
          break;
        }
      }
    }
    return msg;
  },
};

//========================================//
//          JSON Encode / Decode          //
//========================================//

export const ModuleResourceJSON = {
  /**
   * Serializes ModuleResource to JSON.
   */
  encode: function (msg: PartialDeep<ModuleResource>): string {
    return JSON.stringify(ModuleResourceJSON._writeMessage(msg));
  },

  /**
   * Deserializes ModuleResource from JSON.
   */
  decode: function (json: string): ModuleResource {
    return ModuleResourceJSON._readMessage(
      ModuleResourceJSON.initialize(),
      JSON.parse(json),
    );
  },

  /**
   * Initializes ModuleResource with all fields set to their default value.
   */
  initialize: function (msg?: Partial<ModuleResource>): ModuleResource {
    return {
      id: "",
      moduleId: "",
      resourceType: "",
      resourceId: "",
      manifestId: "",
      resourceName: "",
      originalVersion: "",
      currentVersion: "",
      installedAt: protoscript.TimestampJSON.initialize(),
      updatedAt: protoscript.TimestampJSON.initialize(),
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<ModuleResource>,
  ): Record<string, unknown> {
    const json: Record<string, unknown> = {};
    if (msg.id) {
      json["id"] = msg.id;
    }
    if (msg.moduleId) {
      json["moduleId"] = msg.moduleId;
    }
    if (msg.resourceType) {
      json["resourceType"] = msg.resourceType;
    }
    if (msg.resourceId) {
      json["resourceId"] = msg.resourceId;
    }
    if (msg.manifestId) {
      json["manifestId"] = msg.manifestId;
    }
    if (msg.resourceName) {
      json["resourceName"] = msg.resourceName;
    }
    if (msg.originalVersion) {
      json["originalVersion"] = msg.originalVersion;
    }
    if (msg.currentVersion) {
      json["currentVersion"] = msg.currentVersion;
    }
    if (msg.installedAt && (msg.installedAt.seconds || msg.installedAt.nanos)) {
      json["installedAt"] = protoscript.serializeTimestamp(msg.installedAt);
    }
    if (msg.updatedAt && (msg.updatedAt.seconds || msg.updatedAt.nanos)) {
      json["updatedAt"] = protoscript.serializeTimestamp(msg.updatedAt);
    }
    return json;
  },

  /**
   * @private
   */
  _readMessage: function (msg: ModuleResource, json: any): ModuleResource {
    const _id_ = json["id"];
    if (_id_) {
      msg.id = _id_;
    }
    const _moduleId_ = json["moduleId"] ?? json["module_id"];
    if (_moduleId_) {
      msg.moduleId = _moduleId_;
    }
    const _resourceType_ = json["resourceType"] ?? json["resource_type"];
    if (_resourceType_) {
      msg.resourceType = _resourceType_;
    }
    const _resourceId_ = json["resourceId"] ?? json["resource_id"];
    if (_resourceId_) {
      msg.resourceId = _resourceId_;
    }
    const _manifestId_ = json["manifestId"] ?? json["manifest_id"];
    if (_manifestId_) {
      msg.manifestId = _manifestId_;
    }
    const _resourceName_ = json["resourceName"] ?? json["resource_name"];
    if (_resourceName_) {
      msg.resourceName = _resourceName_;
    }
    const _originalVersion_ =
      json["originalVersion"] ?? json["original_version"];
    if (_originalVersion_) {
      msg.originalVersion = _originalVersion_;
    }
    const _currentVersion_ = json["currentVersion"] ?? json["current_version"];
    if (_currentVersion_) {
      msg.currentVersion = _currentVersion_;
    }
    const _installedAt_ = json["installedAt"] ?? json["installed_at"];
    if (_installedAt_) {
      msg.installedAt = protoscript.parseTimestamp(_installedAt_);
    }
    const _updatedAt_ = json["updatedAt"] ?? json["updated_at"];
    if (_updatedAt_) {
      msg.updatedAt = protoscript.parseTimestamp(_updatedAt_);
    }
    return msg;
  },
};

export const CreateModuleResourceRequestJSON = {
  /**
   * Serializes CreateModuleResourceRequest to JSON.
   */
  encode: function (msg: PartialDeep<CreateModuleResourceRequest>): string {
    return JSON.stringify(CreateModuleResourceRequestJSON._writeMessage(msg));
  },

  /**
   * Deserializes CreateModuleResourceRequest from JSON.
   */
  decode: function (json: string): CreateModuleResourceRequest {
    return CreateModuleResourceRequestJSON._readMessage(
      CreateModuleResourceRequestJSON.initialize(),
      JSON.parse(json),
    );
  },

  /**
   * Initializes CreateModuleResourceRequest with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<CreateModuleResourceRequest>,
  ): CreateModuleResourceRequest {
    return {
      moduleId: "",
      resourceType: "",
      resourceId: "",
      manifestId: "",
      resourceName: "",
      version: "",
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<CreateModuleResourceRequest>,
  ): Record<string, unknown> {
    const json: Record<string, unknown> = {};
    if (msg.moduleId) {
      json["moduleId"] = msg.moduleId;
    }
    if (msg.resourceType) {
      json["resourceType"] = msg.resourceType;
    }
    if (msg.resourceId) {
      json["resourceId"] = msg.resourceId;
    }
    if (msg.manifestId) {
      json["manifestId"] = msg.manifestId;
    }
    if (msg.resourceName) {
      json["resourceName"] = msg.resourceName;
    }
    if (msg.version) {
      json["version"] = msg.version;
    }
    return json;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: CreateModuleResourceRequest,
    json: any,
  ): CreateModuleResourceRequest {
    const _moduleId_ = json["moduleId"] ?? json["module_id"];
    if (_moduleId_) {
      msg.moduleId = _moduleId_;
    }
    const _resourceType_ = json["resourceType"] ?? json["resource_type"];
    if (_resourceType_) {
      msg.resourceType = _resourceType_;
    }
    const _resourceId_ = json["resourceId"] ?? json["resource_id"];
    if (_resourceId_) {
      msg.resourceId = _resourceId_;
    }
    const _manifestId_ = json["manifestId"] ?? json["manifest_id"];
    if (_manifestId_) {
      msg.manifestId = _manifestId_;
    }
    const _resourceName_ = json["resourceName"] ?? json["resource_name"];
    if (_resourceName_) {
      msg.resourceName = _resourceName_;
    }
    const _version_ = json["version"];
    if (_version_) {
      msg.version = _version_;
    }
    return msg;
  },
};

export const ListModuleResourcesRequestJSON = {
  /**
   * Serializes ListModuleResourcesRequest to JSON.
   */
  encode: function (msg: PartialDeep<ListModuleResourcesRequest>): string {
    return JSON.stringify(ListModuleResourcesRequestJSON._writeMessage(msg));
  },

  /**
   * Deserializes ListModuleResourcesRequest from JSON.
   */
  decode: function (json: string): ListModuleResourcesRequest {
    return ListModuleResourcesRequestJSON._readMessage(
      ListModuleResourcesRequestJSON.initialize(),
      JSON.parse(json),
    );
  },

  /**
   * Initializes ListModuleResourcesRequest with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<ListModuleResourcesRequest>,
  ): ListModuleResourcesRequest {
    return {
      moduleId: "",
      resourceType: "",
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<ListModuleResourcesRequest>,
  ): Record<string, unknown> {
    const json: Record<string, unknown> = {};
    if (msg.moduleId) {
      json["moduleId"] = msg.moduleId;
    }
    if (msg.resourceType) {
      json["resourceType"] = msg.resourceType;
    }
    return json;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: ListModuleResourcesRequest,
    json: any,
  ): ListModuleResourcesRequest {
    const _moduleId_ = json["moduleId"] ?? json["module_id"];
    if (_moduleId_) {
      msg.moduleId = _moduleId_;
    }
    const _resourceType_ = json["resourceType"] ?? json["resource_type"];
    if (_resourceType_) {
      msg.resourceType = _resourceType_;
    }
    return msg;
  },
};

export const ListModuleResourcesResponseJSON = {
  /**
   * Serializes ListModuleResourcesResponse to JSON.
   */
  encode: function (msg: PartialDeep<ListModuleResourcesResponse>): string {
    return JSON.stringify(ListModuleResourcesResponseJSON._writeMessage(msg));
  },

  /**
   * Deserializes ListModuleResourcesResponse from JSON.
   */
  decode: function (json: string): ListModuleResourcesResponse {
    return ListModuleResourcesResponseJSON._readMessage(
      ListModuleResourcesResponseJSON.initialize(),
      JSON.parse(json),
    );
  },

  /**
   * Initializes ListModuleResourcesResponse with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<ListModuleResourcesResponse>,
  ): ListModuleResourcesResponse {
    return {
      status: common.ResponseStatusJSON.initialize(),
      resources: [],
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<ListModuleResourcesResponse>,
  ): Record<string, unknown> {
    const json: Record<string, unknown> = {};
    if (msg.status) {
      const _status_ = common.ResponseStatusJSON._writeMessage(msg.status);
      if (Object.keys(_status_).length > 0) {
        json["status"] = _status_;
      }
    }
    if (msg.resources?.length) {
      json["resources"] = msg.resources.map(ModuleResourceJSON._writeMessage);
    }
    return json;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: ListModuleResourcesResponse,
    json: any,
  ): ListModuleResourcesResponse {
    const _status_ = json["status"];
    if (_status_) {
      common.ResponseStatusJSON._readMessage(msg.status, _status_);
    }
    const _resources_ = json["resources"];
    if (_resources_) {
      for (const item of _resources_) {
        const m = ModuleResourceJSON.initialize();
        ModuleResourceJSON._readMessage(m, item);
        msg.resources.push(m);
      }
    }
    return msg;
  },
};

export const ModuleResourceResponseJSON = {
  /**
   * Serializes ModuleResourceResponse to JSON.
   */
  encode: function (msg: PartialDeep<ModuleResourceResponse>): string {
    return JSON.stringify(ModuleResourceResponseJSON._writeMessage(msg));
  },

  /**
   * Deserializes ModuleResourceResponse from JSON.
   */
  decode: function (json: string): ModuleResourceResponse {
    return ModuleResourceResponseJSON._readMessage(
      ModuleResourceResponseJSON.initialize(),
      JSON.parse(json),
    );
  },

  /**
   * Initializes ModuleResourceResponse with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<ModuleResourceResponse>,
  ): ModuleResourceResponse {
    return {
      status: common.ResponseStatusJSON.initialize(),
      resource: ModuleResourceJSON.initialize(),
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<ModuleResourceResponse>,
  ): Record<string, unknown> {
    const json: Record<string, unknown> = {};
    if (msg.status) {
      const _status_ = common.ResponseStatusJSON._writeMessage(msg.status);
      if (Object.keys(_status_).length > 0) {
        json["status"] = _status_;
      }
    }
    if (msg.resource) {
      const _resource_ = ModuleResourceJSON._writeMessage(msg.resource);
      if (Object.keys(_resource_).length > 0) {
        json["resource"] = _resource_;
      }
    }
    return json;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: ModuleResourceResponse,
    json: any,
  ): ModuleResourceResponse {
    const _status_ = json["status"];
    if (_status_) {
      common.ResponseStatusJSON._readMessage(msg.status, _status_);
    }
    const _resource_ = json["resource"];
    if (_resource_) {
      ModuleResourceJSON._readMessage(msg.resource, _resource_);
    }
    return msg;
  },
};

export const DeleteModuleResourcesRequestJSON = {
  /**
   * Serializes DeleteModuleResourcesRequest to JSON.
   */
  encode: function (msg: PartialDeep<DeleteModuleResourcesRequest>): string {
    return JSON.stringify(DeleteModuleResourcesRequestJSON._writeMessage(msg));
  },

  /**
   * Deserializes DeleteModuleResourcesRequest from JSON.
   */
  decode: function (json: string): DeleteModuleResourcesRequest {
    return DeleteModuleResourcesRequestJSON._readMessage(
      DeleteModuleResourcesRequestJSON.initialize(),
      JSON.parse(json),
    );
  },

  /**
   * Initializes DeleteModuleResourcesRequest with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<DeleteModuleResourcesRequest>,
  ): DeleteModuleResourcesRequest {
    return {
      moduleId: "",
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<DeleteModuleResourcesRequest>,
  ): Record<string, unknown> {
    const json: Record<string, unknown> = {};
    if (msg.moduleId) {
      json["moduleId"] = msg.moduleId;
    }
    return json;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: DeleteModuleResourcesRequest,
    json: any,
  ): DeleteModuleResourcesRequest {
    const _moduleId_ = json["moduleId"] ?? json["module_id"];
    if (_moduleId_) {
      msg.moduleId = _moduleId_;
    }
    return msg;
  },
};

export const UpdateModuleResourceVersionRequestJSON = {
  /**
   * Serializes UpdateModuleResourceVersionRequest to JSON.
   */
  encode: function (
    msg: PartialDeep<UpdateModuleResourceVersionRequest>,
  ): string {
    return JSON.stringify(
      UpdateModuleResourceVersionRequestJSON._writeMessage(msg),
    );
  },

  /**
   * Deserializes UpdateModuleResourceVersionRequest from JSON.
   */
  decode: function (json: string): UpdateModuleResourceVersionRequest {
    return UpdateModuleResourceVersionRequestJSON._readMessage(
      UpdateModuleResourceVersionRequestJSON.initialize(),
      JSON.parse(json),
    );
  },

  /**
   * Initializes UpdateModuleResourceVersionRequest with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<UpdateModuleResourceVersionRequest>,
  ): UpdateModuleResourceVersionRequest {
    return {
      id: "",
      version: "",
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<UpdateModuleResourceVersionRequest>,
  ): Record<string, unknown> {
    const json: Record<string, unknown> = {};
    if (msg.id) {
      json["id"] = msg.id;
    }
    if (msg.version) {
      json["version"] = msg.version;
    }
    return json;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: UpdateModuleResourceVersionRequest,
    json: any,
  ): UpdateModuleResourceVersionRequest {
    const _id_ = json["id"];
    if (_id_) {
      msg.id = _id_;
    }
    const _version_ = json["version"];
    if (_version_) {
      msg.version = _version_;
    }
    return msg;
  },
};
