// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// Source: stream_gauge.proto
/* eslint-disable */

import type { ByteSource, PartialDeep } from "protoscript";
import * as protoscript from "protoscript";
import { JSONrequest, PBrequest } from "twirpscript";
// This is the minimum version supported by the current runtime.
// If this line fails typechecking, breaking changes have been introduced and this
// file needs to be regenerated by running `npx twirpscript`.
export { MIN_SUPPORTED_VERSION_0_0_56 } from "twirpscript";
import type { ClientConfiguration } from "twirpscript";
import * as common from "./common.pb";

//========================================//
//                 Types                  //
//========================================//

export interface StreamGaugeSample {
  id: string;
  /**
   * The segment that was open when the sample was taken. Stable across
   * splits; resolve a session's samples through it.
   */
  segmentId: string;
  /**
   * The session that owned `segment_id` when the sample was recorded. Not a
   * stable key: a later split can move the segment to another session.
   */
  sessionId: string;
  /**
   * The minute the sample stands for, truncated to the minute in UTC.
   */
  sampledAt: protoscript.Timestamp;
  /**
   * Each metric is absent when its Helix read failed for this minute, so a
   * failure reads as "unknown" rather than as zero. At least one is present.
   */
  viewerCount?: bigint | null | undefined;
  followerTotal?: bigint | null | undefined;
  subscriberTotal?: bigint | null | undefined;
  subscriberPoints?: bigint | null | undefined;
  createdAt: protoscript.Timestamp;
}

export interface RecordStreamGaugeSampleRequest {
  /**
   * When the values were read. Required; stored truncated to the minute.
   */
  sampledAt: protoscript.Timestamp;
  /**
   * Omit a metric whose read failed. At least one must be present: a sample
   * with none carries nothing a missing row does not already say.
   */
  viewerCount?: bigint | null | undefined;
  followerTotal?: bigint | null | undefined;
  subscriberTotal?: bigint | null | undefined;
  subscriberPoints?: bigint | null | undefined;
}

export interface RecordStreamGaugeSampleResponse {
  status: common.ResponseStatus;
  sample: StreamGaugeSample;
  /**
   * False when the minute was already sampled; `sample` is then the row that
   * was stored the first time.
   */
  created: boolean;
}

export interface ListStreamGaugeSamplesRequest {
  streamSessionId: string;
}

export interface ListStreamGaugeSamplesResponse {
  status: common.ResponseStatus;
  /**
   * Oldest first. Gaps between consecutive `sampled_at` values are minutes
   * that were not sampled.
   */
  samples: StreamGaugeSample[];
}

//========================================//
//   StreamGaugeService Protobuf Client   //
//========================================//

/**
 * Records the sample for one minute of the open segment. The segment and
 * session are resolved here, not supplied by the caller, so a sample cannot
 * land on a segment that has already closed.
 *
 * Fails with `failed_precondition` when no segment is open, or when
 * `sampled_at` is before the open segment started. Idempotent per minute: a
 * second sample for a minute already recorded leaves the stored row
 * untouched and returns it with `created` false.
 */
export async function RecordStreamGaugeSample(
  recordStreamGaugeSampleRequest: RecordStreamGaugeSampleRequest,
  config?: ClientConfiguration,
): Promise<RecordStreamGaugeSampleResponse> {
  const response = await PBrequest(
    "/stream_gauge.StreamGaugeService/RecordStreamGaugeSample",
    RecordStreamGaugeSampleRequest.encode(recordStreamGaugeSampleRequest),
    config,
  );
  return RecordStreamGaugeSampleResponse.decode(response);
}

/**
 * Every sample of a session, oldest first, resolved through the segments the
 * session owns now rather than the session each sample was stamped with, so
 * a split or merge after the fact is reflected.
 */
export async function ListStreamGaugeSamples(
  listStreamGaugeSamplesRequest: ListStreamGaugeSamplesRequest,
  config?: ClientConfiguration,
): Promise<ListStreamGaugeSamplesResponse> {
  const response = await PBrequest(
    "/stream_gauge.StreamGaugeService/ListStreamGaugeSamples",
    ListStreamGaugeSamplesRequest.encode(listStreamGaugeSamplesRequest),
    config,
  );
  return ListStreamGaugeSamplesResponse.decode(response);
}

//========================================//
//     StreamGaugeService JSON Client     //
//========================================//

/**
 * Records the sample for one minute of the open segment. The segment and
 * session are resolved here, not supplied by the caller, so a sample cannot
 * land on a segment that has already closed.
 *
 * Fails with `failed_precondition` when no segment is open, or when
 * `sampled_at` is before the open segment started. Idempotent per minute: a
 * second sample for a minute already recorded leaves the stored row
 * untouched and returns it with `created` false.
 */
export async function RecordStreamGaugeSampleJSON(
  recordStreamGaugeSampleRequest: RecordStreamGaugeSampleRequest,
  config?: ClientConfiguration,
): Promise<RecordStreamGaugeSampleResponse> {
  const response = await JSONrequest(
    "/stream_gauge.StreamGaugeService/RecordStreamGaugeSample",
    RecordStreamGaugeSampleRequestJSON.encode(recordStreamGaugeSampleRequest),
    config,
  );
  return RecordStreamGaugeSampleResponseJSON.decode(response);
}

/**
 * Every sample of a session, oldest first, resolved through the segments the
 * session owns now rather than the session each sample was stamped with, so
 * a split or merge after the fact is reflected.
 */
export async function ListStreamGaugeSamplesJSON(
  listStreamGaugeSamplesRequest: ListStreamGaugeSamplesRequest,
  config?: ClientConfiguration,
): Promise<ListStreamGaugeSamplesResponse> {
  const response = await JSONrequest(
    "/stream_gauge.StreamGaugeService/ListStreamGaugeSamples",
    ListStreamGaugeSamplesRequestJSON.encode(listStreamGaugeSamplesRequest),
    config,
  );
  return ListStreamGaugeSamplesResponseJSON.decode(response);
}

//========================================//
//           StreamGaugeService           //
//========================================//

/**
 * Per-minute samples of the levels a broadcast has -- viewer count, follower
 * total, subscriber total and sub points -- that no event log can produce.
 * Twitch emits no unfollow, and `stream.online` carries no viewer count, so
 * these are read from Helix while the stream is live and stored here.
 *
 * A sample belongs to the segment that was open when it was recorded, and is
 * only ever recorded while one is. A minute with no row was not sampled; it
 * does not mean zero. See docs/services/analytics.md.
 */
export interface StreamGaugeService<Context = unknown> {
  /**
   * Records the sample for one minute of the open segment. The segment and
   * session are resolved here, not supplied by the caller, so a sample cannot
   * land on a segment that has already closed.
   *
   * Fails with `failed_precondition` when no segment is open, or when
   * `sampled_at` is before the open segment started. Idempotent per minute: a
   * second sample for a minute already recorded leaves the stored row
   * untouched and returns it with `created` false.
   */
  RecordStreamGaugeSample: (
    recordStreamGaugeSampleRequest: RecordStreamGaugeSampleRequest,
    context: Context,
  ) =>
    Promise<RecordStreamGaugeSampleResponse> | RecordStreamGaugeSampleResponse;
  /**
   * Every sample of a session, oldest first, resolved through the segments the
   * session owns now rather than the session each sample was stamped with, so
   * a split or merge after the fact is reflected.
   */
  ListStreamGaugeSamples: (
    listStreamGaugeSamplesRequest: ListStreamGaugeSamplesRequest,
    context: Context,
  ) => Promise<ListStreamGaugeSamplesResponse> | ListStreamGaugeSamplesResponse;
}

export function createStreamGaugeService<Context>(
  service: StreamGaugeService<Context>,
) {
  return {
    name: "stream_gauge.StreamGaugeService",
    methods: {
      RecordStreamGaugeSample: {
        name: "RecordStreamGaugeSample",
        handler: service.RecordStreamGaugeSample,
        input: {
          protobuf: RecordStreamGaugeSampleRequest,
          json: RecordStreamGaugeSampleRequestJSON,
        },
        output: {
          protobuf: RecordStreamGaugeSampleResponse,
          json: RecordStreamGaugeSampleResponseJSON,
        },
      },
      ListStreamGaugeSamples: {
        name: "ListStreamGaugeSamples",
        handler: service.ListStreamGaugeSamples,
        input: {
          protobuf: ListStreamGaugeSamplesRequest,
          json: ListStreamGaugeSamplesRequestJSON,
        },
        output: {
          protobuf: ListStreamGaugeSamplesResponse,
          json: ListStreamGaugeSamplesResponseJSON,
        },
      },
    },
  } as const;
}

//========================================//
//        Protobuf Encode / Decode        //
//========================================//

export const StreamGaugeSample = {
  /**
   * Serializes StreamGaugeSample to protobuf.
   */
  encode: function (msg: PartialDeep<StreamGaugeSample>): Uint8Array {
    return StreamGaugeSample._writeMessage(
      msg,
      new protoscript.BinaryWriter(),
    ).getResultBuffer();
  },

  /**
   * Deserializes StreamGaugeSample from protobuf.
   */
  decode: function (bytes: ByteSource): StreamGaugeSample {
    return StreamGaugeSample._readMessage(
      StreamGaugeSample.initialize(),
      new protoscript.BinaryReader(bytes),
    );
  },

  /**
   * Initializes StreamGaugeSample with all fields set to their default value.
   */
  initialize: function (msg?: Partial<StreamGaugeSample>): StreamGaugeSample {
    return {
      id: "",
      segmentId: "",
      sessionId: "",
      sampledAt: protoscript.Timestamp.initialize(),
      viewerCount: undefined,
      followerTotal: undefined,
      subscriberTotal: undefined,
      subscriberPoints: undefined,
      createdAt: protoscript.Timestamp.initialize(),
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<StreamGaugeSample>,
    writer: protoscript.BinaryWriter,
  ): protoscript.BinaryWriter {
    if (msg.id) {
      writer.writeString(1, msg.id);
    }
    if (msg.segmentId) {
      writer.writeString(2, msg.segmentId);
    }
    if (msg.sessionId) {
      writer.writeString(3, msg.sessionId);
    }
    if (msg.sampledAt) {
      writer.writeMessage(
        4,
        msg.sampledAt,
        protoscript.Timestamp._writeMessage,
      );
    }
    if (msg.viewerCount != undefined) {
      writer.writeInt64String(5, msg.viewerCount.toString() as any);
    }
    if (msg.followerTotal != undefined) {
      writer.writeInt64String(6, msg.followerTotal.toString() as any);
    }
    if (msg.subscriberTotal != undefined) {
      writer.writeInt64String(7, msg.subscriberTotal.toString() as any);
    }
    if (msg.subscriberPoints != undefined) {
      writer.writeInt64String(8, msg.subscriberPoints.toString() as any);
    }
    if (msg.createdAt) {
      writer.writeMessage(
        9,
        msg.createdAt,
        protoscript.Timestamp._writeMessage,
      );
    }
    return writer;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: StreamGaugeSample,
    reader: protoscript.BinaryReader,
  ): StreamGaugeSample {
    while (reader.nextField()) {
      const field = reader.getFieldNumber();
      switch (field) {
        case 1: {
          msg.id = reader.readString();
          break;
        }
        case 2: {
          msg.segmentId = reader.readString();
          break;
        }
        case 3: {
          msg.sessionId = reader.readString();
          break;
        }
        case 4: {
          reader.readMessage(msg.sampledAt, protoscript.Timestamp._readMessage);
          break;
        }
        case 5: {
          msg.viewerCount = BigInt(reader.readInt64String());
          break;
        }
        case 6: {
          msg.followerTotal = BigInt(reader.readInt64String());
          break;
        }
        case 7: {
          msg.subscriberTotal = BigInt(reader.readInt64String());
          break;
        }
        case 8: {
          msg.subscriberPoints = BigInt(reader.readInt64String());
          break;
        }
        case 9: {
          reader.readMessage(msg.createdAt, protoscript.Timestamp._readMessage);
          break;
        }
        default: {
          reader.skipField();
          break;
        }
      }
    }
    return msg;
  },
};

export const RecordStreamGaugeSampleRequest = {
  /**
   * Serializes RecordStreamGaugeSampleRequest to protobuf.
   */
  encode: function (
    msg: PartialDeep<RecordStreamGaugeSampleRequest>,
  ): Uint8Array {
    return RecordStreamGaugeSampleRequest._writeMessage(
      msg,
      new protoscript.BinaryWriter(),
    ).getResultBuffer();
  },

  /**
   * Deserializes RecordStreamGaugeSampleRequest from protobuf.
   */
  decode: function (bytes: ByteSource): RecordStreamGaugeSampleRequest {
    return RecordStreamGaugeSampleRequest._readMessage(
      RecordStreamGaugeSampleRequest.initialize(),
      new protoscript.BinaryReader(bytes),
    );
  },

  /**
   * Initializes RecordStreamGaugeSampleRequest with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<RecordStreamGaugeSampleRequest>,
  ): RecordStreamGaugeSampleRequest {
    return {
      sampledAt: protoscript.Timestamp.initialize(),
      viewerCount: undefined,
      followerTotal: undefined,
      subscriberTotal: undefined,
      subscriberPoints: undefined,
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<RecordStreamGaugeSampleRequest>,
    writer: protoscript.BinaryWriter,
  ): protoscript.BinaryWriter {
    if (msg.sampledAt) {
      writer.writeMessage(
        1,
        msg.sampledAt,
        protoscript.Timestamp._writeMessage,
      );
    }
    if (msg.viewerCount != undefined) {
      writer.writeInt64String(2, msg.viewerCount.toString() as any);
    }
    if (msg.followerTotal != undefined) {
      writer.writeInt64String(3, msg.followerTotal.toString() as any);
    }
    if (msg.subscriberTotal != undefined) {
      writer.writeInt64String(4, msg.subscriberTotal.toString() as any);
    }
    if (msg.subscriberPoints != undefined) {
      writer.writeInt64String(5, msg.subscriberPoints.toString() as any);
    }
    return writer;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: RecordStreamGaugeSampleRequest,
    reader: protoscript.BinaryReader,
  ): RecordStreamGaugeSampleRequest {
    while (reader.nextField()) {
      const field = reader.getFieldNumber();
      switch (field) {
        case 1: {
          reader.readMessage(msg.sampledAt, protoscript.Timestamp._readMessage);
          break;
        }
        case 2: {
          msg.viewerCount = BigInt(reader.readInt64String());
          break;
        }
        case 3: {
          msg.followerTotal = BigInt(reader.readInt64String());
          break;
        }
        case 4: {
          msg.subscriberTotal = BigInt(reader.readInt64String());
          break;
        }
        case 5: {
          msg.subscriberPoints = BigInt(reader.readInt64String());
          break;
        }
        default: {
          reader.skipField();
          break;
        }
      }
    }
    return msg;
  },
};

export const RecordStreamGaugeSampleResponse = {
  /**
   * Serializes RecordStreamGaugeSampleResponse to protobuf.
   */
  encode: function (
    msg: PartialDeep<RecordStreamGaugeSampleResponse>,
  ): Uint8Array {
    return RecordStreamGaugeSampleResponse._writeMessage(
      msg,
      new protoscript.BinaryWriter(),
    ).getResultBuffer();
  },

  /**
   * Deserializes RecordStreamGaugeSampleResponse from protobuf.
   */
  decode: function (bytes: ByteSource): RecordStreamGaugeSampleResponse {
    return RecordStreamGaugeSampleResponse._readMessage(
      RecordStreamGaugeSampleResponse.initialize(),
      new protoscript.BinaryReader(bytes),
    );
  },

  /**
   * Initializes RecordStreamGaugeSampleResponse with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<RecordStreamGaugeSampleResponse>,
  ): RecordStreamGaugeSampleResponse {
    return {
      status: common.ResponseStatus.initialize(),
      sample: StreamGaugeSample.initialize(),
      created: false,
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<RecordStreamGaugeSampleResponse>,
    writer: protoscript.BinaryWriter,
  ): protoscript.BinaryWriter {
    if (msg.status) {
      writer.writeMessage(1, msg.status, common.ResponseStatus._writeMessage);
    }
    if (msg.sample) {
      writer.writeMessage(2, msg.sample, StreamGaugeSample._writeMessage);
    }
    if (msg.created) {
      writer.writeBool(3, msg.created);
    }
    return writer;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: RecordStreamGaugeSampleResponse,
    reader: protoscript.BinaryReader,
  ): RecordStreamGaugeSampleResponse {
    while (reader.nextField()) {
      const field = reader.getFieldNumber();
      switch (field) {
        case 1: {
          reader.readMessage(msg.status, common.ResponseStatus._readMessage);
          break;
        }
        case 2: {
          reader.readMessage(msg.sample, StreamGaugeSample._readMessage);
          break;
        }
        case 3: {
          msg.created = reader.readBool();
          break;
        }
        default: {
          reader.skipField();
          break;
        }
      }
    }
    return msg;
  },
};

export const ListStreamGaugeSamplesRequest = {
  /**
   * Serializes ListStreamGaugeSamplesRequest to protobuf.
   */
  encode: function (
    msg: PartialDeep<ListStreamGaugeSamplesRequest>,
  ): Uint8Array {
    return ListStreamGaugeSamplesRequest._writeMessage(
      msg,
      new protoscript.BinaryWriter(),
    ).getResultBuffer();
  },

  /**
   * Deserializes ListStreamGaugeSamplesRequest from protobuf.
   */
  decode: function (bytes: ByteSource): ListStreamGaugeSamplesRequest {
    return ListStreamGaugeSamplesRequest._readMessage(
      ListStreamGaugeSamplesRequest.initialize(),
      new protoscript.BinaryReader(bytes),
    );
  },

  /**
   * Initializes ListStreamGaugeSamplesRequest with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<ListStreamGaugeSamplesRequest>,
  ): ListStreamGaugeSamplesRequest {
    return {
      streamSessionId: "",
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<ListStreamGaugeSamplesRequest>,
    writer: protoscript.BinaryWriter,
  ): protoscript.BinaryWriter {
    if (msg.streamSessionId) {
      writer.writeString(1, msg.streamSessionId);
    }
    return writer;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: ListStreamGaugeSamplesRequest,
    reader: protoscript.BinaryReader,
  ): ListStreamGaugeSamplesRequest {
    while (reader.nextField()) {
      const field = reader.getFieldNumber();
      switch (field) {
        case 1: {
          msg.streamSessionId = reader.readString();
          break;
        }
        default: {
          reader.skipField();
          break;
        }
      }
    }
    return msg;
  },
};

export const ListStreamGaugeSamplesResponse = {
  /**
   * Serializes ListStreamGaugeSamplesResponse to protobuf.
   */
  encode: function (
    msg: PartialDeep<ListStreamGaugeSamplesResponse>,
  ): Uint8Array {
    return ListStreamGaugeSamplesResponse._writeMessage(
      msg,
      new protoscript.BinaryWriter(),
    ).getResultBuffer();
  },

  /**
   * Deserializes ListStreamGaugeSamplesResponse from protobuf.
   */
  decode: function (bytes: ByteSource): ListStreamGaugeSamplesResponse {
    return ListStreamGaugeSamplesResponse._readMessage(
      ListStreamGaugeSamplesResponse.initialize(),
      new protoscript.BinaryReader(bytes),
    );
  },

  /**
   * Initializes ListStreamGaugeSamplesResponse with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<ListStreamGaugeSamplesResponse>,
  ): ListStreamGaugeSamplesResponse {
    return {
      status: common.ResponseStatus.initialize(),
      samples: [],
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<ListStreamGaugeSamplesResponse>,
    writer: protoscript.BinaryWriter,
  ): protoscript.BinaryWriter {
    if (msg.status) {
      writer.writeMessage(1, msg.status, common.ResponseStatus._writeMessage);
    }
    if (msg.samples?.length) {
      writer.writeRepeatedMessage(
        2,
        msg.samples as any,
        StreamGaugeSample._writeMessage,
      );
    }
    return writer;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: ListStreamGaugeSamplesResponse,
    reader: protoscript.BinaryReader,
  ): ListStreamGaugeSamplesResponse {
    while (reader.nextField()) {
      const field = reader.getFieldNumber();
      switch (field) {
        case 1: {
          reader.readMessage(msg.status, common.ResponseStatus._readMessage);
          break;
        }
        case 2: {
          const m = StreamGaugeSample.initialize();
          reader.readMessage(m, StreamGaugeSample._readMessage);
          msg.samples.push(m);
          break;
        }
        default: {
          reader.skipField();
          break;
        }
      }
    }
    return msg;
  },
};

//========================================//
//          JSON Encode / Decode          //
//========================================//

export const StreamGaugeSampleJSON = {
  /**
   * Serializes StreamGaugeSample to JSON.
   */
  encode: function (msg: PartialDeep<StreamGaugeSample>): string {
    return JSON.stringify(StreamGaugeSampleJSON._writeMessage(msg));
  },

  /**
   * Deserializes StreamGaugeSample from JSON.
   */
  decode: function (json: string): StreamGaugeSample {
    return StreamGaugeSampleJSON._readMessage(
      StreamGaugeSampleJSON.initialize(),
      JSON.parse(json),
    );
  },

  /**
   * Initializes StreamGaugeSample with all fields set to their default value.
   */
  initialize: function (msg?: Partial<StreamGaugeSample>): StreamGaugeSample {
    return {
      id: "",
      segmentId: "",
      sessionId: "",
      sampledAt: protoscript.TimestampJSON.initialize(),
      viewerCount: undefined,
      followerTotal: undefined,
      subscriberTotal: undefined,
      subscriberPoints: undefined,
      createdAt: protoscript.TimestampJSON.initialize(),
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<StreamGaugeSample>,
  ): Record<string, unknown> {
    const json: Record<string, unknown> = {};
    if (msg.id) {
      json["id"] = msg.id;
    }
    if (msg.segmentId) {
      json["segmentId"] = msg.segmentId;
    }
    if (msg.sessionId) {
      json["sessionId"] = msg.sessionId;
    }
    if (msg.sampledAt && (msg.sampledAt.seconds || msg.sampledAt.nanos)) {
      json["sampledAt"] = protoscript.serializeTimestamp(msg.sampledAt);
    }
    if (msg.viewerCount != undefined) {
      json["viewerCount"] = String(msg.viewerCount);
    }
    if (msg.followerTotal != undefined) {
      json["followerTotal"] = String(msg.followerTotal);
    }
    if (msg.subscriberTotal != undefined) {
      json["subscriberTotal"] = String(msg.subscriberTotal);
    }
    if (msg.subscriberPoints != undefined) {
      json["subscriberPoints"] = String(msg.subscriberPoints);
    }
    if (msg.createdAt && (msg.createdAt.seconds || msg.createdAt.nanos)) {
      json["createdAt"] = protoscript.serializeTimestamp(msg.createdAt);
    }
    return json;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: StreamGaugeSample,
    json: any,
  ): StreamGaugeSample {
    const _id_ = json["id"];
    if (_id_) {
      msg.id = _id_;
    }
    const _segmentId_ = json["segmentId"] ?? json["segment_id"];
    if (_segmentId_) {
      msg.segmentId = _segmentId_;
    }
    const _sessionId_ = json["sessionId"] ?? json["session_id"];
    if (_sessionId_) {
      msg.sessionId = _sessionId_;
    }
    const _sampledAt_ = json["sampledAt"] ?? json["sampled_at"];
    if (_sampledAt_) {
      msg.sampledAt = protoscript.parseTimestamp(_sampledAt_);
    }
    const _viewerCount_ = json["viewerCount"] ?? json["viewer_count"];
    if (_viewerCount_) {
      msg.viewerCount = BigInt(_viewerCount_);
    }
    const _followerTotal_ = json["followerTotal"] ?? json["follower_total"];
    if (_followerTotal_) {
      msg.followerTotal = BigInt(_followerTotal_);
    }
    const _subscriberTotal_ =
      json["subscriberTotal"] ?? json["subscriber_total"];
    if (_subscriberTotal_) {
      msg.subscriberTotal = BigInt(_subscriberTotal_);
    }
    const _subscriberPoints_ =
      json["subscriberPoints"] ?? json["subscriber_points"];
    if (_subscriberPoints_) {
      msg.subscriberPoints = BigInt(_subscriberPoints_);
    }
    const _createdAt_ = json["createdAt"] ?? json["created_at"];
    if (_createdAt_) {
      msg.createdAt = protoscript.parseTimestamp(_createdAt_);
    }
    return msg;
  },
};

export const RecordStreamGaugeSampleRequestJSON = {
  /**
   * Serializes RecordStreamGaugeSampleRequest to JSON.
   */
  encode: function (msg: PartialDeep<RecordStreamGaugeSampleRequest>): string {
    return JSON.stringify(
      RecordStreamGaugeSampleRequestJSON._writeMessage(msg),
    );
  },

  /**
   * Deserializes RecordStreamGaugeSampleRequest from JSON.
   */
  decode: function (json: string): RecordStreamGaugeSampleRequest {
    return RecordStreamGaugeSampleRequestJSON._readMessage(
      RecordStreamGaugeSampleRequestJSON.initialize(),
      JSON.parse(json),
    );
  },

  /**
   * Initializes RecordStreamGaugeSampleRequest with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<RecordStreamGaugeSampleRequest>,
  ): RecordStreamGaugeSampleRequest {
    return {
      sampledAt: protoscript.TimestampJSON.initialize(),
      viewerCount: undefined,
      followerTotal: undefined,
      subscriberTotal: undefined,
      subscriberPoints: undefined,
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<RecordStreamGaugeSampleRequest>,
  ): Record<string, unknown> {
    const json: Record<string, unknown> = {};
    if (msg.sampledAt && (msg.sampledAt.seconds || msg.sampledAt.nanos)) {
      json["sampledAt"] = protoscript.serializeTimestamp(msg.sampledAt);
    }
    if (msg.viewerCount != undefined) {
      json["viewerCount"] = String(msg.viewerCount);
    }
    if (msg.followerTotal != undefined) {
      json["followerTotal"] = String(msg.followerTotal);
    }
    if (msg.subscriberTotal != undefined) {
      json["subscriberTotal"] = String(msg.subscriberTotal);
    }
    if (msg.subscriberPoints != undefined) {
      json["subscriberPoints"] = String(msg.subscriberPoints);
    }
    return json;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: RecordStreamGaugeSampleRequest,
    json: any,
  ): RecordStreamGaugeSampleRequest {
    const _sampledAt_ = json["sampledAt"] ?? json["sampled_at"];
    if (_sampledAt_) {
      msg.sampledAt = protoscript.parseTimestamp(_sampledAt_);
    }
    const _viewerCount_ = json["viewerCount"] ?? json["viewer_count"];
    if (_viewerCount_) {
      msg.viewerCount = BigInt(_viewerCount_);
    }
    const _followerTotal_ = json["followerTotal"] ?? json["follower_total"];
    if (_followerTotal_) {
      msg.followerTotal = BigInt(_followerTotal_);
    }
    const _subscriberTotal_ =
      json["subscriberTotal"] ?? json["subscriber_total"];
    if (_subscriberTotal_) {
      msg.subscriberTotal = BigInt(_subscriberTotal_);
    }
    const _subscriberPoints_ =
      json["subscriberPoints"] ?? json["subscriber_points"];
    if (_subscriberPoints_) {
      msg.subscriberPoints = BigInt(_subscriberPoints_);
    }
    return msg;
  },
};

export const RecordStreamGaugeSampleResponseJSON = {
  /**
   * Serializes RecordStreamGaugeSampleResponse to JSON.
   */
  encode: function (msg: PartialDeep<RecordStreamGaugeSampleResponse>): string {
    return JSON.stringify(
      RecordStreamGaugeSampleResponseJSON._writeMessage(msg),
    );
  },

  /**
   * Deserializes RecordStreamGaugeSampleResponse from JSON.
   */
  decode: function (json: string): RecordStreamGaugeSampleResponse {
    return RecordStreamGaugeSampleResponseJSON._readMessage(
      RecordStreamGaugeSampleResponseJSON.initialize(),
      JSON.parse(json),
    );
  },

  /**
   * Initializes RecordStreamGaugeSampleResponse with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<RecordStreamGaugeSampleResponse>,
  ): RecordStreamGaugeSampleResponse {
    return {
      status: common.ResponseStatusJSON.initialize(),
      sample: StreamGaugeSampleJSON.initialize(),
      created: false,
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<RecordStreamGaugeSampleResponse>,
  ): Record<string, unknown> {
    const json: Record<string, unknown> = {};
    if (msg.status) {
      const _status_ = common.ResponseStatusJSON._writeMessage(msg.status);
      if (Object.keys(_status_).length > 0) {
        json["status"] = _status_;
      }
    }
    if (msg.sample) {
      const _sample_ = StreamGaugeSampleJSON._writeMessage(msg.sample);
      if (Object.keys(_sample_).length > 0) {
        json["sample"] = _sample_;
      }
    }
    if (msg.created) {
      json["created"] = msg.created;
    }
    return json;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: RecordStreamGaugeSampleResponse,
    json: any,
  ): RecordStreamGaugeSampleResponse {
    const _status_ = json["status"];
    if (_status_) {
      common.ResponseStatusJSON._readMessage(msg.status, _status_);
    }
    const _sample_ = json["sample"];
    if (_sample_) {
      StreamGaugeSampleJSON._readMessage(msg.sample, _sample_);
    }
    const _created_ = json["created"];
    if (_created_) {
      msg.created = _created_;
    }
    return msg;
  },
};

export const ListStreamGaugeSamplesRequestJSON = {
  /**
   * Serializes ListStreamGaugeSamplesRequest to JSON.
   */
  encode: function (msg: PartialDeep<ListStreamGaugeSamplesRequest>): string {
    return JSON.stringify(ListStreamGaugeSamplesRequestJSON._writeMessage(msg));
  },

  /**
   * Deserializes ListStreamGaugeSamplesRequest from JSON.
   */
  decode: function (json: string): ListStreamGaugeSamplesRequest {
    return ListStreamGaugeSamplesRequestJSON._readMessage(
      ListStreamGaugeSamplesRequestJSON.initialize(),
      JSON.parse(json),
    );
  },

  /**
   * Initializes ListStreamGaugeSamplesRequest with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<ListStreamGaugeSamplesRequest>,
  ): ListStreamGaugeSamplesRequest {
    return {
      streamSessionId: "",
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<ListStreamGaugeSamplesRequest>,
  ): Record<string, unknown> {
    const json: Record<string, unknown> = {};
    if (msg.streamSessionId) {
      json["streamSessionId"] = msg.streamSessionId;
    }
    return json;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: ListStreamGaugeSamplesRequest,
    json: any,
  ): ListStreamGaugeSamplesRequest {
    const _streamSessionId_ =
      json["streamSessionId"] ?? json["stream_session_id"];
    if (_streamSessionId_) {
      msg.streamSessionId = _streamSessionId_;
    }
    return msg;
  },
};

export const ListStreamGaugeSamplesResponseJSON = {
  /**
   * Serializes ListStreamGaugeSamplesResponse to JSON.
   */
  encode: function (msg: PartialDeep<ListStreamGaugeSamplesResponse>): string {
    return JSON.stringify(
      ListStreamGaugeSamplesResponseJSON._writeMessage(msg),
    );
  },

  /**
   * Deserializes ListStreamGaugeSamplesResponse from JSON.
   */
  decode: function (json: string): ListStreamGaugeSamplesResponse {
    return ListStreamGaugeSamplesResponseJSON._readMessage(
      ListStreamGaugeSamplesResponseJSON.initialize(),
      JSON.parse(json),
    );
  },

  /**
   * Initializes ListStreamGaugeSamplesResponse with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<ListStreamGaugeSamplesResponse>,
  ): ListStreamGaugeSamplesResponse {
    return {
      status: common.ResponseStatusJSON.initialize(),
      samples: [],
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<ListStreamGaugeSamplesResponse>,
  ): Record<string, unknown> {
    const json: Record<string, unknown> = {};
    if (msg.status) {
      const _status_ = common.ResponseStatusJSON._writeMessage(msg.status);
      if (Object.keys(_status_).length > 0) {
        json["status"] = _status_;
      }
    }
    if (msg.samples?.length) {
      json["samples"] = msg.samples.map(StreamGaugeSampleJSON._writeMessage);
    }
    return json;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: ListStreamGaugeSamplesResponse,
    json: any,
  ): ListStreamGaugeSamplesResponse {
    const _status_ = json["status"];
    if (_status_) {
      common.ResponseStatusJSON._readMessage(msg.status, _status_);
    }
    const _samples_ = json["samples"];
    if (_samples_) {
      for (const item of _samples_) {
        const m = StreamGaugeSampleJSON.initialize();
        StreamGaugeSampleJSON._readMessage(m, item);
        msg.samples.push(m);
      }
    }
    return msg;
  },
};
