// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// Source: viewer_fact.proto
/* eslint-disable */

import type { ByteSource, PartialDeep } from "protoscript";
import * as protoscript from "protoscript";
import { JSONrequest, PBrequest } from "twirpscript";
// This is the minimum version supported by the current runtime.
// If this line fails typechecking, breaking changes have been introduced and this
// file needs to be regenerated by running `npx twirpscript`.
export { MIN_SUPPORTED_VERSION_0_0_56 } from "twirpscript";
import type { ClientConfiguration } from "twirpscript";
import * as common from "./common.pb";

//========================================//
//                 Types                  //
//========================================//

export interface FactDefinition {
  /**
   * Canonical fact id, e.g. `woofx3:fact:messages` or `user:fact:<slug>`.
   */
  id: string;
  name: string;
  description: string;
  /**
   * The definition body as JSON:
   * `{"sources": [{"trigger", "subject", "where", "value"}], "aggregate": {"fn"}}`.
   */
  definition: string;
  /**
   * `number`, `string` or `timestamp`. Derived from the aggregate and, for
   * `last`, the type of the value field. A timestamp is epoch milliseconds.
   */
  valueKind: string;
  /**
   * `lifetime` or `session`.
   */
  windowKind: string;
  revision: bigint;
  createdByType: string;
  createdByRef: string;
  /**
   * When the current revision started counting live events.
   */
  countingSince: protoscript.Timestamp;
  /**
   * How far a backfill from the event log has reached. Absent when none ran.
   */
  backfilledThrough?: protoscript.Timestamp | null | undefined;
  createdAt: protoscript.Timestamp;
  updatedAt: protoscript.Timestamp;
  /**
   * `active`, `unresolved` (a source's trigger is not registered) or
   * `invalid` (a source no longer fits what its trigger emits). Resolved when
   * the definition is read, against the triggers registered then.
   */
  status: string;
  /**
   * Why the status is not `active`. Empty when it is.
   */
  reason: string;
  /**
   * One per source, in definition order. A source whose trigger did not
   * resolve has an empty `event`.
   */
  sources: ResolvedFactSource[];
}

/**
 * A source with its trigger resolved: what the workflow service needs to
 * match events and extract the viewer without reading the trigger itself.
 */
export interface ResolvedFactSource {
  /**
   * Canonical trigger id, `{moduleId}:trigger:{manifestId}`.
   */
  trigger: string;
  /**
   * The trigger's event pattern, the subject its events arrive on.
   */
  event: string;
  /**
   * Emits path of the identity field naming the viewer.
   */
  subjectPath: string;
  /**
   * True when the subject is an array: each id in it is a subject.
   */
  subjectIsArray: boolean;
  /**
   * Emits path of the boolean that is true when the identity is withheld, or
   * empty. Events where it is true are attributed to nobody.
   */
  anonymousWhen: string;
  /**
   * Emits path of the viewer's display name, or empty.
   */
  displayName: string;
  /**
   * Emits path of the value the aggregate reads, or empty.
   */
  valuePath: string;
  /**
   * The condition tree an event must satisfy, as JSON, or empty for every
   * event.
   */
  where: string;
}

export interface UpsertFactDefinitionRequest {
  id: string;
  name: string;
  description: string;
  /**
   * The definition body as JSON; see FactDefinition.definition.
   */
  definition: string;
  /**
   * `lifetime` or `session`.
   */
  windowKind: string;
  /**
   * Who declares the definition: `USER` for one saved from the UI, `MODULE`
   * for one a module manifest declares. Defaults to `USER`.
   */
  createdByType: string;
  createdByRef: string;
}

export interface FactDefinitionResponse {
  status: common.ResponseStatus;
  definition: FactDefinition;
}

export interface DeleteFactDefinitionRequest {
  id: string;
}

export interface ListFactDefinitionsRequest {}

export interface ListFactDefinitionsResponse {
  status: common.ResponseStatus;
  definitions: FactDefinition[];
}

/**
 * A stored value. Numbers and timestamps are in `num`, strings in `str`. The
 * session aggregates keep their count in `num` and the last session counted
 * in `str`.
 */
export interface FactValue {
  num?: number | null | undefined;
  str?: string | null | undefined;
}

export interface FactDelta {
  factId: string;
  /**
   * The definition revision the delta was computed against.
   */
  revision: bigint;
  platform: string;
  subjectId: string;
  subjectName?: string | null | undefined;
  /**
   * The definition's aggregate function; a mismatch fails the whole apply.
   */
  op: string;
  /**
   * The value the aggregate reads: `num` for sum, min and max, either for
   * last, neither for the rest.
   */
  num?: number | null | undefined;
  str?: string | null | undefined;
}

export interface ApplyFactDeltasRequest {
  /**
   * The CloudEvent's identity. Required unless `silent`.
   */
  source: string;
  eventId: string;
  /**
   * When the event happened. Timestamps and the stream session a session
   * window resolves to are taken from it.
   */
  occurredAt: protoscript.Timestamp;
  /**
   * The stream session the event was stamped with. Used only when no session
   * had started by `occurred_at`.
   */
  sessionStamp: string;
  /**
   * A backfill: the deltas are applied without recording the event as
   * applied, since the live path may apply the same event too. Every delta
   * must be for one fact.
   */
  silent: boolean;
  deltas: FactDelta[];
}

export interface FactValueChange {
  factId: string;
  platform: string;
  subjectId: string;
  /**
   * Empty for a lifetime value, the stream session id for a session value.
   */
  windowKey: string;
  subjectName?: string | null | undefined;
  /**
   * Absent when the value did not exist before.
   */
  before: FactValue;
  after: FactValue;
}

export interface ApplyFactDeltasResponse {
  status: common.ResponseStatus;
  /**
   * False when the event had been applied before; nothing was written.
   */
  applied: boolean;
  /**
   * Deltas dropped for a stale revision or a deleted definition.
   */
  dropped: number;
  changes: FactValueChange[];
}

export interface GetViewerFactsRequest {
  platform: string;
  subjectId: string;
}

export interface ViewerFactValue {
  factId: string;
  /**
   * `lifetime` or `session`.
   */
  windowKind: string;
  valueKind: string;
  value: FactValue;
  updatedAt: protoscript.Timestamp;
}

export interface GetViewerFactsResponse {
  status: common.ResponseStatus;
  /**
   * The stream session the session values belong to, or empty when no
   * session has started.
   */
  sessionId: string;
  /**
   * The viewer's most recently seen display name, or absent.
   */
  subjectName?: string | null | undefined;
  /**
   * Lifetime values and current-session values. A fact the viewer has no
   * value for is absent.
   */
  values: ViewerFactValue[];
}

//========================================//
//   ViewerFactService Protobuf Client    //
//========================================//

/**
 * Creates or replaces a definition, after resolving each source's trigger
 * and checking every path against what that trigger emits.
 *
 * A change to the definition body or window increments `revision` and
 * deletes every stored value of the fact in the same transaction, so a value
 * is only ever folded under one definition. A change to the name or
 * description alone keeps both. Saving an identical definition writes
 * nothing.
 *
 * Fails with `invalid_argument` when the definition is invalid, and with
 * `failed_precondition` when a source names a trigger that is not
 * registered and the definition is not module-declared (a module may
 * declare a fact over a trigger of a module installed later), or when the
 * id is owned by a different creator.
 */
export async function UpsertFactDefinition(
  upsertFactDefinitionRequest: UpsertFactDefinitionRequest,
  config?: ClientConfiguration,
): Promise<FactDefinitionResponse> {
  const response = await PBrequest(
    "/viewer_fact.ViewerFactService/UpsertFactDefinition",
    UpsertFactDefinitionRequest.encode(upsertFactDefinitionRequest),
    config,
  );
  return FactDefinitionResponse.decode(response);
}

/**
 * Deletes a definition and every value of it. Fails with `not_found` when
 * there is no such definition.
 */
export async function DeleteFactDefinition(
  deleteFactDefinitionRequest: DeleteFactDefinitionRequest,
  config?: ClientConfiguration,
): Promise<common.ResponseStatus> {
  const response = await PBrequest(
    "/viewer_fact.ViewerFactService/DeleteFactDefinition",
    DeleteFactDefinitionRequest.encode(deleteFactDefinitionRequest),
    config,
  );
  return common.ResponseStatus.decode(response);
}

/**
 * Every definition, each re-resolved against the triggers registered now.
 * A definition is applied only while its status is `active`.
 */
export async function ListFactDefinitions(
  listFactDefinitionsRequest: ListFactDefinitionsRequest,
  config?: ClientConfiguration,
): Promise<ListFactDefinitionsResponse> {
  const response = await PBrequest(
    "/viewer_fact.ViewerFactService/ListFactDefinitions",
    ListFactDefinitionsRequest.encode(listFactDefinitionsRequest),
    config,
  );
  return ListFactDefinitionsResponse.decode(response);
}

/**
 * Folds the deltas one event produced into the stored values in one
 * transaction, and returns every value that changed.
 *
 * Idempotent on (source, event_id): applying an event again writes nothing
 * and returns `applied` false. A delta computed against a revision that is
 * no longer current, or against a deleted definition, is dropped.
 */
export async function ApplyFactDeltas(
  applyFactDeltasRequest: ApplyFactDeltasRequest,
  config?: ClientConfiguration,
): Promise<ApplyFactDeltasResponse> {
  const response = await PBrequest(
    "/viewer_fact.ViewerFactService/ApplyFactDeltas",
    ApplyFactDeltasRequest.encode(applyFactDeltasRequest),
    config,
  );
  return ApplyFactDeltasResponse.decode(response);
}

/**
 * One viewer's lifetime values and their values in the current stream
 * session.
 */
export async function GetViewerFacts(
  getViewerFactsRequest: GetViewerFactsRequest,
  config?: ClientConfiguration,
): Promise<GetViewerFactsResponse> {
  const response = await PBrequest(
    "/viewer_fact.ViewerFactService/GetViewerFacts",
    GetViewerFactsRequest.encode(getViewerFactsRequest),
    config,
  );
  return GetViewerFactsResponse.decode(response);
}

//========================================//
//     ViewerFactService JSON Client      //
//========================================//

/**
 * Creates or replaces a definition, after resolving each source's trigger
 * and checking every path against what that trigger emits.
 *
 * A change to the definition body or window increments `revision` and
 * deletes every stored value of the fact in the same transaction, so a value
 * is only ever folded under one definition. A change to the name or
 * description alone keeps both. Saving an identical definition writes
 * nothing.
 *
 * Fails with `invalid_argument` when the definition is invalid, and with
 * `failed_precondition` when a source names a trigger that is not
 * registered and the definition is not module-declared (a module may
 * declare a fact over a trigger of a module installed later), or when the
 * id is owned by a different creator.
 */
export async function UpsertFactDefinitionJSON(
  upsertFactDefinitionRequest: UpsertFactDefinitionRequest,
  config?: ClientConfiguration,
): Promise<FactDefinitionResponse> {
  const response = await JSONrequest(
    "/viewer_fact.ViewerFactService/UpsertFactDefinition",
    UpsertFactDefinitionRequestJSON.encode(upsertFactDefinitionRequest),
    config,
  );
  return FactDefinitionResponseJSON.decode(response);
}

/**
 * Deletes a definition and every value of it. Fails with `not_found` when
 * there is no such definition.
 */
export async function DeleteFactDefinitionJSON(
  deleteFactDefinitionRequest: DeleteFactDefinitionRequest,
  config?: ClientConfiguration,
): Promise<common.ResponseStatus> {
  const response = await JSONrequest(
    "/viewer_fact.ViewerFactService/DeleteFactDefinition",
    DeleteFactDefinitionRequestJSON.encode(deleteFactDefinitionRequest),
    config,
  );
  return common.ResponseStatusJSON.decode(response);
}

/**
 * Every definition, each re-resolved against the triggers registered now.
 * A definition is applied only while its status is `active`.
 */
export async function ListFactDefinitionsJSON(
  listFactDefinitionsRequest: ListFactDefinitionsRequest,
  config?: ClientConfiguration,
): Promise<ListFactDefinitionsResponse> {
  const response = await JSONrequest(
    "/viewer_fact.ViewerFactService/ListFactDefinitions",
    ListFactDefinitionsRequestJSON.encode(listFactDefinitionsRequest),
    config,
  );
  return ListFactDefinitionsResponseJSON.decode(response);
}

/**
 * Folds the deltas one event produced into the stored values in one
 * transaction, and returns every value that changed.
 *
 * Idempotent on (source, event_id): applying an event again writes nothing
 * and returns `applied` false. A delta computed against a revision that is
 * no longer current, or against a deleted definition, is dropped.
 */
export async function ApplyFactDeltasJSON(
  applyFactDeltasRequest: ApplyFactDeltasRequest,
  config?: ClientConfiguration,
): Promise<ApplyFactDeltasResponse> {
  const response = await JSONrequest(
    "/viewer_fact.ViewerFactService/ApplyFactDeltas",
    ApplyFactDeltasRequestJSON.encode(applyFactDeltasRequest),
    config,
  );
  return ApplyFactDeltasResponseJSON.decode(response);
}

/**
 * One viewer's lifetime values and their values in the current stream
 * session.
 */
export async function GetViewerFactsJSON(
  getViewerFactsRequest: GetViewerFactsRequest,
  config?: ClientConfiguration,
): Promise<GetViewerFactsResponse> {
  const response = await JSONrequest(
    "/viewer_fact.ViewerFactService/GetViewerFacts",
    GetViewerFactsRequestJSON.encode(getViewerFactsRequest),
    config,
  );
  return GetViewerFactsResponseJSON.decode(response);
}

//========================================//
//           ViewerFactService            //
//========================================//

/**
 * Per-viewer facts: running aggregates of one field across the trigger events
 * that name a viewer, defined as data rather than as columns. A definition
 * says which triggers feed the fact, which emitted field names the viewer, and
 * how matching events fold into one value. The workflow service evaluates the
 * definitions against each event and sends the resulting deltas here; this
 * service is the only writer of the values.
 */
export interface ViewerFactService<Context = unknown> {
  /**
   * Creates or replaces a definition, after resolving each source's trigger
   * and checking every path against what that trigger emits.
   *
   * A change to the definition body or window increments `revision` and
   * deletes every stored value of the fact in the same transaction, so a value
   * is only ever folded under one definition. A change to the name or
   * description alone keeps both. Saving an identical definition writes
   * nothing.
   *
   * Fails with `invalid_argument` when the definition is invalid, and with
   * `failed_precondition` when a source names a trigger that is not
   * registered and the definition is not module-declared (a module may
   * declare a fact over a trigger of a module installed later), or when the
   * id is owned by a different creator.
   */
  UpsertFactDefinition: (
    upsertFactDefinitionRequest: UpsertFactDefinitionRequest,
    context: Context,
  ) => Promise<FactDefinitionResponse> | FactDefinitionResponse;
  /**
   * Deletes a definition and every value of it. Fails with `not_found` when
   * there is no such definition.
   */
  DeleteFactDefinition: (
    deleteFactDefinitionRequest: DeleteFactDefinitionRequest,
    context: Context,
  ) => Promise<common.ResponseStatus> | common.ResponseStatus;
  /**
   * Every definition, each re-resolved against the triggers registered now.
   * A definition is applied only while its status is `active`.
   */
  ListFactDefinitions: (
    listFactDefinitionsRequest: ListFactDefinitionsRequest,
    context: Context,
  ) => Promise<ListFactDefinitionsResponse> | ListFactDefinitionsResponse;
  /**
   * Folds the deltas one event produced into the stored values in one
   * transaction, and returns every value that changed.
   *
   * Idempotent on (source, event_id): applying an event again writes nothing
   * and returns `applied` false. A delta computed against a revision that is
   * no longer current, or against a deleted definition, is dropped.
   */
  ApplyFactDeltas: (
    applyFactDeltasRequest: ApplyFactDeltasRequest,
    context: Context,
  ) => Promise<ApplyFactDeltasResponse> | ApplyFactDeltasResponse;
  /**
   * One viewer's lifetime values and their values in the current stream
   * session.
   */
  GetViewerFacts: (
    getViewerFactsRequest: GetViewerFactsRequest,
    context: Context,
  ) => Promise<GetViewerFactsResponse> | GetViewerFactsResponse;
}

export function createViewerFactService<Context>(
  service: ViewerFactService<Context>,
) {
  return {
    name: "viewer_fact.ViewerFactService",
    methods: {
      UpsertFactDefinition: {
        name: "UpsertFactDefinition",
        handler: service.UpsertFactDefinition,
        input: {
          protobuf: UpsertFactDefinitionRequest,
          json: UpsertFactDefinitionRequestJSON,
        },
        output: {
          protobuf: FactDefinitionResponse,
          json: FactDefinitionResponseJSON,
        },
      },
      DeleteFactDefinition: {
        name: "DeleteFactDefinition",
        handler: service.DeleteFactDefinition,
        input: {
          protobuf: DeleteFactDefinitionRequest,
          json: DeleteFactDefinitionRequestJSON,
        },
        output: {
          protobuf: common.ResponseStatus,
          json: common.ResponseStatusJSON,
        },
      },
      ListFactDefinitions: {
        name: "ListFactDefinitions",
        handler: service.ListFactDefinitions,
        input: {
          protobuf: ListFactDefinitionsRequest,
          json: ListFactDefinitionsRequestJSON,
        },
        output: {
          protobuf: ListFactDefinitionsResponse,
          json: ListFactDefinitionsResponseJSON,
        },
      },
      ApplyFactDeltas: {
        name: "ApplyFactDeltas",
        handler: service.ApplyFactDeltas,
        input: {
          protobuf: ApplyFactDeltasRequest,
          json: ApplyFactDeltasRequestJSON,
        },
        output: {
          protobuf: ApplyFactDeltasResponse,
          json: ApplyFactDeltasResponseJSON,
        },
      },
      GetViewerFacts: {
        name: "GetViewerFacts",
        handler: service.GetViewerFacts,
        input: {
          protobuf: GetViewerFactsRequest,
          json: GetViewerFactsRequestJSON,
        },
        output: {
          protobuf: GetViewerFactsResponse,
          json: GetViewerFactsResponseJSON,
        },
      },
    },
  } as const;
}

//========================================//
//        Protobuf Encode / Decode        //
//========================================//

export const FactDefinition = {
  /**
   * Serializes FactDefinition to protobuf.
   */
  encode: function (msg: PartialDeep<FactDefinition>): Uint8Array {
    return FactDefinition._writeMessage(
      msg,
      new protoscript.BinaryWriter(),
    ).getResultBuffer();
  },

  /**
   * Deserializes FactDefinition from protobuf.
   */
  decode: function (bytes: ByteSource): FactDefinition {
    return FactDefinition._readMessage(
      FactDefinition.initialize(),
      new protoscript.BinaryReader(bytes),
    );
  },

  /**
   * Initializes FactDefinition with all fields set to their default value.
   */
  initialize: function (msg?: Partial<FactDefinition>): FactDefinition {
    return {
      id: "",
      name: "",
      description: "",
      definition: "",
      valueKind: "",
      windowKind: "",
      revision: 0n,
      createdByType: "",
      createdByRef: "",
      countingSince: protoscript.Timestamp.initialize(),
      backfilledThrough: undefined,
      createdAt: protoscript.Timestamp.initialize(),
      updatedAt: protoscript.Timestamp.initialize(),
      status: "",
      reason: "",
      sources: [],
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<FactDefinition>,
    writer: protoscript.BinaryWriter,
  ): protoscript.BinaryWriter {
    if (msg.id) {
      writer.writeString(1, msg.id);
    }
    if (msg.name) {
      writer.writeString(2, msg.name);
    }
    if (msg.description) {
      writer.writeString(3, msg.description);
    }
    if (msg.definition) {
      writer.writeString(4, msg.definition);
    }
    if (msg.valueKind) {
      writer.writeString(5, msg.valueKind);
    }
    if (msg.windowKind) {
      writer.writeString(6, msg.windowKind);
    }
    if (msg.revision) {
      writer.writeInt64String(7, msg.revision.toString() as any);
    }
    if (msg.createdByType) {
      writer.writeString(8, msg.createdByType);
    }
    if (msg.createdByRef) {
      writer.writeString(9, msg.createdByRef);
    }
    if (msg.countingSince) {
      writer.writeMessage(
        10,
        msg.countingSince,
        protoscript.Timestamp._writeMessage,
      );
    }
    if (msg.backfilledThrough != undefined) {
      writer.writeMessage(
        11,
        msg.backfilledThrough,
        protoscript.Timestamp._writeMessage,
      );
    }
    if (msg.createdAt) {
      writer.writeMessage(
        12,
        msg.createdAt,
        protoscript.Timestamp._writeMessage,
      );
    }
    if (msg.updatedAt) {
      writer.writeMessage(
        13,
        msg.updatedAt,
        protoscript.Timestamp._writeMessage,
      );
    }
    if (msg.status) {
      writer.writeString(14, msg.status);
    }
    if (msg.reason) {
      writer.writeString(15, msg.reason);
    }
    if (msg.sources?.length) {
      writer.writeRepeatedMessage(
        16,
        msg.sources as any,
        ResolvedFactSource._writeMessage,
      );
    }
    return writer;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: FactDefinition,
    reader: protoscript.BinaryReader,
  ): FactDefinition {
    while (reader.nextField()) {
      const field = reader.getFieldNumber();
      switch (field) {
        case 1: {
          msg.id = reader.readString();
          break;
        }
        case 2: {
          msg.name = reader.readString();
          break;
        }
        case 3: {
          msg.description = reader.readString();
          break;
        }
        case 4: {
          msg.definition = reader.readString();
          break;
        }
        case 5: {
          msg.valueKind = reader.readString();
          break;
        }
        case 6: {
          msg.windowKind = reader.readString();
          break;
        }
        case 7: {
          msg.revision = BigInt(reader.readInt64String());
          break;
        }
        case 8: {
          msg.createdByType = reader.readString();
          break;
        }
        case 9: {
          msg.createdByRef = reader.readString();
          break;
        }
        case 10: {
          reader.readMessage(
            msg.countingSince,
            protoscript.Timestamp._readMessage,
          );
          break;
        }
        case 11: {
          msg.backfilledThrough = protoscript.Timestamp.initialize();
          reader.readMessage(
            msg.backfilledThrough,
            protoscript.Timestamp._readMessage,
          );
          break;
        }
        case 12: {
          reader.readMessage(msg.createdAt, protoscript.Timestamp._readMessage);
          break;
        }
        case 13: {
          reader.readMessage(msg.updatedAt, protoscript.Timestamp._readMessage);
          break;
        }
        case 14: {
          msg.status = reader.readString();
          break;
        }
        case 15: {
          msg.reason = reader.readString();
          break;
        }
        case 16: {
          const m = ResolvedFactSource.initialize();
          reader.readMessage(m, ResolvedFactSource._readMessage);
          msg.sources.push(m);
          break;
        }
        default: {
          reader.skipField();
          break;
        }
      }
    }
    return msg;
  },
};

export const ResolvedFactSource = {
  /**
   * Serializes ResolvedFactSource to protobuf.
   */
  encode: function (msg: PartialDeep<ResolvedFactSource>): Uint8Array {
    return ResolvedFactSource._writeMessage(
      msg,
      new protoscript.BinaryWriter(),
    ).getResultBuffer();
  },

  /**
   * Deserializes ResolvedFactSource from protobuf.
   */
  decode: function (bytes: ByteSource): ResolvedFactSource {
    return ResolvedFactSource._readMessage(
      ResolvedFactSource.initialize(),
      new protoscript.BinaryReader(bytes),
    );
  },

  /**
   * Initializes ResolvedFactSource with all fields set to their default value.
   */
  initialize: function (msg?: Partial<ResolvedFactSource>): ResolvedFactSource {
    return {
      trigger: "",
      event: "",
      subjectPath: "",
      subjectIsArray: false,
      anonymousWhen: "",
      displayName: "",
      valuePath: "",
      where: "",
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<ResolvedFactSource>,
    writer: protoscript.BinaryWriter,
  ): protoscript.BinaryWriter {
    if (msg.trigger) {
      writer.writeString(1, msg.trigger);
    }
    if (msg.event) {
      writer.writeString(2, msg.event);
    }
    if (msg.subjectPath) {
      writer.writeString(3, msg.subjectPath);
    }
    if (msg.subjectIsArray) {
      writer.writeBool(4, msg.subjectIsArray);
    }
    if (msg.anonymousWhen) {
      writer.writeString(5, msg.anonymousWhen);
    }
    if (msg.displayName) {
      writer.writeString(6, msg.displayName);
    }
    if (msg.valuePath) {
      writer.writeString(7, msg.valuePath);
    }
    if (msg.where) {
      writer.writeString(8, msg.where);
    }
    return writer;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: ResolvedFactSource,
    reader: protoscript.BinaryReader,
  ): ResolvedFactSource {
    while (reader.nextField()) {
      const field = reader.getFieldNumber();
      switch (field) {
        case 1: {
          msg.trigger = reader.readString();
          break;
        }
        case 2: {
          msg.event = reader.readString();
          break;
        }
        case 3: {
          msg.subjectPath = reader.readString();
          break;
        }
        case 4: {
          msg.subjectIsArray = reader.readBool();
          break;
        }
        case 5: {
          msg.anonymousWhen = reader.readString();
          break;
        }
        case 6: {
          msg.displayName = reader.readString();
          break;
        }
        case 7: {
          msg.valuePath = reader.readString();
          break;
        }
        case 8: {
          msg.where = reader.readString();
          break;
        }
        default: {
          reader.skipField();
          break;
        }
      }
    }
    return msg;
  },
};

export const UpsertFactDefinitionRequest = {
  /**
   * Serializes UpsertFactDefinitionRequest to protobuf.
   */
  encode: function (msg: PartialDeep<UpsertFactDefinitionRequest>): Uint8Array {
    return UpsertFactDefinitionRequest._writeMessage(
      msg,
      new protoscript.BinaryWriter(),
    ).getResultBuffer();
  },

  /**
   * Deserializes UpsertFactDefinitionRequest from protobuf.
   */
  decode: function (bytes: ByteSource): UpsertFactDefinitionRequest {
    return UpsertFactDefinitionRequest._readMessage(
      UpsertFactDefinitionRequest.initialize(),
      new protoscript.BinaryReader(bytes),
    );
  },

  /**
   * Initializes UpsertFactDefinitionRequest with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<UpsertFactDefinitionRequest>,
  ): UpsertFactDefinitionRequest {
    return {
      id: "",
      name: "",
      description: "",
      definition: "",
      windowKind: "",
      createdByType: "",
      createdByRef: "",
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<UpsertFactDefinitionRequest>,
    writer: protoscript.BinaryWriter,
  ): protoscript.BinaryWriter {
    if (msg.id) {
      writer.writeString(1, msg.id);
    }
    if (msg.name) {
      writer.writeString(2, msg.name);
    }
    if (msg.description) {
      writer.writeString(3, msg.description);
    }
    if (msg.definition) {
      writer.writeString(4, msg.definition);
    }
    if (msg.windowKind) {
      writer.writeString(5, msg.windowKind);
    }
    if (msg.createdByType) {
      writer.writeString(6, msg.createdByType);
    }
    if (msg.createdByRef) {
      writer.writeString(7, msg.createdByRef);
    }
    return writer;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: UpsertFactDefinitionRequest,
    reader: protoscript.BinaryReader,
  ): UpsertFactDefinitionRequest {
    while (reader.nextField()) {
      const field = reader.getFieldNumber();
      switch (field) {
        case 1: {
          msg.id = reader.readString();
          break;
        }
        case 2: {
          msg.name = reader.readString();
          break;
        }
        case 3: {
          msg.description = reader.readString();
          break;
        }
        case 4: {
          msg.definition = reader.readString();
          break;
        }
        case 5: {
          msg.windowKind = reader.readString();
          break;
        }
        case 6: {
          msg.createdByType = reader.readString();
          break;
        }
        case 7: {
          msg.createdByRef = reader.readString();
          break;
        }
        default: {
          reader.skipField();
          break;
        }
      }
    }
    return msg;
  },
};

export const FactDefinitionResponse = {
  /**
   * Serializes FactDefinitionResponse to protobuf.
   */
  encode: function (msg: PartialDeep<FactDefinitionResponse>): Uint8Array {
    return FactDefinitionResponse._writeMessage(
      msg,
      new protoscript.BinaryWriter(),
    ).getResultBuffer();
  },

  /**
   * Deserializes FactDefinitionResponse from protobuf.
   */
  decode: function (bytes: ByteSource): FactDefinitionResponse {
    return FactDefinitionResponse._readMessage(
      FactDefinitionResponse.initialize(),
      new protoscript.BinaryReader(bytes),
    );
  },

  /**
   * Initializes FactDefinitionResponse with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<FactDefinitionResponse>,
  ): FactDefinitionResponse {
    return {
      status: common.ResponseStatus.initialize(),
      definition: FactDefinition.initialize(),
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<FactDefinitionResponse>,
    writer: protoscript.BinaryWriter,
  ): protoscript.BinaryWriter {
    if (msg.status) {
      writer.writeMessage(1, msg.status, common.ResponseStatus._writeMessage);
    }
    if (msg.definition) {
      writer.writeMessage(2, msg.definition, FactDefinition._writeMessage);
    }
    return writer;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: FactDefinitionResponse,
    reader: protoscript.BinaryReader,
  ): FactDefinitionResponse {
    while (reader.nextField()) {
      const field = reader.getFieldNumber();
      switch (field) {
        case 1: {
          reader.readMessage(msg.status, common.ResponseStatus._readMessage);
          break;
        }
        case 2: {
          reader.readMessage(msg.definition, FactDefinition._readMessage);
          break;
        }
        default: {
          reader.skipField();
          break;
        }
      }
    }
    return msg;
  },
};

export const DeleteFactDefinitionRequest = {
  /**
   * Serializes DeleteFactDefinitionRequest to protobuf.
   */
  encode: function (msg: PartialDeep<DeleteFactDefinitionRequest>): Uint8Array {
    return DeleteFactDefinitionRequest._writeMessage(
      msg,
      new protoscript.BinaryWriter(),
    ).getResultBuffer();
  },

  /**
   * Deserializes DeleteFactDefinitionRequest from protobuf.
   */
  decode: function (bytes: ByteSource): DeleteFactDefinitionRequest {
    return DeleteFactDefinitionRequest._readMessage(
      DeleteFactDefinitionRequest.initialize(),
      new protoscript.BinaryReader(bytes),
    );
  },

  /**
   * Initializes DeleteFactDefinitionRequest with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<DeleteFactDefinitionRequest>,
  ): DeleteFactDefinitionRequest {
    return {
      id: "",
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<DeleteFactDefinitionRequest>,
    writer: protoscript.BinaryWriter,
  ): protoscript.BinaryWriter {
    if (msg.id) {
      writer.writeString(1, msg.id);
    }
    return writer;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: DeleteFactDefinitionRequest,
    reader: protoscript.BinaryReader,
  ): DeleteFactDefinitionRequest {
    while (reader.nextField()) {
      const field = reader.getFieldNumber();
      switch (field) {
        case 1: {
          msg.id = reader.readString();
          break;
        }
        default: {
          reader.skipField();
          break;
        }
      }
    }
    return msg;
  },
};

export const ListFactDefinitionsRequest = {
  /**
   * Serializes ListFactDefinitionsRequest to protobuf.
   */
  encode: function (
    _msg?: PartialDeep<ListFactDefinitionsRequest>,
  ): Uint8Array {
    return new Uint8Array();
  },

  /**
   * Deserializes ListFactDefinitionsRequest from protobuf.
   */
  decode: function (_bytes?: ByteSource): ListFactDefinitionsRequest {
    return {};
  },

  /**
   * Initializes ListFactDefinitionsRequest with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<ListFactDefinitionsRequest>,
  ): ListFactDefinitionsRequest {
    return {
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    _msg: PartialDeep<ListFactDefinitionsRequest>,
    writer: protoscript.BinaryWriter,
  ): protoscript.BinaryWriter {
    return writer;
  },

  /**
   * @private
   */
  _readMessage: function (
    _msg: ListFactDefinitionsRequest,
    _reader: protoscript.BinaryReader,
  ): ListFactDefinitionsRequest {
    return _msg;
  },
};

export const ListFactDefinitionsResponse = {
  /**
   * Serializes ListFactDefinitionsResponse to protobuf.
   */
  encode: function (msg: PartialDeep<ListFactDefinitionsResponse>): Uint8Array {
    return ListFactDefinitionsResponse._writeMessage(
      msg,
      new protoscript.BinaryWriter(),
    ).getResultBuffer();
  },

  /**
   * Deserializes ListFactDefinitionsResponse from protobuf.
   */
  decode: function (bytes: ByteSource): ListFactDefinitionsResponse {
    return ListFactDefinitionsResponse._readMessage(
      ListFactDefinitionsResponse.initialize(),
      new protoscript.BinaryReader(bytes),
    );
  },

  /**
   * Initializes ListFactDefinitionsResponse with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<ListFactDefinitionsResponse>,
  ): ListFactDefinitionsResponse {
    return {
      status: common.ResponseStatus.initialize(),
      definitions: [],
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<ListFactDefinitionsResponse>,
    writer: protoscript.BinaryWriter,
  ): protoscript.BinaryWriter {
    if (msg.status) {
      writer.writeMessage(1, msg.status, common.ResponseStatus._writeMessage);
    }
    if (msg.definitions?.length) {
      writer.writeRepeatedMessage(
        2,
        msg.definitions as any,
        FactDefinition._writeMessage,
      );
    }
    return writer;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: ListFactDefinitionsResponse,
    reader: protoscript.BinaryReader,
  ): ListFactDefinitionsResponse {
    while (reader.nextField()) {
      const field = reader.getFieldNumber();
      switch (field) {
        case 1: {
          reader.readMessage(msg.status, common.ResponseStatus._readMessage);
          break;
        }
        case 2: {
          const m = FactDefinition.initialize();
          reader.readMessage(m, FactDefinition._readMessage);
          msg.definitions.push(m);
          break;
        }
        default: {
          reader.skipField();
          break;
        }
      }
    }
    return msg;
  },
};

export const FactValue = {
  /**
   * Serializes FactValue to protobuf.
   */
  encode: function (msg: PartialDeep<FactValue>): Uint8Array {
    return FactValue._writeMessage(
      msg,
      new protoscript.BinaryWriter(),
    ).getResultBuffer();
  },

  /**
   * Deserializes FactValue from protobuf.
   */
  decode: function (bytes: ByteSource): FactValue {
    return FactValue._readMessage(
      FactValue.initialize(),
      new protoscript.BinaryReader(bytes),
    );
  },

  /**
   * Initializes FactValue with all fields set to their default value.
   */
  initialize: function (msg?: Partial<FactValue>): FactValue {
    return {
      num: undefined,
      str: undefined,
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<FactValue>,
    writer: protoscript.BinaryWriter,
  ): protoscript.BinaryWriter {
    if (msg.num != undefined) {
      writer.writeDouble(1, msg.num);
    }
    if (msg.str != undefined) {
      writer.writeString(2, msg.str);
    }
    return writer;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: FactValue,
    reader: protoscript.BinaryReader,
  ): FactValue {
    while (reader.nextField()) {
      const field = reader.getFieldNumber();
      switch (field) {
        case 1: {
          msg.num = reader.readDouble();
          break;
        }
        case 2: {
          msg.str = reader.readString();
          break;
        }
        default: {
          reader.skipField();
          break;
        }
      }
    }
    return msg;
  },
};

export const FactDelta = {
  /**
   * Serializes FactDelta to protobuf.
   */
  encode: function (msg: PartialDeep<FactDelta>): Uint8Array {
    return FactDelta._writeMessage(
      msg,
      new protoscript.BinaryWriter(),
    ).getResultBuffer();
  },

  /**
   * Deserializes FactDelta from protobuf.
   */
  decode: function (bytes: ByteSource): FactDelta {
    return FactDelta._readMessage(
      FactDelta.initialize(),
      new protoscript.BinaryReader(bytes),
    );
  },

  /**
   * Initializes FactDelta with all fields set to their default value.
   */
  initialize: function (msg?: Partial<FactDelta>): FactDelta {
    return {
      factId: "",
      revision: 0n,
      platform: "",
      subjectId: "",
      subjectName: undefined,
      op: "",
      num: undefined,
      str: undefined,
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<FactDelta>,
    writer: protoscript.BinaryWriter,
  ): protoscript.BinaryWriter {
    if (msg.factId) {
      writer.writeString(1, msg.factId);
    }
    if (msg.revision) {
      writer.writeInt64String(2, msg.revision.toString() as any);
    }
    if (msg.platform) {
      writer.writeString(3, msg.platform);
    }
    if (msg.subjectId) {
      writer.writeString(4, msg.subjectId);
    }
    if (msg.subjectName != undefined) {
      writer.writeString(5, msg.subjectName);
    }
    if (msg.op) {
      writer.writeString(6, msg.op);
    }
    if (msg.num != undefined) {
      writer.writeDouble(7, msg.num);
    }
    if (msg.str != undefined) {
      writer.writeString(8, msg.str);
    }
    return writer;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: FactDelta,
    reader: protoscript.BinaryReader,
  ): FactDelta {
    while (reader.nextField()) {
      const field = reader.getFieldNumber();
      switch (field) {
        case 1: {
          msg.factId = reader.readString();
          break;
        }
        case 2: {
          msg.revision = BigInt(reader.readInt64String());
          break;
        }
        case 3: {
          msg.platform = reader.readString();
          break;
        }
        case 4: {
          msg.subjectId = reader.readString();
          break;
        }
        case 5: {
          msg.subjectName = reader.readString();
          break;
        }
        case 6: {
          msg.op = reader.readString();
          break;
        }
        case 7: {
          msg.num = reader.readDouble();
          break;
        }
        case 8: {
          msg.str = reader.readString();
          break;
        }
        default: {
          reader.skipField();
          break;
        }
      }
    }
    return msg;
  },
};

export const ApplyFactDeltasRequest = {
  /**
   * Serializes ApplyFactDeltasRequest to protobuf.
   */
  encode: function (msg: PartialDeep<ApplyFactDeltasRequest>): Uint8Array {
    return ApplyFactDeltasRequest._writeMessage(
      msg,
      new protoscript.BinaryWriter(),
    ).getResultBuffer();
  },

  /**
   * Deserializes ApplyFactDeltasRequest from protobuf.
   */
  decode: function (bytes: ByteSource): ApplyFactDeltasRequest {
    return ApplyFactDeltasRequest._readMessage(
      ApplyFactDeltasRequest.initialize(),
      new protoscript.BinaryReader(bytes),
    );
  },

  /**
   * Initializes ApplyFactDeltasRequest with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<ApplyFactDeltasRequest>,
  ): ApplyFactDeltasRequest {
    return {
      source: "",
      eventId: "",
      occurredAt: protoscript.Timestamp.initialize(),
      sessionStamp: "",
      silent: false,
      deltas: [],
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<ApplyFactDeltasRequest>,
    writer: protoscript.BinaryWriter,
  ): protoscript.BinaryWriter {
    if (msg.source) {
      writer.writeString(1, msg.source);
    }
    if (msg.eventId) {
      writer.writeString(2, msg.eventId);
    }
    if (msg.occurredAt) {
      writer.writeMessage(
        3,
        msg.occurredAt,
        protoscript.Timestamp._writeMessage,
      );
    }
    if (msg.sessionStamp) {
      writer.writeString(4, msg.sessionStamp);
    }
    if (msg.silent) {
      writer.writeBool(5, msg.silent);
    }
    if (msg.deltas?.length) {
      writer.writeRepeatedMessage(
        6,
        msg.deltas as any,
        FactDelta._writeMessage,
      );
    }
    return writer;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: ApplyFactDeltasRequest,
    reader: protoscript.BinaryReader,
  ): ApplyFactDeltasRequest {
    while (reader.nextField()) {
      const field = reader.getFieldNumber();
      switch (field) {
        case 1: {
          msg.source = reader.readString();
          break;
        }
        case 2: {
          msg.eventId = reader.readString();
          break;
        }
        case 3: {
          reader.readMessage(
            msg.occurredAt,
            protoscript.Timestamp._readMessage,
          );
          break;
        }
        case 4: {
          msg.sessionStamp = reader.readString();
          break;
        }
        case 5: {
          msg.silent = reader.readBool();
          break;
        }
        case 6: {
          const m = FactDelta.initialize();
          reader.readMessage(m, FactDelta._readMessage);
          msg.deltas.push(m);
          break;
        }
        default: {
          reader.skipField();
          break;
        }
      }
    }
    return msg;
  },
};

export const FactValueChange = {
  /**
   * Serializes FactValueChange to protobuf.
   */
  encode: function (msg: PartialDeep<FactValueChange>): Uint8Array {
    return FactValueChange._writeMessage(
      msg,
      new protoscript.BinaryWriter(),
    ).getResultBuffer();
  },

  /**
   * Deserializes FactValueChange from protobuf.
   */
  decode: function (bytes: ByteSource): FactValueChange {
    return FactValueChange._readMessage(
      FactValueChange.initialize(),
      new protoscript.BinaryReader(bytes),
    );
  },

  /**
   * Initializes FactValueChange with all fields set to their default value.
   */
  initialize: function (msg?: Partial<FactValueChange>): FactValueChange {
    return {
      factId: "",
      platform: "",
      subjectId: "",
      windowKey: "",
      subjectName: undefined,
      before: FactValue.initialize(),
      after: FactValue.initialize(),
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<FactValueChange>,
    writer: protoscript.BinaryWriter,
  ): protoscript.BinaryWriter {
    if (msg.factId) {
      writer.writeString(1, msg.factId);
    }
    if (msg.platform) {
      writer.writeString(2, msg.platform);
    }
    if (msg.subjectId) {
      writer.writeString(3, msg.subjectId);
    }
    if (msg.windowKey) {
      writer.writeString(4, msg.windowKey);
    }
    if (msg.subjectName != undefined) {
      writer.writeString(5, msg.subjectName);
    }
    if (msg.before) {
      writer.writeMessage(6, msg.before, FactValue._writeMessage);
    }
    if (msg.after) {
      writer.writeMessage(7, msg.after, FactValue._writeMessage);
    }
    return writer;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: FactValueChange,
    reader: protoscript.BinaryReader,
  ): FactValueChange {
    while (reader.nextField()) {
      const field = reader.getFieldNumber();
      switch (field) {
        case 1: {
          msg.factId = reader.readString();
          break;
        }
        case 2: {
          msg.platform = reader.readString();
          break;
        }
        case 3: {
          msg.subjectId = reader.readString();
          break;
        }
        case 4: {
          msg.windowKey = reader.readString();
          break;
        }
        case 5: {
          msg.subjectName = reader.readString();
          break;
        }
        case 6: {
          reader.readMessage(msg.before, FactValue._readMessage);
          break;
        }
        case 7: {
          reader.readMessage(msg.after, FactValue._readMessage);
          break;
        }
        default: {
          reader.skipField();
          break;
        }
      }
    }
    return msg;
  },
};

export const ApplyFactDeltasResponse = {
  /**
   * Serializes ApplyFactDeltasResponse to protobuf.
   */
  encode: function (msg: PartialDeep<ApplyFactDeltasResponse>): Uint8Array {
    return ApplyFactDeltasResponse._writeMessage(
      msg,
      new protoscript.BinaryWriter(),
    ).getResultBuffer();
  },

  /**
   * Deserializes ApplyFactDeltasResponse from protobuf.
   */
  decode: function (bytes: ByteSource): ApplyFactDeltasResponse {
    return ApplyFactDeltasResponse._readMessage(
      ApplyFactDeltasResponse.initialize(),
      new protoscript.BinaryReader(bytes),
    );
  },

  /**
   * Initializes ApplyFactDeltasResponse with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<ApplyFactDeltasResponse>,
  ): ApplyFactDeltasResponse {
    return {
      status: common.ResponseStatus.initialize(),
      applied: false,
      dropped: 0,
      changes: [],
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<ApplyFactDeltasResponse>,
    writer: protoscript.BinaryWriter,
  ): protoscript.BinaryWriter {
    if (msg.status) {
      writer.writeMessage(1, msg.status, common.ResponseStatus._writeMessage);
    }
    if (msg.applied) {
      writer.writeBool(2, msg.applied);
    }
    if (msg.dropped) {
      writer.writeInt32(3, msg.dropped);
    }
    if (msg.changes?.length) {
      writer.writeRepeatedMessage(
        4,
        msg.changes as any,
        FactValueChange._writeMessage,
      );
    }
    return writer;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: ApplyFactDeltasResponse,
    reader: protoscript.BinaryReader,
  ): ApplyFactDeltasResponse {
    while (reader.nextField()) {
      const field = reader.getFieldNumber();
      switch (field) {
        case 1: {
          reader.readMessage(msg.status, common.ResponseStatus._readMessage);
          break;
        }
        case 2: {
          msg.applied = reader.readBool();
          break;
        }
        case 3: {
          msg.dropped = reader.readInt32();
          break;
        }
        case 4: {
          const m = FactValueChange.initialize();
          reader.readMessage(m, FactValueChange._readMessage);
          msg.changes.push(m);
          break;
        }
        default: {
          reader.skipField();
          break;
        }
      }
    }
    return msg;
  },
};

export const GetViewerFactsRequest = {
  /**
   * Serializes GetViewerFactsRequest to protobuf.
   */
  encode: function (msg: PartialDeep<GetViewerFactsRequest>): Uint8Array {
    return GetViewerFactsRequest._writeMessage(
      msg,
      new protoscript.BinaryWriter(),
    ).getResultBuffer();
  },

  /**
   * Deserializes GetViewerFactsRequest from protobuf.
   */
  decode: function (bytes: ByteSource): GetViewerFactsRequest {
    return GetViewerFactsRequest._readMessage(
      GetViewerFactsRequest.initialize(),
      new protoscript.BinaryReader(bytes),
    );
  },

  /**
   * Initializes GetViewerFactsRequest with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<GetViewerFactsRequest>,
  ): GetViewerFactsRequest {
    return {
      platform: "",
      subjectId: "",
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<GetViewerFactsRequest>,
    writer: protoscript.BinaryWriter,
  ): protoscript.BinaryWriter {
    if (msg.platform) {
      writer.writeString(1, msg.platform);
    }
    if (msg.subjectId) {
      writer.writeString(2, msg.subjectId);
    }
    return writer;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: GetViewerFactsRequest,
    reader: protoscript.BinaryReader,
  ): GetViewerFactsRequest {
    while (reader.nextField()) {
      const field = reader.getFieldNumber();
      switch (field) {
        case 1: {
          msg.platform = reader.readString();
          break;
        }
        case 2: {
          msg.subjectId = reader.readString();
          break;
        }
        default: {
          reader.skipField();
          break;
        }
      }
    }
    return msg;
  },
};

export const ViewerFactValue = {
  /**
   * Serializes ViewerFactValue to protobuf.
   */
  encode: function (msg: PartialDeep<ViewerFactValue>): Uint8Array {
    return ViewerFactValue._writeMessage(
      msg,
      new protoscript.BinaryWriter(),
    ).getResultBuffer();
  },

  /**
   * Deserializes ViewerFactValue from protobuf.
   */
  decode: function (bytes: ByteSource): ViewerFactValue {
    return ViewerFactValue._readMessage(
      ViewerFactValue.initialize(),
      new protoscript.BinaryReader(bytes),
    );
  },

  /**
   * Initializes ViewerFactValue with all fields set to their default value.
   */
  initialize: function (msg?: Partial<ViewerFactValue>): ViewerFactValue {
    return {
      factId: "",
      windowKind: "",
      valueKind: "",
      value: FactValue.initialize(),
      updatedAt: protoscript.Timestamp.initialize(),
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<ViewerFactValue>,
    writer: protoscript.BinaryWriter,
  ): protoscript.BinaryWriter {
    if (msg.factId) {
      writer.writeString(1, msg.factId);
    }
    if (msg.windowKind) {
      writer.writeString(2, msg.windowKind);
    }
    if (msg.valueKind) {
      writer.writeString(3, msg.valueKind);
    }
    if (msg.value) {
      writer.writeMessage(4, msg.value, FactValue._writeMessage);
    }
    if (msg.updatedAt) {
      writer.writeMessage(
        5,
        msg.updatedAt,
        protoscript.Timestamp._writeMessage,
      );
    }
    return writer;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: ViewerFactValue,
    reader: protoscript.BinaryReader,
  ): ViewerFactValue {
    while (reader.nextField()) {
      const field = reader.getFieldNumber();
      switch (field) {
        case 1: {
          msg.factId = reader.readString();
          break;
        }
        case 2: {
          msg.windowKind = reader.readString();
          break;
        }
        case 3: {
          msg.valueKind = reader.readString();
          break;
        }
        case 4: {
          reader.readMessage(msg.value, FactValue._readMessage);
          break;
        }
        case 5: {
          reader.readMessage(msg.updatedAt, protoscript.Timestamp._readMessage);
          break;
        }
        default: {
          reader.skipField();
          break;
        }
      }
    }
    return msg;
  },
};

export const GetViewerFactsResponse = {
  /**
   * Serializes GetViewerFactsResponse to protobuf.
   */
  encode: function (msg: PartialDeep<GetViewerFactsResponse>): Uint8Array {
    return GetViewerFactsResponse._writeMessage(
      msg,
      new protoscript.BinaryWriter(),
    ).getResultBuffer();
  },

  /**
   * Deserializes GetViewerFactsResponse from protobuf.
   */
  decode: function (bytes: ByteSource): GetViewerFactsResponse {
    return GetViewerFactsResponse._readMessage(
      GetViewerFactsResponse.initialize(),
      new protoscript.BinaryReader(bytes),
    );
  },

  /**
   * Initializes GetViewerFactsResponse with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<GetViewerFactsResponse>,
  ): GetViewerFactsResponse {
    return {
      status: common.ResponseStatus.initialize(),
      sessionId: "",
      subjectName: undefined,
      values: [],
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<GetViewerFactsResponse>,
    writer: protoscript.BinaryWriter,
  ): protoscript.BinaryWriter {
    if (msg.status) {
      writer.writeMessage(1, msg.status, common.ResponseStatus._writeMessage);
    }
    if (msg.sessionId) {
      writer.writeString(2, msg.sessionId);
    }
    if (msg.subjectName != undefined) {
      writer.writeString(3, msg.subjectName);
    }
    if (msg.values?.length) {
      writer.writeRepeatedMessage(
        4,
        msg.values as any,
        ViewerFactValue._writeMessage,
      );
    }
    return writer;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: GetViewerFactsResponse,
    reader: protoscript.BinaryReader,
  ): GetViewerFactsResponse {
    while (reader.nextField()) {
      const field = reader.getFieldNumber();
      switch (field) {
        case 1: {
          reader.readMessage(msg.status, common.ResponseStatus._readMessage);
          break;
        }
        case 2: {
          msg.sessionId = reader.readString();
          break;
        }
        case 3: {
          msg.subjectName = reader.readString();
          break;
        }
        case 4: {
          const m = ViewerFactValue.initialize();
          reader.readMessage(m, ViewerFactValue._readMessage);
          msg.values.push(m);
          break;
        }
        default: {
          reader.skipField();
          break;
        }
      }
    }
    return msg;
  },
};

//========================================//
//          JSON Encode / Decode          //
//========================================//

export const FactDefinitionJSON = {
  /**
   * Serializes FactDefinition to JSON.
   */
  encode: function (msg: PartialDeep<FactDefinition>): string {
    return JSON.stringify(FactDefinitionJSON._writeMessage(msg));
  },

  /**
   * Deserializes FactDefinition from JSON.
   */
  decode: function (json: string): FactDefinition {
    return FactDefinitionJSON._readMessage(
      FactDefinitionJSON.initialize(),
      JSON.parse(json),
    );
  },

  /**
   * Initializes FactDefinition with all fields set to their default value.
   */
  initialize: function (msg?: Partial<FactDefinition>): FactDefinition {
    return {
      id: "",
      name: "",
      description: "",
      definition: "",
      valueKind: "",
      windowKind: "",
      revision: 0n,
      createdByType: "",
      createdByRef: "",
      countingSince: protoscript.TimestampJSON.initialize(),
      backfilledThrough: undefined,
      createdAt: protoscript.TimestampJSON.initialize(),
      updatedAt: protoscript.TimestampJSON.initialize(),
      status: "",
      reason: "",
      sources: [],
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<FactDefinition>,
  ): Record<string, unknown> {
    const json: Record<string, unknown> = {};
    if (msg.id) {
      json["id"] = msg.id;
    }
    if (msg.name) {
      json["name"] = msg.name;
    }
    if (msg.description) {
      json["description"] = msg.description;
    }
    if (msg.definition) {
      json["definition"] = msg.definition;
    }
    if (msg.valueKind) {
      json["valueKind"] = msg.valueKind;
    }
    if (msg.windowKind) {
      json["windowKind"] = msg.windowKind;
    }
    if (msg.revision) {
      json["revision"] = String(msg.revision);
    }
    if (msg.createdByType) {
      json["createdByType"] = msg.createdByType;
    }
    if (msg.createdByRef) {
      json["createdByRef"] = msg.createdByRef;
    }
    if (
      msg.countingSince &&
      (msg.countingSince.seconds || msg.countingSince.nanos)
    ) {
      json["countingSince"] = protoscript.serializeTimestamp(msg.countingSince);
    }
    if (msg.backfilledThrough != undefined) {
      json["backfilledThrough"] = protoscript.serializeTimestamp(
        msg.backfilledThrough,
      );
    }
    if (msg.createdAt && (msg.createdAt.seconds || msg.createdAt.nanos)) {
      json["createdAt"] = protoscript.serializeTimestamp(msg.createdAt);
    }
    if (msg.updatedAt && (msg.updatedAt.seconds || msg.updatedAt.nanos)) {
      json["updatedAt"] = protoscript.serializeTimestamp(msg.updatedAt);
    }
    if (msg.status) {
      json["status"] = msg.status;
    }
    if (msg.reason) {
      json["reason"] = msg.reason;
    }
    if (msg.sources?.length) {
      json["sources"] = msg.sources.map(ResolvedFactSourceJSON._writeMessage);
    }
    return json;
  },

  /**
   * @private
   */
  _readMessage: function (msg: FactDefinition, json: any): FactDefinition {
    const _id_ = json["id"];
    if (_id_) {
      msg.id = _id_;
    }
    const _name_ = json["name"];
    if (_name_) {
      msg.name = _name_;
    }
    const _description_ = json["description"];
    if (_description_) {
      msg.description = _description_;
    }
    const _definition_ = json["definition"];
    if (_definition_) {
      msg.definition = _definition_;
    }
    const _valueKind_ = json["valueKind"] ?? json["value_kind"];
    if (_valueKind_) {
      msg.valueKind = _valueKind_;
    }
    const _windowKind_ = json["windowKind"] ?? json["window_kind"];
    if (_windowKind_) {
      msg.windowKind = _windowKind_;
    }
    const _revision_ = json["revision"];
    if (_revision_) {
      msg.revision = BigInt(_revision_);
    }
    const _createdByType_ = json["createdByType"] ?? json["created_by_type"];
    if (_createdByType_) {
      msg.createdByType = _createdByType_;
    }
    const _createdByRef_ = json["createdByRef"] ?? json["created_by_ref"];
    if (_createdByRef_) {
      msg.createdByRef = _createdByRef_;
    }
    const _countingSince_ = json["countingSince"] ?? json["counting_since"];
    if (_countingSince_) {
      msg.countingSince = protoscript.parseTimestamp(_countingSince_);
    }
    const _backfilledThrough_ =
      json["backfilledThrough"] ?? json["backfilled_through"];
    if (_backfilledThrough_) {
      msg.backfilledThrough = protoscript.parseTimestamp(_backfilledThrough_);
    }
    const _createdAt_ = json["createdAt"] ?? json["created_at"];
    if (_createdAt_) {
      msg.createdAt = protoscript.parseTimestamp(_createdAt_);
    }
    const _updatedAt_ = json["updatedAt"] ?? json["updated_at"];
    if (_updatedAt_) {
      msg.updatedAt = protoscript.parseTimestamp(_updatedAt_);
    }
    const _status_ = json["status"];
    if (_status_) {
      msg.status = _status_;
    }
    const _reason_ = json["reason"];
    if (_reason_) {
      msg.reason = _reason_;
    }
    const _sources_ = json["sources"];
    if (_sources_) {
      for (const item of _sources_) {
        const m = ResolvedFactSourceJSON.initialize();
        ResolvedFactSourceJSON._readMessage(m, item);
        msg.sources.push(m);
      }
    }
    return msg;
  },
};

export const ResolvedFactSourceJSON = {
  /**
   * Serializes ResolvedFactSource to JSON.
   */
  encode: function (msg: PartialDeep<ResolvedFactSource>): string {
    return JSON.stringify(ResolvedFactSourceJSON._writeMessage(msg));
  },

  /**
   * Deserializes ResolvedFactSource from JSON.
   */
  decode: function (json: string): ResolvedFactSource {
    return ResolvedFactSourceJSON._readMessage(
      ResolvedFactSourceJSON.initialize(),
      JSON.parse(json),
    );
  },

  /**
   * Initializes ResolvedFactSource with all fields set to their default value.
   */
  initialize: function (msg?: Partial<ResolvedFactSource>): ResolvedFactSource {
    return {
      trigger: "",
      event: "",
      subjectPath: "",
      subjectIsArray: false,
      anonymousWhen: "",
      displayName: "",
      valuePath: "",
      where: "",
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<ResolvedFactSource>,
  ): Record<string, unknown> {
    const json: Record<string, unknown> = {};
    if (msg.trigger) {
      json["trigger"] = msg.trigger;
    }
    if (msg.event) {
      json["event"] = msg.event;
    }
    if (msg.subjectPath) {
      json["subjectPath"] = msg.subjectPath;
    }
    if (msg.subjectIsArray) {
      json["subjectIsArray"] = msg.subjectIsArray;
    }
    if (msg.anonymousWhen) {
      json["anonymousWhen"] = msg.anonymousWhen;
    }
    if (msg.displayName) {
      json["displayName"] = msg.displayName;
    }
    if (msg.valuePath) {
      json["valuePath"] = msg.valuePath;
    }
    if (msg.where) {
      json["where"] = msg.where;
    }
    return json;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: ResolvedFactSource,
    json: any,
  ): ResolvedFactSource {
    const _trigger_ = json["trigger"];
    if (_trigger_) {
      msg.trigger = _trigger_;
    }
    const _event_ = json["event"];
    if (_event_) {
      msg.event = _event_;
    }
    const _subjectPath_ = json["subjectPath"] ?? json["subject_path"];
    if (_subjectPath_) {
      msg.subjectPath = _subjectPath_;
    }
    const _subjectIsArray_ = json["subjectIsArray"] ?? json["subject_is_array"];
    if (_subjectIsArray_) {
      msg.subjectIsArray = _subjectIsArray_;
    }
    const _anonymousWhen_ = json["anonymousWhen"] ?? json["anonymous_when"];
    if (_anonymousWhen_) {
      msg.anonymousWhen = _anonymousWhen_;
    }
    const _displayName_ = json["displayName"] ?? json["display_name"];
    if (_displayName_) {
      msg.displayName = _displayName_;
    }
    const _valuePath_ = json["valuePath"] ?? json["value_path"];
    if (_valuePath_) {
      msg.valuePath = _valuePath_;
    }
    const _where_ = json["where"];
    if (_where_) {
      msg.where = _where_;
    }
    return msg;
  },
};

export const UpsertFactDefinitionRequestJSON = {
  /**
   * Serializes UpsertFactDefinitionRequest to JSON.
   */
  encode: function (msg: PartialDeep<UpsertFactDefinitionRequest>): string {
    return JSON.stringify(UpsertFactDefinitionRequestJSON._writeMessage(msg));
  },

  /**
   * Deserializes UpsertFactDefinitionRequest from JSON.
   */
  decode: function (json: string): UpsertFactDefinitionRequest {
    return UpsertFactDefinitionRequestJSON._readMessage(
      UpsertFactDefinitionRequestJSON.initialize(),
      JSON.parse(json),
    );
  },

  /**
   * Initializes UpsertFactDefinitionRequest with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<UpsertFactDefinitionRequest>,
  ): UpsertFactDefinitionRequest {
    return {
      id: "",
      name: "",
      description: "",
      definition: "",
      windowKind: "",
      createdByType: "",
      createdByRef: "",
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<UpsertFactDefinitionRequest>,
  ): Record<string, unknown> {
    const json: Record<string, unknown> = {};
    if (msg.id) {
      json["id"] = msg.id;
    }
    if (msg.name) {
      json["name"] = msg.name;
    }
    if (msg.description) {
      json["description"] = msg.description;
    }
    if (msg.definition) {
      json["definition"] = msg.definition;
    }
    if (msg.windowKind) {
      json["windowKind"] = msg.windowKind;
    }
    if (msg.createdByType) {
      json["createdByType"] = msg.createdByType;
    }
    if (msg.createdByRef) {
      json["createdByRef"] = msg.createdByRef;
    }
    return json;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: UpsertFactDefinitionRequest,
    json: any,
  ): UpsertFactDefinitionRequest {
    const _id_ = json["id"];
    if (_id_) {
      msg.id = _id_;
    }
    const _name_ = json["name"];
    if (_name_) {
      msg.name = _name_;
    }
    const _description_ = json["description"];
    if (_description_) {
      msg.description = _description_;
    }
    const _definition_ = json["definition"];
    if (_definition_) {
      msg.definition = _definition_;
    }
    const _windowKind_ = json["windowKind"] ?? json["window_kind"];
    if (_windowKind_) {
      msg.windowKind = _windowKind_;
    }
    const _createdByType_ = json["createdByType"] ?? json["created_by_type"];
    if (_createdByType_) {
      msg.createdByType = _createdByType_;
    }
    const _createdByRef_ = json["createdByRef"] ?? json["created_by_ref"];
    if (_createdByRef_) {
      msg.createdByRef = _createdByRef_;
    }
    return msg;
  },
};

export const FactDefinitionResponseJSON = {
  /**
   * Serializes FactDefinitionResponse to JSON.
   */
  encode: function (msg: PartialDeep<FactDefinitionResponse>): string {
    return JSON.stringify(FactDefinitionResponseJSON._writeMessage(msg));
  },

  /**
   * Deserializes FactDefinitionResponse from JSON.
   */
  decode: function (json: string): FactDefinitionResponse {
    return FactDefinitionResponseJSON._readMessage(
      FactDefinitionResponseJSON.initialize(),
      JSON.parse(json),
    );
  },

  /**
   * Initializes FactDefinitionResponse with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<FactDefinitionResponse>,
  ): FactDefinitionResponse {
    return {
      status: common.ResponseStatusJSON.initialize(),
      definition: FactDefinitionJSON.initialize(),
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<FactDefinitionResponse>,
  ): Record<string, unknown> {
    const json: Record<string, unknown> = {};
    if (msg.status) {
      const _status_ = common.ResponseStatusJSON._writeMessage(msg.status);
      if (Object.keys(_status_).length > 0) {
        json["status"] = _status_;
      }
    }
    if (msg.definition) {
      const _definition_ = FactDefinitionJSON._writeMessage(msg.definition);
      if (Object.keys(_definition_).length > 0) {
        json["definition"] = _definition_;
      }
    }
    return json;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: FactDefinitionResponse,
    json: any,
  ): FactDefinitionResponse {
    const _status_ = json["status"];
    if (_status_) {
      common.ResponseStatusJSON._readMessage(msg.status, _status_);
    }
    const _definition_ = json["definition"];
    if (_definition_) {
      FactDefinitionJSON._readMessage(msg.definition, _definition_);
    }
    return msg;
  },
};

export const DeleteFactDefinitionRequestJSON = {
  /**
   * Serializes DeleteFactDefinitionRequest to JSON.
   */
  encode: function (msg: PartialDeep<DeleteFactDefinitionRequest>): string {
    return JSON.stringify(DeleteFactDefinitionRequestJSON._writeMessage(msg));
  },

  /**
   * Deserializes DeleteFactDefinitionRequest from JSON.
   */
  decode: function (json: string): DeleteFactDefinitionRequest {
    return DeleteFactDefinitionRequestJSON._readMessage(
      DeleteFactDefinitionRequestJSON.initialize(),
      JSON.parse(json),
    );
  },

  /**
   * Initializes DeleteFactDefinitionRequest with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<DeleteFactDefinitionRequest>,
  ): DeleteFactDefinitionRequest {
    return {
      id: "",
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<DeleteFactDefinitionRequest>,
  ): Record<string, unknown> {
    const json: Record<string, unknown> = {};
    if (msg.id) {
      json["id"] = msg.id;
    }
    return json;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: DeleteFactDefinitionRequest,
    json: any,
  ): DeleteFactDefinitionRequest {
    const _id_ = json["id"];
    if (_id_) {
      msg.id = _id_;
    }
    return msg;
  },
};

export const ListFactDefinitionsRequestJSON = {
  /**
   * Serializes ListFactDefinitionsRequest to JSON.
   */
  encode: function (_msg?: PartialDeep<ListFactDefinitionsRequest>): string {
    return "{}";
  },

  /**
   * Deserializes ListFactDefinitionsRequest from JSON.
   */
  decode: function (_json?: string): ListFactDefinitionsRequest {
    return {};
  },

  /**
   * Initializes ListFactDefinitionsRequest with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<ListFactDefinitionsRequest>,
  ): ListFactDefinitionsRequest {
    return {
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    _msg: PartialDeep<ListFactDefinitionsRequest>,
  ): Record<string, unknown> {
    return {};
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: ListFactDefinitionsRequest,
    _json: any,
  ): ListFactDefinitionsRequest {
    return msg;
  },
};

export const ListFactDefinitionsResponseJSON = {
  /**
   * Serializes ListFactDefinitionsResponse to JSON.
   */
  encode: function (msg: PartialDeep<ListFactDefinitionsResponse>): string {
    return JSON.stringify(ListFactDefinitionsResponseJSON._writeMessage(msg));
  },

  /**
   * Deserializes ListFactDefinitionsResponse from JSON.
   */
  decode: function (json: string): ListFactDefinitionsResponse {
    return ListFactDefinitionsResponseJSON._readMessage(
      ListFactDefinitionsResponseJSON.initialize(),
      JSON.parse(json),
    );
  },

  /**
   * Initializes ListFactDefinitionsResponse with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<ListFactDefinitionsResponse>,
  ): ListFactDefinitionsResponse {
    return {
      status: common.ResponseStatusJSON.initialize(),
      definitions: [],
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<ListFactDefinitionsResponse>,
  ): Record<string, unknown> {
    const json: Record<string, unknown> = {};
    if (msg.status) {
      const _status_ = common.ResponseStatusJSON._writeMessage(msg.status);
      if (Object.keys(_status_).length > 0) {
        json["status"] = _status_;
      }
    }
    if (msg.definitions?.length) {
      json["definitions"] = msg.definitions.map(
        FactDefinitionJSON._writeMessage,
      );
    }
    return json;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: ListFactDefinitionsResponse,
    json: any,
  ): ListFactDefinitionsResponse {
    const _status_ = json["status"];
    if (_status_) {
      common.ResponseStatusJSON._readMessage(msg.status, _status_);
    }
    const _definitions_ = json["definitions"];
    if (_definitions_) {
      for (const item of _definitions_) {
        const m = FactDefinitionJSON.initialize();
        FactDefinitionJSON._readMessage(m, item);
        msg.definitions.push(m);
      }
    }
    return msg;
  },
};

export const FactValueJSON = {
  /**
   * Serializes FactValue to JSON.
   */
  encode: function (msg: PartialDeep<FactValue>): string {
    return JSON.stringify(FactValueJSON._writeMessage(msg));
  },

  /**
   * Deserializes FactValue from JSON.
   */
  decode: function (json: string): FactValue {
    return FactValueJSON._readMessage(
      FactValueJSON.initialize(),
      JSON.parse(json),
    );
  },

  /**
   * Initializes FactValue with all fields set to their default value.
   */
  initialize: function (msg?: Partial<FactValue>): FactValue {
    return {
      num: undefined,
      str: undefined,
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<FactValue>,
  ): Record<string, unknown> {
    const json: Record<string, unknown> = {};
    if (msg.num != undefined) {
      json["num"] = msg.num;
    }
    if (msg.str != undefined) {
      json["str"] = msg.str;
    }
    return json;
  },

  /**
   * @private
   */
  _readMessage: function (msg: FactValue, json: any): FactValue {
    const _num_ = json["num"];
    if (_num_) {
      msg.num = protoscript.parseDouble(_num_);
    }
    const _str_ = json["str"];
    if (_str_) {
      msg.str = _str_;
    }
    return msg;
  },
};

export const FactDeltaJSON = {
  /**
   * Serializes FactDelta to JSON.
   */
  encode: function (msg: PartialDeep<FactDelta>): string {
    return JSON.stringify(FactDeltaJSON._writeMessage(msg));
  },

  /**
   * Deserializes FactDelta from JSON.
   */
  decode: function (json: string): FactDelta {
    return FactDeltaJSON._readMessage(
      FactDeltaJSON.initialize(),
      JSON.parse(json),
    );
  },

  /**
   * Initializes FactDelta with all fields set to their default value.
   */
  initialize: function (msg?: Partial<FactDelta>): FactDelta {
    return {
      factId: "",
      revision: 0n,
      platform: "",
      subjectId: "",
      subjectName: undefined,
      op: "",
      num: undefined,
      str: undefined,
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<FactDelta>,
  ): Record<string, unknown> {
    const json: Record<string, unknown> = {};
    if (msg.factId) {
      json["factId"] = msg.factId;
    }
    if (msg.revision) {
      json["revision"] = String(msg.revision);
    }
    if (msg.platform) {
      json["platform"] = msg.platform;
    }
    if (msg.subjectId) {
      json["subjectId"] = msg.subjectId;
    }
    if (msg.subjectName != undefined) {
      json["subjectName"] = msg.subjectName;
    }
    if (msg.op) {
      json["op"] = msg.op;
    }
    if (msg.num != undefined) {
      json["num"] = msg.num;
    }
    if (msg.str != undefined) {
      json["str"] = msg.str;
    }
    return json;
  },

  /**
   * @private
   */
  _readMessage: function (msg: FactDelta, json: any): FactDelta {
    const _factId_ = json["factId"] ?? json["fact_id"];
    if (_factId_) {
      msg.factId = _factId_;
    }
    const _revision_ = json["revision"];
    if (_revision_) {
      msg.revision = BigInt(_revision_);
    }
    const _platform_ = json["platform"];
    if (_platform_) {
      msg.platform = _platform_;
    }
    const _subjectId_ = json["subjectId"] ?? json["subject_id"];
    if (_subjectId_) {
      msg.subjectId = _subjectId_;
    }
    const _subjectName_ = json["subjectName"] ?? json["subject_name"];
    if (_subjectName_) {
      msg.subjectName = _subjectName_;
    }
    const _op_ = json["op"];
    if (_op_) {
      msg.op = _op_;
    }
    const _num_ = json["num"];
    if (_num_) {
      msg.num = protoscript.parseDouble(_num_);
    }
    const _str_ = json["str"];
    if (_str_) {
      msg.str = _str_;
    }
    return msg;
  },
};

export const ApplyFactDeltasRequestJSON = {
  /**
   * Serializes ApplyFactDeltasRequest to JSON.
   */
  encode: function (msg: PartialDeep<ApplyFactDeltasRequest>): string {
    return JSON.stringify(ApplyFactDeltasRequestJSON._writeMessage(msg));
  },

  /**
   * Deserializes ApplyFactDeltasRequest from JSON.
   */
  decode: function (json: string): ApplyFactDeltasRequest {
    return ApplyFactDeltasRequestJSON._readMessage(
      ApplyFactDeltasRequestJSON.initialize(),
      JSON.parse(json),
    );
  },

  /**
   * Initializes ApplyFactDeltasRequest with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<ApplyFactDeltasRequest>,
  ): ApplyFactDeltasRequest {
    return {
      source: "",
      eventId: "",
      occurredAt: protoscript.TimestampJSON.initialize(),
      sessionStamp: "",
      silent: false,
      deltas: [],
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<ApplyFactDeltasRequest>,
  ): Record<string, unknown> {
    const json: Record<string, unknown> = {};
    if (msg.source) {
      json["source"] = msg.source;
    }
    if (msg.eventId) {
      json["eventId"] = msg.eventId;
    }
    if (msg.occurredAt && (msg.occurredAt.seconds || msg.occurredAt.nanos)) {
      json["occurredAt"] = protoscript.serializeTimestamp(msg.occurredAt);
    }
    if (msg.sessionStamp) {
      json["sessionStamp"] = msg.sessionStamp;
    }
    if (msg.silent) {
      json["silent"] = msg.silent;
    }
    if (msg.deltas?.length) {
      json["deltas"] = msg.deltas.map(FactDeltaJSON._writeMessage);
    }
    return json;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: ApplyFactDeltasRequest,
    json: any,
  ): ApplyFactDeltasRequest {
    const _source_ = json["source"];
    if (_source_) {
      msg.source = _source_;
    }
    const _eventId_ = json["eventId"] ?? json["event_id"];
    if (_eventId_) {
      msg.eventId = _eventId_;
    }
    const _occurredAt_ = json["occurredAt"] ?? json["occurred_at"];
    if (_occurredAt_) {
      msg.occurredAt = protoscript.parseTimestamp(_occurredAt_);
    }
    const _sessionStamp_ = json["sessionStamp"] ?? json["session_stamp"];
    if (_sessionStamp_) {
      msg.sessionStamp = _sessionStamp_;
    }
    const _silent_ = json["silent"];
    if (_silent_) {
      msg.silent = _silent_;
    }
    const _deltas_ = json["deltas"];
    if (_deltas_) {
      for (const item of _deltas_) {
        const m = FactDeltaJSON.initialize();
        FactDeltaJSON._readMessage(m, item);
        msg.deltas.push(m);
      }
    }
    return msg;
  },
};

export const FactValueChangeJSON = {
  /**
   * Serializes FactValueChange to JSON.
   */
  encode: function (msg: PartialDeep<FactValueChange>): string {
    return JSON.stringify(FactValueChangeJSON._writeMessage(msg));
  },

  /**
   * Deserializes FactValueChange from JSON.
   */
  decode: function (json: string): FactValueChange {
    return FactValueChangeJSON._readMessage(
      FactValueChangeJSON.initialize(),
      JSON.parse(json),
    );
  },

  /**
   * Initializes FactValueChange with all fields set to their default value.
   */
  initialize: function (msg?: Partial<FactValueChange>): FactValueChange {
    return {
      factId: "",
      platform: "",
      subjectId: "",
      windowKey: "",
      subjectName: undefined,
      before: FactValueJSON.initialize(),
      after: FactValueJSON.initialize(),
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<FactValueChange>,
  ): Record<string, unknown> {
    const json: Record<string, unknown> = {};
    if (msg.factId) {
      json["factId"] = msg.factId;
    }
    if (msg.platform) {
      json["platform"] = msg.platform;
    }
    if (msg.subjectId) {
      json["subjectId"] = msg.subjectId;
    }
    if (msg.windowKey) {
      json["windowKey"] = msg.windowKey;
    }
    if (msg.subjectName != undefined) {
      json["subjectName"] = msg.subjectName;
    }
    if (msg.before) {
      const _before_ = FactValueJSON._writeMessage(msg.before);
      if (Object.keys(_before_).length > 0) {
        json["before"] = _before_;
      }
    }
    if (msg.after) {
      const _after_ = FactValueJSON._writeMessage(msg.after);
      if (Object.keys(_after_).length > 0) {
        json["after"] = _after_;
      }
    }
    return json;
  },

  /**
   * @private
   */
  _readMessage: function (msg: FactValueChange, json: any): FactValueChange {
    const _factId_ = json["factId"] ?? json["fact_id"];
    if (_factId_) {
      msg.factId = _factId_;
    }
    const _platform_ = json["platform"];
    if (_platform_) {
      msg.platform = _platform_;
    }
    const _subjectId_ = json["subjectId"] ?? json["subject_id"];
    if (_subjectId_) {
      msg.subjectId = _subjectId_;
    }
    const _windowKey_ = json["windowKey"] ?? json["window_key"];
    if (_windowKey_) {
      msg.windowKey = _windowKey_;
    }
    const _subjectName_ = json["subjectName"] ?? json["subject_name"];
    if (_subjectName_) {
      msg.subjectName = _subjectName_;
    }
    const _before_ = json["before"];
    if (_before_) {
      FactValueJSON._readMessage(msg.before, _before_);
    }
    const _after_ = json["after"];
    if (_after_) {
      FactValueJSON._readMessage(msg.after, _after_);
    }
    return msg;
  },
};

export const ApplyFactDeltasResponseJSON = {
  /**
   * Serializes ApplyFactDeltasResponse to JSON.
   */
  encode: function (msg: PartialDeep<ApplyFactDeltasResponse>): string {
    return JSON.stringify(ApplyFactDeltasResponseJSON._writeMessage(msg));
  },

  /**
   * Deserializes ApplyFactDeltasResponse from JSON.
   */
  decode: function (json: string): ApplyFactDeltasResponse {
    return ApplyFactDeltasResponseJSON._readMessage(
      ApplyFactDeltasResponseJSON.initialize(),
      JSON.parse(json),
    );
  },

  /**
   * Initializes ApplyFactDeltasResponse with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<ApplyFactDeltasResponse>,
  ): ApplyFactDeltasResponse {
    return {
      status: common.ResponseStatusJSON.initialize(),
      applied: false,
      dropped: 0,
      changes: [],
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<ApplyFactDeltasResponse>,
  ): Record<string, unknown> {
    const json: Record<string, unknown> = {};
    if (msg.status) {
      const _status_ = common.ResponseStatusJSON._writeMessage(msg.status);
      if (Object.keys(_status_).length > 0) {
        json["status"] = _status_;
      }
    }
    if (msg.applied) {
      json["applied"] = msg.applied;
    }
    if (msg.dropped) {
      json["dropped"] = msg.dropped;
    }
    if (msg.changes?.length) {
      json["changes"] = msg.changes.map(FactValueChangeJSON._writeMessage);
    }
    return json;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: ApplyFactDeltasResponse,
    json: any,
  ): ApplyFactDeltasResponse {
    const _status_ = json["status"];
    if (_status_) {
      common.ResponseStatusJSON._readMessage(msg.status, _status_);
    }
    const _applied_ = json["applied"];
    if (_applied_) {
      msg.applied = _applied_;
    }
    const _dropped_ = json["dropped"];
    if (_dropped_) {
      msg.dropped = protoscript.parseNumber(_dropped_);
    }
    const _changes_ = json["changes"];
    if (_changes_) {
      for (const item of _changes_) {
        const m = FactValueChangeJSON.initialize();
        FactValueChangeJSON._readMessage(m, item);
        msg.changes.push(m);
      }
    }
    return msg;
  },
};

export const GetViewerFactsRequestJSON = {
  /**
   * Serializes GetViewerFactsRequest to JSON.
   */
  encode: function (msg: PartialDeep<GetViewerFactsRequest>): string {
    return JSON.stringify(GetViewerFactsRequestJSON._writeMessage(msg));
  },

  /**
   * Deserializes GetViewerFactsRequest from JSON.
   */
  decode: function (json: string): GetViewerFactsRequest {
    return GetViewerFactsRequestJSON._readMessage(
      GetViewerFactsRequestJSON.initialize(),
      JSON.parse(json),
    );
  },

  /**
   * Initializes GetViewerFactsRequest with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<GetViewerFactsRequest>,
  ): GetViewerFactsRequest {
    return {
      platform: "",
      subjectId: "",
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<GetViewerFactsRequest>,
  ): Record<string, unknown> {
    const json: Record<string, unknown> = {};
    if (msg.platform) {
      json["platform"] = msg.platform;
    }
    if (msg.subjectId) {
      json["subjectId"] = msg.subjectId;
    }
    return json;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: GetViewerFactsRequest,
    json: any,
  ): GetViewerFactsRequest {
    const _platform_ = json["platform"];
    if (_platform_) {
      msg.platform = _platform_;
    }
    const _subjectId_ = json["subjectId"] ?? json["subject_id"];
    if (_subjectId_) {
      msg.subjectId = _subjectId_;
    }
    return msg;
  },
};

export const ViewerFactValueJSON = {
  /**
   * Serializes ViewerFactValue to JSON.
   */
  encode: function (msg: PartialDeep<ViewerFactValue>): string {
    return JSON.stringify(ViewerFactValueJSON._writeMessage(msg));
  },

  /**
   * Deserializes ViewerFactValue from JSON.
   */
  decode: function (json: string): ViewerFactValue {
    return ViewerFactValueJSON._readMessage(
      ViewerFactValueJSON.initialize(),
      JSON.parse(json),
    );
  },

  /**
   * Initializes ViewerFactValue with all fields set to their default value.
   */
  initialize: function (msg?: Partial<ViewerFactValue>): ViewerFactValue {
    return {
      factId: "",
      windowKind: "",
      valueKind: "",
      value: FactValueJSON.initialize(),
      updatedAt: protoscript.TimestampJSON.initialize(),
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<ViewerFactValue>,
  ): Record<string, unknown> {
    const json: Record<string, unknown> = {};
    if (msg.factId) {
      json["factId"] = msg.factId;
    }
    if (msg.windowKind) {
      json["windowKind"] = msg.windowKind;
    }
    if (msg.valueKind) {
      json["valueKind"] = msg.valueKind;
    }
    if (msg.value) {
      const _value_ = FactValueJSON._writeMessage(msg.value);
      if (Object.keys(_value_).length > 0) {
        json["value"] = _value_;
      }
    }
    if (msg.updatedAt && (msg.updatedAt.seconds || msg.updatedAt.nanos)) {
      json["updatedAt"] = protoscript.serializeTimestamp(msg.updatedAt);
    }
    return json;
  },

  /**
   * @private
   */
  _readMessage: function (msg: ViewerFactValue, json: any): ViewerFactValue {
    const _factId_ = json["factId"] ?? json["fact_id"];
    if (_factId_) {
      msg.factId = _factId_;
    }
    const _windowKind_ = json["windowKind"] ?? json["window_kind"];
    if (_windowKind_) {
      msg.windowKind = _windowKind_;
    }
    const _valueKind_ = json["valueKind"] ?? json["value_kind"];
    if (_valueKind_) {
      msg.valueKind = _valueKind_;
    }
    const _value_ = json["value"];
    if (_value_) {
      FactValueJSON._readMessage(msg.value, _value_);
    }
    const _updatedAt_ = json["updatedAt"] ?? json["updated_at"];
    if (_updatedAt_) {
      msg.updatedAt = protoscript.parseTimestamp(_updatedAt_);
    }
    return msg;
  },
};

export const GetViewerFactsResponseJSON = {
  /**
   * Serializes GetViewerFactsResponse to JSON.
   */
  encode: function (msg: PartialDeep<GetViewerFactsResponse>): string {
    return JSON.stringify(GetViewerFactsResponseJSON._writeMessage(msg));
  },

  /**
   * Deserializes GetViewerFactsResponse from JSON.
   */
  decode: function (json: string): GetViewerFactsResponse {
    return GetViewerFactsResponseJSON._readMessage(
      GetViewerFactsResponseJSON.initialize(),
      JSON.parse(json),
    );
  },

  /**
   * Initializes GetViewerFactsResponse with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<GetViewerFactsResponse>,
  ): GetViewerFactsResponse {
    return {
      status: common.ResponseStatusJSON.initialize(),
      sessionId: "",
      subjectName: undefined,
      values: [],
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<GetViewerFactsResponse>,
  ): Record<string, unknown> {
    const json: Record<string, unknown> = {};
    if (msg.status) {
      const _status_ = common.ResponseStatusJSON._writeMessage(msg.status);
      if (Object.keys(_status_).length > 0) {
        json["status"] = _status_;
      }
    }
    if (msg.sessionId) {
      json["sessionId"] = msg.sessionId;
    }
    if (msg.subjectName != undefined) {
      json["subjectName"] = msg.subjectName;
    }
    if (msg.values?.length) {
      json["values"] = msg.values.map(ViewerFactValueJSON._writeMessage);
    }
    return json;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: GetViewerFactsResponse,
    json: any,
  ): GetViewerFactsResponse {
    const _status_ = json["status"];
    if (_status_) {
      common.ResponseStatusJSON._readMessage(msg.status, _status_);
    }
    const _sessionId_ = json["sessionId"] ?? json["session_id"];
    if (_sessionId_) {
      msg.sessionId = _sessionId_;
    }
    const _subjectName_ = json["subjectName"] ?? json["subject_name"];
    if (_subjectName_) {
      msg.subjectName = _subjectName_;
    }
    const _values_ = json["values"];
    if (_values_) {
      for (const item of _values_) {
        const m = ViewerFactValueJSON.initialize();
        ViewerFactValueJSON._readMessage(m, item);
        msg.values.push(m);
      }
    }
    return msg;
  },
};
