// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WidgetStatus {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub application_id: ::prost::alloc::string::String,
    /// Module that owns the widget definition. Denormalised from the
    /// scene's widgets_json so consumers can group by module without
    /// joining.
    #[prost(string, tag="3")]
    pub module_id: ::prost::alloc::string::String,
    /// Stable per-placement instance id from `WidgetInstance.id`.
    #[prost(string, tag="4")]
    pub instance_id: ::prost::alloc::string::String,
    /// Canonical `{moduleId}:widget:{manifestId}`. Empty when the
    /// placement didn't surface it.
    #[prost(string, tag="5")]
    pub widget_canonical_id: ::prost::alloc::string::String,
    /// Caller-defined report key (e.g. "count", "goalReached",
    /// "elapsedSeconds").
    #[prost(string, tag="6")]
    pub key: ::prost::alloc::string::String,
    /// Opaque JSON-encoded value. Engine treats as bytes — consumers
    /// parse based on the widget's documented schema.
    #[prost(string, tag="7")]
    pub value: ::prost::alloc::string::String,
    /// When the widget reported this value (set by the scene overlay,
    /// not the engine). Carried verbatim so dashboards display the
    /// event time, not the persistence time.
    #[prost(message, optional, tag="8")]
    pub occurred_at: ::core::option::Option<::pbjson_types::Timestamp>,
    #[prost(message, optional, tag="9")]
    pub created_at: ::core::option::Option<::pbjson_types::Timestamp>,
    #[prost(message, optional, tag="10")]
    pub updated_at: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpsertWidgetStatusRequest {
    #[prost(string, tag="1")]
    pub application_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub module_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub instance_id: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub widget_canonical_id: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub key: ::prost::alloc::string::String,
    /// JSON-encoded value (string).
    #[prost(string, tag="6")]
    pub value: ::prost::alloc::string::String,
    /// Optional ISO-8601 timestamp from the overlay; the service stamps
    /// `now()` when omitted.
    #[prost(string, tag="7")]
    pub occurred_at: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetWidgetStatusRequest {
    #[prost(string, tag="1")]
    pub application_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub instance_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub key: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WidgetStatusResponse {
    #[prost(message, optional, tag="1")]
    pub status: ::core::option::Option<super::common::ResponseStatus>,
    #[prost(message, optional, tag="2")]
    pub widget_status: ::core::option::Option<WidgetStatus>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListWidgetStatusRequest {
    #[prost(string, tag="1")]
    pub application_id: ::prost::alloc::string::String,
    /// Optional filters. Empty string = no filter.
    #[prost(string, tag="2")]
    pub module_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub instance_id: ::prost::alloc::string::String,
    #[prost(int32, tag="4")]
    pub limit: i32,
    #[prost(int32, tag="5")]
    pub offset: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListWidgetStatusResponse {
    #[prost(message, optional, tag="1")]
    pub status: ::core::option::Option<super::common::ResponseStatus>,
    #[prost(message, repeated, tag="2")]
    pub rows: ::prost::alloc::vec::Vec<WidgetStatus>,
    #[prost(int64, tag="3")]
    pub total_count: i64,
    #[prost(int32, tag="4")]
    pub limit: i32,
    #[prost(int32, tag="5")]
    pub offset: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteWidgetStatusRequest {
    #[prost(string, tag="1")]
    pub application_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub instance_id: ::prost::alloc::string::String,
    /// Optional: when omitted, deletes every row for the instance.
    #[prost(string, tag="3")]
    pub key: ::prost::alloc::string::String,
}
include!("widget_status.serde.rs");
include!("widget_status.tonic.rs");
// @@protoc_insertion_point(module)